/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


#include <iostream>

#include "gc/allocator/rosalloc.h"

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace gc {
namespace allocator {
std::ostream& operator<<(std::ostream& os, const RosAlloc::PageReleaseMode& rhs) {
  switch (rhs) {
    case RosAlloc::kPageReleaseModeNone: os << "PageReleaseModeNone"; break;
    case RosAlloc::kPageReleaseModeEnd: os << "PageReleaseModeEnd"; break;
    case RosAlloc::kPageReleaseModeSize: os << "PageReleaseModeSize"; break;
    case RosAlloc::kPageReleaseModeSizeAndEnd: os << "PageReleaseModeSizeAndEnd"; break;
    case RosAlloc::kPageReleaseModeAll: os << "PageReleaseModeAll"; break;
    default: os << "RosAlloc::PageReleaseMode[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace allocator
}  // namespace gc
}  // namespace art

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace gc {
namespace allocator {
std::ostream& operator<<(std::ostream& os, const RosAlloc::PageMapKind& rhs) {
  switch (rhs) {
    case RosAlloc::kPageMapReleased: os << "PageMapReleased"; break;
    case RosAlloc::kPageMapEmpty: os << "PageMapEmpty"; break;
    case RosAlloc::kPageMapRun: os << "PageMapRun"; break;
    case RosAlloc::kPageMapRunPart: os << "PageMapRunPart"; break;
    case RosAlloc::kPageMapLargeObject: os << "PageMapLargeObject"; break;
    case RosAlloc::kPageMapLargeObjectPart: os << "PageMapLargeObjectPart"; break;
    default: os << "RosAlloc::PageMapKind[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace allocator
}  // namespace gc
}  // namespace art

