/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


#include <iostream>

#include "gc/space/space.h"

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace gc {
namespace space {
std::ostream& operator<<(std::ostream& os, const SpaceType& rhs) {
  switch (rhs) {
    case kSpaceTypeImageSpace: os << "SpaceTypeImageSpace"; break;
    case kSpaceTypeMallocSpace: os << "SpaceTypeMallocSpace"; break;
    case kSpaceTypeZygoteSpace: os << "SpaceTypeZygoteSpace"; break;
    case kSpaceTypeBumpPointerSpace: os << "SpaceTypeBumpPointerSpace"; break;
    case kSpaceTypeLargeObjectSpace: os << "SpaceTypeLargeObjectSpace"; break;
    case kSpaceTypeRegionSpace: os << "SpaceTypeRegionSpace"; break;
    default: os << "SpaceType[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace space
}  // namespace gc
}  // namespace art

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace gc {
namespace space {
std::ostream& operator<<(std::ostream& os, const GcRetentionPolicy& rhs) {
  switch (rhs) {
    case kGcRetentionPolicyNeverCollect: os << "GcRetentionPolicyNeverCollect"; break;
    case kGcRetentionPolicyAlwaysCollect: os << "GcRetentionPolicyAlwaysCollect"; break;
    case kGcRetentionPolicyFullCollect: os << "GcRetentionPolicyFullCollect"; break;
    default: os << "GcRetentionPolicy[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace space
}  // namespace gc
}  // namespace art

