---
- hosts: win-test-servers
  tasks:
  - name: Pre-Clean test directory
    win_file: path=testing-moe-natj-cxx state=absent
  - name: Create test directory
    win_file: path=testing-moe-natj-cxx state=directory
  - name: Copy files
    win_copy: src=build/distributions/win-test.tar dest=testing-moe-natj-cxx/
  - name: Unzip tests
    win_unzip:
      src: testing-moe-natj-cxx/win-test.tar
      dest: testing-moe-natj-cxx/win-test
      rm: yes
  - name: Run tests
    raw: powershell -command ./testing-moe-natj-cxx/win-test/run.ps1