//
//  OpenGLES_ES1_Defines.h
//

#ifndef __OpenGLES_ES1_Defines_H
#define __OpenGLES_ES1_Defines_H

#include <OpenGLES/ES1/gl.h>
#include <OpenGLES/ES1/glext.h>

enum _ES1_ {
    
    /*************************************************************/
    /*                            gl.h                           */
    /*************************************************************/
    
    /* OpenGL ES core versions */
    _ES1_GL_VERSION_ES_CM_1_0 = GL_VERSION_ES_CM_1_0,
    _ES1_GL_VERSION_ES_CL_1_0 = GL_VERSION_ES_CL_1_0,
    _ES1_GL_VERSION_ES_CM_1_1 = GL_VERSION_ES_CM_1_1,
    _ES1_GL_VERSION_ES_CL_1_1 = GL_VERSION_ES_CL_1_1,
    
    /* Legacy core versions */
    _ES1_GL_OES_VERSION_1_0 = GL_OES_VERSION_1_0,
    _ES1_GL_OES_VERSION_1_1 = GL_OES_VERSION_1_1,
    
    /* Extensions */
    _ES1_GL_OES_byte_coordinates = GL_OES_byte_coordinates,
    _ES1_GL_OES_compressed_paletted_texture = GL_OES_compressed_paletted_texture,
    _ES1_GL_OES_draw_texture = GL_OES_draw_texture,
    _ES1_GL_OES_fixed_point = GL_OES_fixed_point,
    _ES1_GL_OES_matrix_get = GL_OES_matrix_get,
    _ES1_GL_OES_matrix_palette = GL_OES_matrix_palette,
    _ES1_GL_OES_point_size_array = GL_OES_point_size_array,
    _ES1_GL_OES_point_sprite = GL_OES_point_sprite,
    _ES1_GL_OES_read_format = GL_OES_read_format,
    _ES1_GL_OES_single_precision = GL_OES_single_precision,
    
    /* ClearBufferMask */
    _ES1_GL_DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT,
    _ES1_GL_STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT,
    _ES1_GL_COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT,
    
    /* Boolean */
    _ES1_GL_FALSE = GL_FALSE,
    _ES1_GL_TRUE = GL_TRUE,
    
    /* BeginMode */
    _ES1_GL_POINTS = GL_POINTS,
    _ES1_GL_LINES = GL_LINES,
    _ES1_GL_LINE_LOOP = GL_LINE_LOOP,
    _ES1_GL_LINE_STRIP = GL_LINE_STRIP,
    _ES1_GL_TRIANGLES = GL_TRIANGLES,
    _ES1_GL_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
    _ES1_GL_TRIANGLE_FAN = GL_TRIANGLE_FAN,
    
    /* AlphaFunction */
    _ES1_GL_NEVER = GL_NEVER,
    _ES1_GL_LESS = GL_LESS,
    _ES1_GL_EQUAL = GL_EQUAL,
    _ES1_GL_LEQUAL = GL_LEQUAL,
    _ES1_GL_GREATER = GL_GREATER,
    _ES1_GL_NOTEQUAL = GL_NOTEQUAL,
    _ES1_GL_GEQUAL = GL_GEQUAL,
    _ES1_GL_ALWAYS = GL_ALWAYS,
    
    /* BlendingFactorDest */
    _ES1_GL_ZERO = GL_ZERO,
    _ES1_GL_ONE = GL_ONE,
    _ES1_GL_SRC_COLOR = GL_SRC_COLOR,
    _ES1_GL_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR,
    _ES1_GL_SRC_ALPHA = GL_SRC_ALPHA,
    _ES1_GL_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
    _ES1_GL_DST_ALPHA = GL_DST_ALPHA,
    _ES1_GL_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
    
    /* BlendingFactorSrc */
    /*      GL_ZERO */
    /*      GL_ONE */
    _ES1_GL_DST_COLOR = GL_DST_COLOR,
    _ES1_GL_ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR,
    _ES1_GL_SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE,
    /*      GL_SRC_ALPHA */
    /*      GL_ONE_MINUS_SRC_ALPHA */
    /*      GL_DST_ALPHA */
    /*      GL_ONE_MINUS_DST_ALPHA */
    
    /* ClipPlaneName */
    _ES1_GL_CLIP_PLANE0 = GL_CLIP_PLANE0,
    _ES1_GL_CLIP_PLANE1 = GL_CLIP_PLANE1,
    _ES1_GL_CLIP_PLANE2 = GL_CLIP_PLANE2,
    _ES1_GL_CLIP_PLANE3 = GL_CLIP_PLANE3,
    _ES1_GL_CLIP_PLANE4 = GL_CLIP_PLANE4,
    _ES1_GL_CLIP_PLANE5 = GL_CLIP_PLANE5,
    
    /* ColorMaterialFace */
    /*      GL_FRONT_AND_BACK */
    
    /* ColorMaterialParameter */
    /*      GL_AMBIENT_AND_DIFFUSE */
    
    /* ColorPointerType */
    /*      GL_UNSIGNED_BYTE */
    /*      GL_FLOAT */
    /*      GL_FIXED */
    
    /* CullFaceMode */
    _ES1_GL_FRONT = GL_FRONT,
    _ES1_GL_BACK = GL_BACK,
    _ES1_GL_FRONT_AND_BACK = GL_FRONT_AND_BACK,
    
    /* DepthFunction */
    /*      GL_NEVER */
    /*      GL_LESS */
    /*      GL_EQUAL */
    /*      GL_LEQUAL */
    /*      GL_GREATER */
    /*      GL_NOTEQUAL */
    /*      GL_GEQUAL */
    /*      GL_ALWAYS */
    
    /* EnableCap */
    _ES1_GL_FOG = GL_FOG,
    _ES1_GL_LIGHTING = GL_LIGHTING,
    _ES1_GL_TEXTURE_2D = GL_TEXTURE_2D,
    _ES1_GL_CULL_FACE = GL_CULL_FACE,
    _ES1_GL_ALPHA_TEST = GL_ALPHA_TEST,
    _ES1_GL_BLEND = GL_BLEND,
    _ES1_GL_COLOR_LOGIC_OP = GL_COLOR_LOGIC_OP,
    _ES1_GL_DITHER = GL_DITHER,
    _ES1_GL_STENCIL_TEST = GL_STENCIL_TEST,
    _ES1_GL_DEPTH_TEST = GL_DEPTH_TEST,
    /*      GL_LIGHT0 */
    /*      GL_LIGHT1 */
    /*      GL_LIGHT2 */
    /*      GL_LIGHT3 */
    /*      GL_LIGHT4 */
    /*      GL_LIGHT5 */
    /*      GL_LIGHT6 */
    /*      GL_LIGHT7 */
    _ES1_GL_POINT_SMOOTH = GL_POINT_SMOOTH,
    _ES1_GL_LINE_SMOOTH = GL_LINE_SMOOTH,
    _ES1_GL_SCISSOR_TEST = GL_SCISSOR_TEST,
    _ES1_GL_COLOR_MATERIAL = GL_COLOR_MATERIAL,
    _ES1_GL_NORMALIZE = GL_NORMALIZE,
    _ES1_GL_RESCALE_NORMAL = GL_RESCALE_NORMAL,
    _ES1_GL_POLYGON_OFFSET_FILL = GL_POLYGON_OFFSET_FILL,
    _ES1_GL_VERTEX_ARRAY = GL_VERTEX_ARRAY,
    _ES1_GL_NORMAL_ARRAY = GL_NORMAL_ARRAY,
    _ES1_GL_COLOR_ARRAY = GL_COLOR_ARRAY,
    _ES1_GL_TEXTURE_COORD_ARRAY = GL_TEXTURE_COORD_ARRAY,
    _ES1_GL_MULTISAMPLE = GL_MULTISAMPLE,
    _ES1_GL_SAMPLE_ALPHA_TO_COVERAGE = GL_SAMPLE_ALPHA_TO_COVERAGE,
    _ES1_GL_SAMPLE_ALPHA_TO_ONE = GL_SAMPLE_ALPHA_TO_ONE,
    _ES1_GL_SAMPLE_COVERAGE = GL_SAMPLE_COVERAGE,
    
    /* ErrorCode */
    _ES1_GL_NO_ERROR = GL_NO_ERROR,
    _ES1_GL_INVALID_ENUM = GL_INVALID_ENUM,
    _ES1_GL_INVALID_VALUE = GL_INVALID_VALUE,
    _ES1_GL_INVALID_OPERATION = GL_INVALID_OPERATION,
    _ES1_GL_STACK_OVERFLOW = GL_STACK_OVERFLOW,
    _ES1_GL_STACK_UNDERFLOW = GL_STACK_UNDERFLOW,
    _ES1_GL_OUT_OF_MEMORY = GL_OUT_OF_MEMORY,
    
    /* FogMode */
    /*      GL_LINEAR */
    _ES1_GL_EXP = GL_EXP,
    _ES1_GL_EXP2 = GL_EXP2,
    
    /* FogParameter */
    _ES1_GL_FOG_DENSITY = GL_FOG_DENSITY,
    _ES1_GL_FOG_START = GL_FOG_START,
    _ES1_GL_FOG_END = GL_FOG_END,
    _ES1_GL_FOG_MODE = GL_FOG_MODE,
    _ES1_GL_FOG_COLOR = GL_FOG_COLOR,
    
    /* FrontFaceDirection */
    _ES1_GL_CW = GL_CW,
    _ES1_GL_CCW = GL_CCW,
    
    /* GetPName */
    _ES1_GL_CURRENT_COLOR = GL_CURRENT_COLOR,
    _ES1_GL_CURRENT_NORMAL = GL_CURRENT_NORMAL,
    _ES1_GL_CURRENT_TEXTURE_COORDS = GL_CURRENT_TEXTURE_COORDS,
    _ES1_GL_POINT_SIZE = GL_POINT_SIZE,
    _ES1_GL_POINT_SIZE_MIN = GL_POINT_SIZE_MIN,
    _ES1_GL_POINT_SIZE_MAX = GL_POINT_SIZE_MAX,
    _ES1_GL_POINT_FADE_THRESHOLD_SIZE = GL_POINT_FADE_THRESHOLD_SIZE,
    _ES1_GL_POINT_DISTANCE_ATTENUATION = GL_POINT_DISTANCE_ATTENUATION,
    _ES1_GL_SMOOTH_POINT_SIZE_RANGE = GL_SMOOTH_POINT_SIZE_RANGE,
    _ES1_GL_LINE_WIDTH = GL_LINE_WIDTH,
    _ES1_GL_SMOOTH_LINE_WIDTH_RANGE = GL_SMOOTH_LINE_WIDTH_RANGE,
    _ES1_GL_ALIASED_POINT_SIZE_RANGE = GL_ALIASED_POINT_SIZE_RANGE,
    _ES1_GL_ALIASED_LINE_WIDTH_RANGE = GL_ALIASED_LINE_WIDTH_RANGE,
    _ES1_GL_CULL_FACE_MODE = GL_CULL_FACE_MODE,
    _ES1_GL_FRONT_FACE = GL_FRONT_FACE,
    _ES1_GL_SHADE_MODEL = GL_SHADE_MODEL,
    _ES1_GL_DEPTH_RANGE = GL_DEPTH_RANGE,
    _ES1_GL_DEPTH_WRITEMASK = GL_DEPTH_WRITEMASK,
    _ES1_GL_DEPTH_CLEAR_VALUE = GL_DEPTH_CLEAR_VALUE,
    _ES1_GL_DEPTH_FUNC = GL_DEPTH_FUNC,
    _ES1_GL_STENCIL_CLEAR_VALUE = GL_STENCIL_CLEAR_VALUE,
    _ES1_GL_STENCIL_FUNC = GL_STENCIL_FUNC,
    _ES1_GL_STENCIL_VALUE_MASK = GL_STENCIL_VALUE_MASK,
    _ES1_GL_STENCIL_FAIL = GL_STENCIL_FAIL,
    _ES1_GL_STENCIL_PASS_DEPTH_FAIL = GL_STENCIL_PASS_DEPTH_FAIL,
    _ES1_GL_STENCIL_PASS_DEPTH_PASS = GL_STENCIL_PASS_DEPTH_PASS,
    _ES1_GL_STENCIL_REF = GL_STENCIL_REF,
    _ES1_GL_STENCIL_WRITEMASK = GL_STENCIL_WRITEMASK,
    _ES1_GL_MATRIX_MODE = GL_MATRIX_MODE,
    _ES1_GL_VIEWPORT = GL_VIEWPORT,
    _ES1_GL_MODELVIEW_STACK_DEPTH = GL_MODELVIEW_STACK_DEPTH,
    _ES1_GL_PROJECTION_STACK_DEPTH = GL_PROJECTION_STACK_DEPTH,
    _ES1_GL_TEXTURE_STACK_DEPTH = GL_TEXTURE_STACK_DEPTH,
    _ES1_GL_MODELVIEW_MATRIX = GL_MODELVIEW_MATRIX,
    _ES1_GL_PROJECTION_MATRIX = GL_PROJECTION_MATRIX,
    _ES1_GL_TEXTURE_MATRIX = GL_TEXTURE_MATRIX,
    _ES1_GL_ALPHA_TEST_FUNC = GL_ALPHA_TEST_FUNC,
    _ES1_GL_ALPHA_TEST_REF = GL_ALPHA_TEST_REF,
    _ES1_GL_BLEND_DST = GL_BLEND_DST,
    _ES1_GL_BLEND_SRC = GL_BLEND_SRC,
    _ES1_GL_LOGIC_OP_MODE = GL_LOGIC_OP_MODE,
    _ES1_GL_SCISSOR_BOX = GL_SCISSOR_BOX,
    //_ES1_GL_SCISSOR_TEST = GL_SCISSOR_TEST,
    _ES1_GL_COLOR_CLEAR_VALUE = GL_COLOR_CLEAR_VALUE,
    _ES1_GL_COLOR_WRITEMASK = GL_COLOR_WRITEMASK,
    _ES1_GL_UNPACK_ALIGNMENT = GL_UNPACK_ALIGNMENT,
    _ES1_GL_PACK_ALIGNMENT = GL_PACK_ALIGNMENT,
    _ES1_GL_MAX_LIGHTS = GL_MAX_LIGHTS,
    _ES1_GL_MAX_CLIP_PLANES = GL_MAX_CLIP_PLANES,
    _ES1_GL_MAX_TEXTURE_SIZE = GL_MAX_TEXTURE_SIZE,
    _ES1_GL_MAX_MODELVIEW_STACK_DEPTH = GL_MAX_MODELVIEW_STACK_DEPTH,
    _ES1_GL_MAX_PROJECTION_STACK_DEPTH = GL_MAX_PROJECTION_STACK_DEPTH,
    _ES1_GL_MAX_TEXTURE_STACK_DEPTH = GL_MAX_TEXTURE_STACK_DEPTH,
    _ES1_GL_MAX_VIEWPORT_DIMS = GL_MAX_VIEWPORT_DIMS,
    _ES1_GL_MAX_TEXTURE_UNITS = GL_MAX_TEXTURE_UNITS,
    _ES1_GL_SUBPIXEL_BITS = GL_SUBPIXEL_BITS,
    _ES1_GL_RED_BITS = GL_RED_BITS,
    _ES1_GL_GREEN_BITS = GL_GREEN_BITS,
    _ES1_GL_BLUE_BITS = GL_BLUE_BITS,
    _ES1_GL_ALPHA_BITS = GL_ALPHA_BITS,
    _ES1_GL_DEPTH_BITS = GL_DEPTH_BITS,
    _ES1_GL_STENCIL_BITS = GL_STENCIL_BITS,
    _ES1_GL_POLYGON_OFFSET_UNITS = GL_POLYGON_OFFSET_UNITS,
    //_ES1_GL_POLYGON_OFFSET_FILL = GL_POLYGON_OFFSET_FILL,
    _ES1_GL_POLYGON_OFFSET_FACTOR = GL_POLYGON_OFFSET_FACTOR,
    _ES1_GL_TEXTURE_BINDING_2D = GL_TEXTURE_BINDING_2D,
    _ES1_GL_VERTEX_ARRAY_SIZE = GL_VERTEX_ARRAY_SIZE,
    _ES1_GL_VERTEX_ARRAY_TYPE = GL_VERTEX_ARRAY_TYPE,
    _ES1_GL_VERTEX_ARRAY_STRIDE = GL_VERTEX_ARRAY_STRIDE,
    _ES1_GL_NORMAL_ARRAY_TYPE = GL_NORMAL_ARRAY_TYPE,
    _ES1_GL_NORMAL_ARRAY_STRIDE = GL_NORMAL_ARRAY_STRIDE,
    _ES1_GL_COLOR_ARRAY_SIZE = GL_COLOR_ARRAY_SIZE,
    _ES1_GL_COLOR_ARRAY_TYPE = GL_COLOR_ARRAY_TYPE,
    _ES1_GL_COLOR_ARRAY_STRIDE = GL_COLOR_ARRAY_STRIDE,
    _ES1_GL_TEXTURE_COORD_ARRAY_SIZE = GL_TEXTURE_COORD_ARRAY_SIZE,
    _ES1_GL_TEXTURE_COORD_ARRAY_TYPE = GL_TEXTURE_COORD_ARRAY_TYPE,
    _ES1_GL_TEXTURE_COORD_ARRAY_STRIDE = GL_TEXTURE_COORD_ARRAY_STRIDE,
    _ES1_GL_VERTEX_ARRAY_POINTER = GL_VERTEX_ARRAY_POINTER,
    _ES1_GL_NORMAL_ARRAY_POINTER = GL_NORMAL_ARRAY_POINTER,
    _ES1_GL_COLOR_ARRAY_POINTER = GL_COLOR_ARRAY_POINTER,
    _ES1_GL_TEXTURE_COORD_ARRAY_POINTER = GL_TEXTURE_COORD_ARRAY_POINTER,
    _ES1_GL_SAMPLE_BUFFERS = GL_SAMPLE_BUFFERS,
    _ES1_GL_SAMPLES = GL_SAMPLES,
    _ES1_GL_SAMPLE_COVERAGE_VALUE = GL_SAMPLE_COVERAGE_VALUE,
    _ES1_GL_SAMPLE_COVERAGE_INVERT = GL_SAMPLE_COVERAGE_INVERT,
    
    /* GetTextureParameter */
    /*      GL_TEXTURE_MAG_FILTER */
    /*      GL_TEXTURE_MIN_FILTER */
    /*      GL_TEXTURE_WRAP_S */
    /*      GL_TEXTURE_WRAP_T */
    
    _ES1_GL_IMPLEMENTATION_COLOR_READ_TYPE_OES = GL_IMPLEMENTATION_COLOR_READ_TYPE_OES,
    _ES1_GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES = GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES,
    _ES1_GL_NUM_COMPRESSED_TEXTURE_FORMATS = GL_NUM_COMPRESSED_TEXTURE_FORMATS,
    _ES1_GL_COMPRESSED_TEXTURE_FORMATS = GL_COMPRESSED_TEXTURE_FORMATS,
    
    /* HintMode */
    _ES1_GL_DONT_CARE = GL_DONT_CARE,
    _ES1_GL_FASTEST = GL_FASTEST,
    _ES1_GL_NICEST = GL_NICEST,
    
    /* HintTarget */
    _ES1_GL_PERSPECTIVE_CORRECTION_HINT = GL_PERSPECTIVE_CORRECTION_HINT,
    _ES1_GL_POINT_SMOOTH_HINT = GL_POINT_SMOOTH_HINT,
    _ES1_GL_LINE_SMOOTH_HINT = GL_LINE_SMOOTH_HINT,
    _ES1_GL_FOG_HINT = GL_FOG_HINT,
    _ES1_GL_GENERATE_MIPMAP_HINT = GL_GENERATE_MIPMAP_HINT,
    
    /* LightModelParameter */
    _ES1_GL_LIGHT_MODEL_AMBIENT = GL_LIGHT_MODEL_AMBIENT,
    _ES1_GL_LIGHT_MODEL_TWO_SIDE = GL_LIGHT_MODEL_TWO_SIDE,
    
    /* LightParameter */
    _ES1_GL_AMBIENT = GL_AMBIENT,
    _ES1_GL_DIFFUSE = GL_DIFFUSE,
    _ES1_GL_SPECULAR = GL_SPECULAR,
    _ES1_GL_POSITION = GL_POSITION,
    _ES1_GL_SPOT_DIRECTION = GL_SPOT_DIRECTION,
    _ES1_GL_SPOT_EXPONENT = GL_SPOT_EXPONENT,
    _ES1_GL_SPOT_CUTOFF = GL_SPOT_CUTOFF,
    _ES1_GL_CONSTANT_ATTENUATION = GL_CONSTANT_ATTENUATION,
    _ES1_GL_LINEAR_ATTENUATION = GL_LINEAR_ATTENUATION,
    _ES1_GL_QUADRATIC_ATTENUATION = GL_QUADRATIC_ATTENUATION,
    
    /* DataType */
    _ES1_GL_BYTE = GL_BYTE,
    _ES1_GL_UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
    _ES1_GL_SHORT = GL_SHORT,
    _ES1_GL_UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
    _ES1_GL_FLOAT = GL_FLOAT,
    _ES1_GL_FIXED = GL_FIXED,
    
    /* LogicOp */
    _ES1_GL_CLEAR = GL_CLEAR,
    _ES1_GL_AND = GL_AND,
    _ES1_GL_AND_REVERSE = GL_AND_REVERSE,
    _ES1_GL_COPY = GL_COPY,
    _ES1_GL_AND_INVERTED = GL_AND_INVERTED,
    _ES1_GL_NOOP = GL_NOOP,
    _ES1_GL_XOR = GL_XOR,
    _ES1_GL_OR = GL_OR,
    _ES1_GL_NOR = GL_NOR,
    _ES1_GL_EQUIV = GL_EQUIV,
    _ES1_GL_INVERT = GL_INVERT,
    _ES1_GL_OR_REVERSE = GL_OR_REVERSE,
    _ES1_GL_COPY_INVERTED = GL_COPY_INVERTED,
    _ES1_GL_OR_INVERTED = GL_OR_INVERTED,
    _ES1_GL_NAND = GL_NAND,
    _ES1_GL_SET = GL_SET,
    
    /* MaterialFace */
    /*      GL_FRONT_AND_BACK */
    
    /* MaterialParameter */
    _ES1_GL_EMISSION = GL_EMISSION,
    _ES1_GL_SHININESS = GL_SHININESS,
    _ES1_GL_AMBIENT_AND_DIFFUSE = GL_AMBIENT_AND_DIFFUSE,
    /*      GL_AMBIENT */
    /*      GL_DIFFUSE */
    /*      GL_SPECULAR */
    
    /* MatrixMode */
    _ES1_GL_MODELVIEW = GL_MODELVIEW,
    _ES1_GL_PROJECTION = GL_PROJECTION,
    _ES1_GL_TEXTURE = GL_TEXTURE,
    
    /* NormalPointerType */
    /*      GL_BYTE */
    /*      GL_SHORT */
    /*      GL_FLOAT */
    /*      GL_FIXED */
    
    /* PixelFormat */
    _ES1_GL_ALPHA = GL_ALPHA,
    _ES1_GL_RGB = GL_RGB,
    _ES1_GL_RGBA = GL_RGBA,
    _ES1_GL_LUMINANCE = GL_LUMINANCE,
    _ES1_GL_LUMINANCE_ALPHA = GL_LUMINANCE_ALPHA,
    
    /* PixelStoreParameter */
    //_ES1_GL_UNPACK_ALIGNMENT = GL_UNPACK_ALIGNMENT,
    //_ES1_GL_PACK_ALIGNMENT = GL_PACK_ALIGNMENT,
    
    /* PixelType */
    /*      GL_UNSIGNED_BYTE */
    _ES1_GL_UNSIGNED_SHORT_4_4_4_4 = GL_UNSIGNED_SHORT_4_4_4_4,
    _ES1_GL_UNSIGNED_SHORT_5_5_5_1 = GL_UNSIGNED_SHORT_5_5_5_1,
    _ES1_GL_UNSIGNED_SHORT_5_6_5 = GL_UNSIGNED_SHORT_5_6_5,
    
    /* ShadingModel */
    _ES1_GL_FLAT = GL_FLAT,
    _ES1_GL_SMOOTH = GL_SMOOTH,
    
    /* StencilFunction */
    /*      GL_NEVER */
    /*      GL_LESS */
    /*      GL_EQUAL */
    /*      GL_LEQUAL */
    /*      GL_GREATER */
    /*      GL_NOTEQUAL */
    /*      GL_GEQUAL */
    /*      GL_ALWAYS */
    
    /* StencilOp */
    /*      GL_ZERO */
    _ES1_GL_KEEP = GL_KEEP,
    _ES1_GL_REPLACE = GL_REPLACE,
    _ES1_GL_INCR = GL_INCR,
    _ES1_GL_DECR = GL_DECR,
    /*      GL_INVERT */
    
    /* StringName */
    _ES1_GL_VENDOR = GL_VENDOR,
    _ES1_GL_RENDERER = GL_RENDERER,
    _ES1_GL_VERSION = GL_VERSION,
    _ES1_GL_EXTENSIONS = GL_EXTENSIONS,
    
    /* TexCoordPointerType */
    /*      GL_SHORT */
    /*      GL_FLOAT */
    /*      GL_FIXED */
    /*      GL_BYTE */
    
    /* TextureEnvMode */
    _ES1_GL_MODULATE = GL_MODULATE,
    _ES1_GL_DECAL = GL_DECAL,
    /*      GL_BLEND */
    _ES1_GL_ADD = GL_ADD,
    /*      GL_REPLACE */
    
    /* TextureEnvParameter */
    _ES1_GL_TEXTURE_ENV_MODE = GL_TEXTURE_ENV_MODE,
    _ES1_GL_TEXTURE_ENV_COLOR = GL_TEXTURE_ENV_COLOR,
    
    /* TextureEnvTarget */
    _ES1_GL_TEXTURE_ENV = GL_TEXTURE_ENV,
    
    /* TextureMagFilter */
    _ES1_GL_NEAREST = GL_NEAREST,
    _ES1_GL_LINEAR = GL_LINEAR,
    
    /* TextureMinFilter */
    /*      GL_NEAREST */
    /*      GL_LINEAR */
    _ES1_GL_NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
    _ES1_GL_LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
    _ES1_GL_NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
    _ES1_GL_LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
    
    /* TextureParameterName */
    _ES1_GL_TEXTURE_MAG_FILTER = GL_TEXTURE_MAG_FILTER,
    _ES1_GL_TEXTURE_MIN_FILTER = GL_TEXTURE_MIN_FILTER,
    _ES1_GL_TEXTURE_WRAP_S = GL_TEXTURE_WRAP_S,
    _ES1_GL_TEXTURE_WRAP_T = GL_TEXTURE_WRAP_T,
    _ES1_GL_GENERATE_MIPMAP = GL_GENERATE_MIPMAP,
    
    /* TextureTarget */
    /*      GL_TEXTURE_2D */
    
    /* TextureUnit */
    _ES1_GL_TEXTURE0 = GL_TEXTURE0,
    _ES1_GL_TEXTURE1 = GL_TEXTURE1,
    _ES1_GL_TEXTURE2 = GL_TEXTURE2,
    _ES1_GL_TEXTURE3 = GL_TEXTURE3,
    _ES1_GL_TEXTURE4 = GL_TEXTURE4,
    _ES1_GL_TEXTURE5 = GL_TEXTURE5,
    _ES1_GL_TEXTURE6 = GL_TEXTURE6,
    _ES1_GL_TEXTURE7 = GL_TEXTURE7,
    _ES1_GL_TEXTURE8 = GL_TEXTURE8,
    _ES1_GL_TEXTURE9 = GL_TEXTURE9,
    _ES1_GL_TEXTURE10 = GL_TEXTURE10,
    _ES1_GL_TEXTURE11 = GL_TEXTURE11,
    _ES1_GL_TEXTURE12 = GL_TEXTURE12,
    _ES1_GL_TEXTURE13 = GL_TEXTURE13,
    _ES1_GL_TEXTURE14 = GL_TEXTURE14,
    _ES1_GL_TEXTURE15 = GL_TEXTURE15,
    _ES1_GL_TEXTURE16 = GL_TEXTURE16,
    _ES1_GL_TEXTURE17 = GL_TEXTURE17,
    _ES1_GL_TEXTURE18 = GL_TEXTURE18,
    _ES1_GL_TEXTURE19 = GL_TEXTURE19,
    _ES1_GL_TEXTURE20 = GL_TEXTURE20,
    _ES1_GL_TEXTURE21 = GL_TEXTURE21,
    _ES1_GL_TEXTURE22 = GL_TEXTURE22,
    _ES1_GL_TEXTURE23 = GL_TEXTURE23,
    _ES1_GL_TEXTURE24 = GL_TEXTURE24,
    _ES1_GL_TEXTURE25 = GL_TEXTURE25,
    _ES1_GL_TEXTURE26 = GL_TEXTURE26,
    _ES1_GL_TEXTURE27 = GL_TEXTURE27,
    _ES1_GL_TEXTURE28 = GL_TEXTURE28,
    _ES1_GL_TEXTURE29 = GL_TEXTURE29,
    _ES1_GL_TEXTURE30 = GL_TEXTURE30,
    _ES1_GL_TEXTURE31 = GL_TEXTURE31,
    _ES1_GL_ACTIVE_TEXTURE = GL_ACTIVE_TEXTURE,
    _ES1_GL_CLIENT_ACTIVE_TEXTURE = GL_CLIENT_ACTIVE_TEXTURE,
    
    /* TextureWrapMode */
    _ES1_GL_REPEAT = GL_REPEAT,
    _ES1_GL_CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
    
    /* PixelInternalFormat */
    _ES1_GL_PALETTE4_RGB8_OES = GL_PALETTE4_RGB8_OES,
    _ES1_GL_PALETTE4_RGBA8_OES = GL_PALETTE4_RGBA8_OES,
    _ES1_GL_PALETTE4_R5_G6_B5_OES = GL_PALETTE4_R5_G6_B5_OES,
    _ES1_GL_PALETTE4_RGBA4_OES = GL_PALETTE4_RGBA4_OES,
    _ES1_GL_PALETTE4_RGB5_A1_OES = GL_PALETTE4_RGB5_A1_OES,
    _ES1_GL_PALETTE8_RGB8_OES = GL_PALETTE8_RGB8_OES,
    _ES1_GL_PALETTE8_RGBA8_OES = GL_PALETTE8_RGBA8_OES,
    _ES1_GL_PALETTE8_R5_G6_B5_OES = GL_PALETTE8_R5_G6_B5_OES,
    _ES1_GL_PALETTE8_RGBA4_OES = GL_PALETTE8_RGBA4_OES,
    _ES1_GL_PALETTE8_RGB5_A1_OES = GL_PALETTE8_RGB5_A1_OES,
    
    /* VertexPointerType */
    /*      GL_SHORT */
    /*      GL_FLOAT */
    /*      GL_FIXED */
    /*      GL_BYTE */
    
    /* LightName */
    _ES1_GL_LIGHT0 = GL_LIGHT0,
    _ES1_GL_LIGHT1 = GL_LIGHT1,
    _ES1_GL_LIGHT2 = GL_LIGHT2,
    _ES1_GL_LIGHT3 = GL_LIGHT3,
    _ES1_GL_LIGHT4 = GL_LIGHT4,
    _ES1_GL_LIGHT5 = GL_LIGHT5,
    _ES1_GL_LIGHT6 = GL_LIGHT6,
    _ES1_GL_LIGHT7 = GL_LIGHT7,
    
    /* Buffer Objects */
    _ES1_GL_ARRAY_BUFFER = GL_ARRAY_BUFFER,
    _ES1_GL_ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER,
    
    _ES1_GL_ARRAY_BUFFER_BINDING = GL_ARRAY_BUFFER_BINDING,
    _ES1_GL_ELEMENT_ARRAY_BUFFER_BINDING = GL_ELEMENT_ARRAY_BUFFER_BINDING,
    _ES1_GL_VERTEX_ARRAY_BUFFER_BINDING = GL_VERTEX_ARRAY_BUFFER_BINDING,
    _ES1_GL_NORMAL_ARRAY_BUFFER_BINDING = GL_NORMAL_ARRAY_BUFFER_BINDING,
    _ES1_GL_COLOR_ARRAY_BUFFER_BINDING = GL_COLOR_ARRAY_BUFFER_BINDING,
    _ES1_GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING,
    
    _ES1_GL_STATIC_DRAW = GL_STATIC_DRAW,
    _ES1_GL_DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
    
    _ES1_GL_BUFFER_SIZE = GL_BUFFER_SIZE,
    _ES1_GL_BUFFER_USAGE = GL_BUFFER_USAGE,
    
    /* Texture combine + dot3 */
    _ES1_GL_SUBTRACT = GL_SUBTRACT,
    _ES1_GL_COMBINE = GL_COMBINE,
    _ES1_GL_COMBINE_RGB = GL_COMBINE_RGB,
    _ES1_GL_COMBINE_ALPHA = GL_COMBINE_ALPHA,
    _ES1_GL_RGB_SCALE = GL_RGB_SCALE,
    _ES1_GL_ADD_SIGNED = GL_ADD_SIGNED,
    _ES1_GL_INTERPOLATE = GL_INTERPOLATE,
    _ES1_GL_CONSTANT = GL_CONSTANT,
    _ES1_GL_PRIMARY_COLOR = GL_PRIMARY_COLOR,
    _ES1_GL_PREVIOUS = GL_PREVIOUS,
    _ES1_GL_OPERAND0_RGB = GL_OPERAND0_RGB,
    _ES1_GL_OPERAND1_RGB = GL_OPERAND1_RGB,
    _ES1_GL_OPERAND2_RGB = GL_OPERAND2_RGB,
    _ES1_GL_OPERAND0_ALPHA = GL_OPERAND0_ALPHA,
    _ES1_GL_OPERAND1_ALPHA = GL_OPERAND1_ALPHA,
    _ES1_GL_OPERAND2_ALPHA = GL_OPERAND2_ALPHA,
    
    _ES1_GL_ALPHA_SCALE = GL_ALPHA_SCALE,
    
    _ES1_GL_SRC0_RGB = GL_SRC0_RGB,
    _ES1_GL_SRC1_RGB = GL_SRC1_RGB,
    _ES1_GL_SRC2_RGB = GL_SRC2_RGB,
    _ES1_GL_SRC0_ALPHA = GL_SRC0_ALPHA,
    _ES1_GL_SRC1_ALPHA = GL_SRC1_ALPHA,
    _ES1_GL_SRC2_ALPHA = GL_SRC2_ALPHA,
    
    _ES1_GL_DOT3_RGB = GL_DOT3_RGB,
    _ES1_GL_DOT3_RGBA = GL_DOT3_RGBA,
    
    /*****************************************************************************************/
    /*                                 OES extension functions                               */
    /*****************************************************************************************/
    
    /* OES_draw_texture */
    _ES1_GL_TEXTURE_CROP_RECT_OES = GL_TEXTURE_CROP_RECT_OES,
    
    /* OES_matrix_get */
    _ES1_GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES = GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES,
    _ES1_GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES = GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES,
    _ES1_GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES = GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES,
    
    /* OES_matrix_palette */
    _ES1_GL_MAX_VERTEX_UNITS_OES = GL_MAX_VERTEX_UNITS_OES,
    _ES1_GL_MAX_PALETTE_MATRICES_OES = GL_MAX_PALETTE_MATRICES_OES,
    _ES1_GL_MATRIX_PALETTE_OES = GL_MATRIX_PALETTE_OES,
    _ES1_GL_MATRIX_INDEX_ARRAY_OES = GL_MATRIX_INDEX_ARRAY_OES,
    _ES1_GL_WEIGHT_ARRAY_OES = GL_WEIGHT_ARRAY_OES,
    _ES1_GL_CURRENT_PALETTE_MATRIX_OES = GL_CURRENT_PALETTE_MATRIX_OES,
    
    _ES1_GL_MATRIX_INDEX_ARRAY_SIZE_OES = GL_MATRIX_INDEX_ARRAY_SIZE_OES,
    _ES1_GL_MATRIX_INDEX_ARRAY_TYPE_OES = GL_MATRIX_INDEX_ARRAY_TYPE_OES,
    _ES1_GL_MATRIX_INDEX_ARRAY_STRIDE_OES = GL_MATRIX_INDEX_ARRAY_STRIDE_OES,
    _ES1_GL_MATRIX_INDEX_ARRAY_POINTER_OES = GL_MATRIX_INDEX_ARRAY_POINTER_OES,
    _ES1_GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES = GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES,
    
    _ES1_GL_WEIGHT_ARRAY_SIZE_OES = GL_WEIGHT_ARRAY_SIZE_OES,
    _ES1_GL_WEIGHT_ARRAY_TYPE_OES = GL_WEIGHT_ARRAY_TYPE_OES,
    _ES1_GL_WEIGHT_ARRAY_STRIDE_OES = GL_WEIGHT_ARRAY_STRIDE_OES,
    _ES1_GL_WEIGHT_ARRAY_POINTER_OES = GL_WEIGHT_ARRAY_POINTER_OES,
    _ES1_GL_WEIGHT_ARRAY_BUFFER_BINDING_OES = GL_WEIGHT_ARRAY_BUFFER_BINDING_OES,
    
    /* OES_point_size_array */
    _ES1_GL_POINT_SIZE_ARRAY_OES = GL_POINT_SIZE_ARRAY_OES,
    _ES1_GL_POINT_SIZE_ARRAY_TYPE_OES = GL_POINT_SIZE_ARRAY_TYPE_OES,
    _ES1_GL_POINT_SIZE_ARRAY_STRIDE_OES = GL_POINT_SIZE_ARRAY_STRIDE_OES,
    _ES1_GL_POINT_SIZE_ARRAY_POINTER_OES = GL_POINT_SIZE_ARRAY_POINTER_OES,
    _ES1_GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES = GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES,
    
    /* OES_point_sprite */
    _ES1_GL_POINT_SPRITE_OES = GL_POINT_SPRITE_OES,
    _ES1_GL_COORD_REPLACE_OES = GL_COORD_REPLACE_OES,
    
    /*************************************************************/
    /*                          glext.h                          */
    /*************************************************************/
    
    _ES1_GL_APPLE_copy_texture_levels = GL_APPLE_copy_texture_levels,
    _ES1_GL_APPLE_framebuffer_multisample = GL_APPLE_framebuffer_multisample,
    _ES1_GL_APPLE_texture_2D_limited_npot = GL_APPLE_texture_2D_limited_npot,
    _ES1_GL_APPLE_texture_format_BGRA8888 = GL_APPLE_texture_format_BGRA8888,
    _ES1_GL_APPLE_texture_max_level = GL_APPLE_texture_max_level,
    _ES1_GL_EXT_blend_minmax = GL_EXT_blend_minmax,
    _ES1_GL_EXT_debug_label = GL_EXT_debug_label,
    _ES1_GL_EXT_debug_marker = GL_EXT_debug_marker,
    _ES1_GL_EXT_discard_framebuffer = GL_EXT_discard_framebuffer,
    _ES1_GL_EXT_map_buffer_range = GL_EXT_map_buffer_range,
    _ES1_GL_EXT_read_format_bgra = GL_EXT_read_format_bgra,
    _ES1_GL_EXT_texture_filter_anisotropic = GL_EXT_texture_filter_anisotropic,
    _ES1_GL_EXT_texture_lod_bias = GL_EXT_texture_lod_bias,
    _ES1_GL_EXT_texture_storage = GL_EXT_texture_storage,
    _ES1_GL_IMG_read_format = GL_IMG_read_format,
    _ES1_GL_IMG_texture_compression_pvrtc = GL_IMG_texture_compression_pvrtc,
    _ES1_GL_OES_blend_equation_separate = GL_OES_blend_equation_separate,
    _ES1_GL_OES_blend_func_separate = GL_OES_blend_func_separate,
    _ES1_GL_OES_blend_subtract = GL_OES_blend_subtract,
    _ES1_GL_OES_depth24 = GL_OES_depth24,
    _ES1_GL_OES_element_index_uint = GL_OES_element_index_uint,
    _ES1_GL_OES_fbo_render_mipmap = GL_OES_fbo_render_mipmap,
    _ES1_GL_OES_framebuffer_object = GL_OES_framebuffer_object,
    _ES1_GL_OES_mapbuffer = GL_OES_mapbuffer,
    _ES1_GL_OES_packed_depth_stencil = GL_OES_packed_depth_stencil,
    _ES1_GL_OES_rgb8_rgba8 = GL_OES_rgb8_rgba8,
    _ES1_GL_OES_stencil_wrap = GL_OES_stencil_wrap,
    _ES1_GL_OES_stencil8 = GL_OES_stencil8,
    _ES1_GL_OES_texture_mirrored_repeat = GL_OES_texture_mirrored_repeat,
    _ES1_GL_OES_vertex_array_object = GL_OES_vertex_array_object,
    
    
    /*------------------------------------------------------------------------*
     * APPLE extension tokens
     *------------------------------------------------------------------------*/
#if GL_APPLE_framebuffer_multisample
    _ES1_GL_RENDERBUFFER_SAMPLES_APPLE = GL_RENDERBUFFER_SAMPLES_APPLE,
    _ES1_GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE = GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE,
    _ES1_GL_MAX_SAMPLES_APPLE = GL_MAX_SAMPLES_APPLE,
    _ES1_GL_READ_FRAMEBUFFER_APPLE = GL_READ_FRAMEBUFFER_APPLE,
    _ES1_GL_DRAW_FRAMEBUFFER_APPLE = GL_DRAW_FRAMEBUFFER_APPLE,
    _ES1_GL_DRAW_FRAMEBUFFER_BINDING_APPLE = GL_DRAW_FRAMEBUFFER_BINDING_APPLE,
    _ES1_GL_READ_FRAMEBUFFER_BINDING_APPLE = GL_READ_FRAMEBUFFER_BINDING_APPLE,
#endif
    
#if GL_APPLE_texture_format_BGRA8888
    _ES1_GL_BGRA_EXT = GL_BGRA_EXT,
#endif
    
#if GL_APPLE_texture_format_BGRA8888 || GL_IMG_read_format
    _ES1_GL_BGRA = GL_BGRA,
#endif
    
#if GL_APPLE_texture_max_level
    _ES1_GL_TEXTURE_MAX_LEVEL_APPLE = GL_TEXTURE_MAX_LEVEL_APPLE,
#endif
    
    /*------------------------------------------------------------------------*
     * EXT extension tokens
     *------------------------------------------------------------------------*/
#if GL_EXT_blend_minmax
    _ES1_GL_MIN_EXT = GL_MIN_EXT,
    _ES1_GL_MAX_EXT = GL_MAX_EXT,
#endif
    
#if GL_EXT_debug_label
    _ES1_GL_BUFFER_OBJECT_EXT = GL_BUFFER_OBJECT_EXT,
    _ES1_GL_VERTEX_ARRAY_OBJECT_EXT = GL_VERTEX_ARRAY_OBJECT_EXT,
#endif
    
#if GL_EXT_discard_framebuffer
    _ES1_GL_COLOR_EXT = GL_COLOR_EXT,
    _ES1_GL_DEPTH_EXT = GL_DEPTH_EXT,
    _ES1_GL_STENCIL_EXT = GL_STENCIL_EXT,
#endif
    
#if GL_EXT_map_buffer_range
    _ES1_GL_MAP_READ_BIT_EXT = GL_MAP_READ_BIT_EXT,
    _ES1_GL_MAP_WRITE_BIT_EXT = GL_MAP_WRITE_BIT_EXT,
    _ES1_GL_MAP_INVALIDATE_RANGE_BIT_EXT = GL_MAP_INVALIDATE_RANGE_BIT_EXT,
    _ES1_GL_MAP_INVALIDATE_BUFFER_BIT_EXT = GL_MAP_INVALIDATE_BUFFER_BIT_EXT,
    _ES1_GL_MAP_FLUSH_EXPLICIT_BIT_EXT = GL_MAP_FLUSH_EXPLICIT_BIT_EXT,
    _ES1_GL_MAP_UNSYNCHRONIZED_BIT_EXT = GL_MAP_UNSYNCHRONIZED_BIT_EXT,
#endif
    
#if GL_EXT_read_format_bgra
    _ES1_GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT = GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT,
    _ES1_GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT = GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT,
    _ES1_GL_UNSIGNED_SHORT_1_5_5_5_REV = GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT,
#endif
    
#if GL_EXT_read_format_bgra || GL_IMG_read_format
    _ES1_GL_UNSIGNED_SHORT_4_4_4_4_REV = GL_UNSIGNED_SHORT_4_4_4_4_REV,
#endif
    
#if GL_EXT_texture_filter_anisotropic
    _ES1_GL_TEXTURE_MAX_ANISOTROPY_EXT = GL_TEXTURE_MAX_ANISOTROPY_EXT,
    _ES1_GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT,
#endif
    
#if GL_EXT_texture_lod_bias
    _ES1_GL_MAX_TEXTURE_LOD_BIAS_EXT = GL_MAX_TEXTURE_LOD_BIAS_EXT,
    _ES1_GL_TEXTURE_FILTER_CONTROL_EXT = GL_TEXTURE_FILTER_CONTROL_EXT,
    _ES1_GL_TEXTURE_LOD_BIAS_EXT = GL_TEXTURE_LOD_BIAS_EXT,
#endif
    
#if GL_EXT_texture_storage
    _ES1_GL_TEXTURE_IMMUTABLE_FORMAT_EXT = GL_TEXTURE_IMMUTABLE_FORMAT_EXT,
    _ES1_GL_ALPHA8_EXT = GL_ALPHA8_EXT,
    _ES1_GL_LUMINANCE8_EXT = GL_LUMINANCE8_EXT,
    _ES1_GL_LUMINANCE8_ALPHA8_EXT = GL_LUMINANCE8_ALPHA8_EXT,
    _ES1_GL_BGRA8_EXT = GL_BGRA8_EXT,
#endif
    
    /*------------------------------------------------------------------------*
     * IMG extension tokens
     *------------------------------------------------------------------------*/
#if GL_IMG_read_format
    _ES1_GL_BGRA_IMG = GL_BGRA_IMG,
    _ES1_GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG = GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG,
#endif
    
#if GL_IMG_texture_compression_pvrtc
    _ES1_GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG = GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
    _ES1_GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG = GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
    _ES1_GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG = GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
    _ES1_GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG = GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
#endif
    
    /*------------------------------------------------------------------------*
     * OES extension tokens
     *------------------------------------------------------------------------*/
#if GL_OES_blend_equation_separate
    _ES1_GL_BLEND_EQUATION_RGB_OES = GL_BLEND_EQUATION_RGB_OES,
    _ES1_GL_BLEND_EQUATION_ALPHA_OES = GL_BLEND_EQUATION_ALPHA_OES,
#endif
    
#if GL_OES_blend_func_separate
    _ES1_GL_BLEND_DST_RGB_OES = GL_BLEND_DST_RGB_OES,
    _ES1_GL_BLEND_SRC_RGB_OES = GL_BLEND_SRC_RGB_OES,
    _ES1_GL_BLEND_DST_ALPHA_OES = GL_BLEND_DST_ALPHA_OES,
    _ES1_GL_BLEND_SRC_ALPHA_OES = GL_BLEND_SRC_ALPHA_OES,
#endif
    
#if GL_OES_blend_subtract
    _ES1_GL_BLEND_EQUATION_OES = GL_BLEND_EQUATION_OES,
    _ES1_GL_FUNC_ADD_OES = GL_FUNC_ADD_OES,
    _ES1_GL_FUNC_SUBTRACT_OES = GL_FUNC_SUBTRACT_OES,
    _ES1_GL_FUNC_REVERSE_SUBTRACT_OES = GL_FUNC_REVERSE_SUBTRACT_OES,
#endif
    
#if GL_OES_depth24
    _ES1_GL_DEPTH_COMPONENT24_OES = GL_DEPTH_COMPONENT24_OES,
#endif
    
#if GL_OES_element_index_uint
    _ES1_GL_UNSIGNED_INT_OES = GL_UNSIGNED_INT_OES,
#endif
    
#if GL_OES_framebuffer_object
    _ES1_GL_FRAMEBUFFER_OES = GL_FRAMEBUFFER_OES,
    _ES1_GL_RENDERBUFFER_OES = GL_RENDERBUFFER_OES,
    _ES1_GL_RGBA4_OES = GL_RGBA4_OES,
    _ES1_GL_RGB5_A1_OES = GL_RGB5_A1_OES,
    _ES1_GL_RGB565_OES = GL_RGB565_OES,
    _ES1_GL_DEPTH_COMPONENT16_OES = GL_DEPTH_COMPONENT16_OES,
    _ES1_GL_RENDERBUFFER_WIDTH_OES = GL_RENDERBUFFER_WIDTH_OES,
    _ES1_GL_RENDERBUFFER_HEIGHT_OES = GL_RENDERBUFFER_HEIGHT_OES,
    _ES1_GL_RENDERBUFFER_INTERNAL_FORMAT_OES = GL_RENDERBUFFER_INTERNAL_FORMAT_OES,
    _ES1_GL_RENDERBUFFER_RED_SIZE_OES = GL_RENDERBUFFER_RED_SIZE_OES,
    _ES1_GL_RENDERBUFFER_GREEN_SIZE_OES = GL_RENDERBUFFER_GREEN_SIZE_OES,
    _ES1_GL_RENDERBUFFER_BLUE_SIZE_OES = GL_RENDERBUFFER_BLUE_SIZE_OES,
    _ES1_GL_RENDERBUFFER_ALPHA_SIZE_OES = GL_RENDERBUFFER_ALPHA_SIZE_OES,
    _ES1_GL_RENDERBUFFER_DEPTH_SIZE_OES = GL_RENDERBUFFER_DEPTH_SIZE_OES,
    _ES1_GL_RENDERBUFFER_STENCIL_SIZE_OES = GL_RENDERBUFFER_STENCIL_SIZE_OES,
    _ES1_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES = GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES,
    _ES1_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES = GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES,
    _ES1_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES,
    _ES1_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES,
    _ES1_GL_COLOR_ATTACHMENT0_OES = GL_COLOR_ATTACHMENT0_OES,
    _ES1_GL_DEPTH_ATTACHMENT_OES = GL_DEPTH_ATTACHMENT_OES,
    _ES1_GL_STENCIL_ATTACHMENT_OES = GL_STENCIL_ATTACHMENT_OES,
    _ES1_GL_FRAMEBUFFER_COMPLETE_OES = GL_FRAMEBUFFER_COMPLETE_OES,
    _ES1_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES = GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES,
    _ES1_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES = GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES,
    _ES1_GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES = GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES,
    _ES1_GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES = GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES,
    _ES1_GL_FRAMEBUFFER_UNSUPPORTED_OES = GL_FRAMEBUFFER_UNSUPPORTED_OES,
    _ES1_GL_FRAMEBUFFER_BINDING_OES = GL_FRAMEBUFFER_BINDING_OES,
    _ES1_GL_RENDERBUFFER_BINDING_OES = GL_RENDERBUFFER_BINDING_OES,
    _ES1_GL_MAX_RENDERBUFFER_SIZE_OES = GL_MAX_RENDERBUFFER_SIZE_OES,
    _ES1_GL_INVALID_FRAMEBUFFER_OPERATION_OES = GL_INVALID_FRAMEBUFFER_OPERATION_OES,
#endif
    
#if GL_OES_mapbuffer
    _ES1_GL_WRITE_ONLY_OES = GL_WRITE_ONLY_OES,
    _ES1_GL_BUFFER_ACCESS_OES = GL_BUFFER_ACCESS_OES,
    _ES1_GL_BUFFER_MAPPED_OES = GL_BUFFER_MAPPED_OES,
    _ES1_GL_BUFFER_MAP_POINTER_OES = GL_BUFFER_MAP_POINTER_OES,
#endif
    
#if GL_OES_packed_depth_stencil
    _ES1_GL_DEPTH_STENCIL_OES = GL_DEPTH_STENCIL_OES,
    _ES1_GL_UNSIGNED_INT_24_8_OES = GL_UNSIGNED_INT_24_8_OES,
    _ES1_GL_DEPTH24_STENCIL8_OES = GL_DEPTH24_STENCIL8_OES,
#endif
    
#if GL_OES_rgb8_rgba8
    _ES1_GL_RGB8_OES = GL_RGB8_OES,
    _ES1_GL_RGBA8_OES = GL_RGBA8_OES,
#endif
    
#if GL_OES_stencil_wrap
    _ES1_GL_INCR_WRAP_OES = GL_INCR_WRAP_OES,
    _ES1_GL_DECR_WRAP_OES = GL_DECR_WRAP_OES,
#endif
    
#if GL_OES_stencil8
    _ES1_GL_STENCIL_INDEX8_OES = GL_STENCIL_INDEX8_OES,
#endif
    
#if GL_OES_texture_mirrored_repeat
    _ES1_GL_MIRRORED_REPEAT_OES = GL_MIRRORED_REPEAT_OES,
#endif
    
#if GL_OES_vertex_array_object
    _ES1_GL_VERTEX_ARRAY_BINDING_OES = GL_VERTEX_ARRAY_BINDING_OES,
#endif
    
    /**************************************************************************/
};

typedef enum _ES1_ ES1;

#endif /* __OpenGLES_ES1_Defines_H */
