//
//  OpenGLES_ES3_Defines.h
//

#ifndef __OpenGLES_ES3_Defines_H
#define __OpenGLES_ES3_Defines_H

#include <OpenGLES/ES3/gl.h>
#include <OpenGLES/ES3/glext.h>

enum _ES3_ {
    
    /*************************************************************/
    /*                            gl.h                           */
    /*************************************************************/
    
    /* OpenGL ES core versions */
    _ES3_GL_ES_VERSION_3_0 = GL_ES_VERSION_3_0,
    _ES3_GL_ES_VERSION_2_0 = GL_ES_VERSION_2_0,
    
    /* OpenGL ES 2.0 */
    
    /* ClearBufferMask */
    _ES3_GL_DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT,
    _ES3_GL_STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT,
    _ES3_GL_COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT,
    
    /* Boolean */
    _ES3_GL_FALSE = GL_FALSE,
    _ES3_GL_TRUE = GL_TRUE,
    
    /* BeginMode */
    _ES3_GL_POINTS = GL_POINTS,
    _ES3_GL_LINES = GL_LINES,
    _ES3_GL_LINE_LOOP = GL_LINE_LOOP,
    _ES3_GL_LINE_STRIP = GL_LINE_STRIP,
    _ES3_GL_TRIANGLES = GL_TRIANGLES,
    _ES3_GL_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
    _ES3_GL_TRIANGLE_FAN = GL_TRIANGLE_FAN,
    
    /* BlendingFactorDest */
    _ES3_GL_ZERO = GL_ZERO,
    _ES3_GL_ONE = GL_ONE,
    _ES3_GL_SRC_COLOR = GL_SRC_COLOR,
    _ES3_GL_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR,
    _ES3_GL_SRC_ALPHA = GL_SRC_ALPHA,
    _ES3_GL_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
    _ES3_GL_DST_ALPHA = GL_DST_ALPHA,
    _ES3_GL_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
    
    /* BlendingFactorSrc */
    /*      GL_ZERO */
    /*      GL_ONE */
    _ES3_GL_DST_COLOR = GL_DST_COLOR,
    _ES3_GL_ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR,
    _ES3_GL_SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE,
    /*      GL_SRC_ALPHA */
    /*      GL_ONE_MINUS_SRC_ALPHA */
    /*      GL_DST_ALPHA */
    /*      GL_ONE_MINUS_DST_ALPHA */
    
    /* BlendEquationSeparate */
    _ES3_GL_FUNC_ADD = GL_FUNC_ADD,
    _ES3_GL_BLEND_EQUATION = GL_BLEND_EQUATION,
    _ES3_GL_BLEND_EQUATION_RGB = GL_BLEND_EQUATION_RGB,    /* same as BLEND_EQUATION */
    _ES3_GL_BLEND_EQUATION_ALPHA = GL_BLEND_EQUATION_ALPHA,
    
    /* BlendSubtract */
    _ES3_GL_FUNC_SUBTRACT = GL_FUNC_SUBTRACT,
    _ES3_GL_FUNC_REVERSE_SUBTRACT = GL_FUNC_REVERSE_SUBTRACT,
    
    /* Separate Blend Functions */
    _ES3_GL_BLEND_DST_RGB = GL_BLEND_DST_RGB,
    _ES3_GL_BLEND_SRC_RGB = GL_BLEND_SRC_RGB,
    _ES3_GL_BLEND_DST_ALPHA = GL_BLEND_DST_ALPHA,
    _ES3_GL_BLEND_SRC_ALPHA = GL_BLEND_SRC_ALPHA,
    _ES3_GL_CONSTANT_COLOR = GL_CONSTANT_COLOR,
    _ES3_GL_ONE_MINUS_CONSTANT_COLOR = GL_ONE_MINUS_CONSTANT_COLOR,
    _ES3_GL_CONSTANT_ALPHA = GL_CONSTANT_ALPHA,
    _ES3_GL_ONE_MINUS_CONSTANT_ALPHA = GL_ONE_MINUS_CONSTANT_ALPHA,
    _ES3_GL_BLEND_COLOR = GL_BLEND_COLOR,
    
    /* Buffer Objects */
    _ES3_GL_ARRAY_BUFFER = GL_ARRAY_BUFFER,
    _ES3_GL_ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER,
    _ES3_GL_ARRAY_BUFFER_BINDING = GL_ARRAY_BUFFER_BINDING,
    _ES3_GL_ELEMENT_ARRAY_BUFFER_BINDING = GL_ELEMENT_ARRAY_BUFFER_BINDING,
    
    _ES3_GL_STREAM_DRAW = GL_STREAM_DRAW,
    _ES3_GL_STATIC_DRAW = GL_STATIC_DRAW,
    _ES3_GL_DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
    
    _ES3_GL_BUFFER_SIZE = GL_BUFFER_SIZE,
    _ES3_GL_BUFFER_USAGE = GL_BUFFER_USAGE,
    
    _ES3_GL_CURRENT_VERTEX_ATTRIB = GL_CURRENT_VERTEX_ATTRIB,
    
    /* CullFaceMode */
    _ES3_GL_FRONT = GL_FRONT,
    _ES3_GL_BACK = GL_BACK,
    _ES3_GL_FRONT_AND_BACK = GL_FRONT_AND_BACK,
    
    /* DepthFunction */
    /*      GL_NEVER */
    /*      GL_LESS */
    /*      GL_EQUAL */
    /*      GL_LEQUAL */
    /*      GL_GREATER */
    /*      GL_NOTEQUAL */
    /*      GL_GEQUAL */
    /*      GL_ALWAYS */
    
    /* EnableCap */
    _ES3_GL_TEXTURE_2D = GL_TEXTURE_2D,
    _ES3_GL_CULL_FACE = GL_CULL_FACE,
    _ES3_GL_BLEND = GL_BLEND,
    _ES3_GL_DITHER = GL_DITHER,
    _ES3_GL_STENCIL_TEST = GL_STENCIL_TEST,
    _ES3_GL_DEPTH_TEST = GL_DEPTH_TEST,
    _ES3_GL_SCISSOR_TEST = GL_SCISSOR_TEST,
    _ES3_GL_POLYGON_OFFSET_FILL = GL_POLYGON_OFFSET_FILL,
    _ES3_GL_SAMPLE_ALPHA_TO_COVERAGE = GL_SAMPLE_ALPHA_TO_COVERAGE,
    _ES3_GL_SAMPLE_COVERAGE = GL_SAMPLE_COVERAGE,
    
    /* ErrorCode */
    _ES3_GL_NO_ERROR = GL_NO_ERROR,
    _ES3_GL_INVALID_ENUM = GL_INVALID_ENUM,
    _ES3_GL_INVALID_VALUE = GL_INVALID_VALUE,
    _ES3_GL_INVALID_OPERATION = GL_INVALID_OPERATION,
    _ES3_GL_OUT_OF_MEMORY = GL_OUT_OF_MEMORY,
    
    /* FrontFaceDirection */
    _ES3_GL_CW = GL_CW,
    _ES3_GL_CCW = GL_CCW,
    
    /* GetPName */
    _ES3_GL_LINE_WIDTH = GL_LINE_WIDTH,
    _ES3_GL_ALIASED_POINT_SIZE_RANGE = GL_ALIASED_POINT_SIZE_RANGE,
    _ES3_GL_ALIASED_LINE_WIDTH_RANGE = GL_ALIASED_LINE_WIDTH_RANGE,
    _ES3_GL_CULL_FACE_MODE = GL_CULL_FACE_MODE,
    _ES3_GL_FRONT_FACE = GL_FRONT_FACE,
    _ES3_GL_DEPTH_RANGE = GL_DEPTH_RANGE,
    _ES3_GL_DEPTH_WRITEMASK = GL_DEPTH_WRITEMASK,
    _ES3_GL_DEPTH_CLEAR_VALUE = GL_DEPTH_CLEAR_VALUE,
    _ES3_GL_DEPTH_FUNC = GL_DEPTH_FUNC,
    _ES3_GL_STENCIL_CLEAR_VALUE = GL_STENCIL_CLEAR_VALUE,
    _ES3_GL_STENCIL_FUNC = GL_STENCIL_FUNC,
    _ES3_GL_STENCIL_FAIL = GL_STENCIL_FAIL,
    _ES3_GL_STENCIL_PASS_DEPTH_FAIL = GL_STENCIL_PASS_DEPTH_FAIL,
    _ES3_GL_STENCIL_PASS_DEPTH_PASS = GL_STENCIL_PASS_DEPTH_PASS,
    _ES3_GL_STENCIL_REF = GL_STENCIL_REF,
    _ES3_GL_STENCIL_VALUE_MASK = GL_STENCIL_VALUE_MASK,
    _ES3_GL_STENCIL_WRITEMASK = GL_STENCIL_WRITEMASK,
    _ES3_GL_STENCIL_BACK_FUNC = GL_STENCIL_BACK_FUNC,
    _ES3_GL_STENCIL_BACK_FAIL = GL_STENCIL_BACK_FAIL,
    _ES3_GL_STENCIL_BACK_PASS_DEPTH_FAIL = GL_STENCIL_BACK_PASS_DEPTH_FAIL,
    _ES3_GL_STENCIL_BACK_PASS_DEPTH_PASS = GL_STENCIL_BACK_PASS_DEPTH_PASS,
    _ES3_GL_STENCIL_BACK_REF = GL_STENCIL_BACK_REF,
    _ES3_GL_STENCIL_BACK_VALUE_MASK = GL_STENCIL_BACK_VALUE_MASK,
    _ES3_GL_STENCIL_BACK_WRITEMASK = GL_STENCIL_BACK_WRITEMASK,
    _ES3_GL_VIEWPORT = GL_VIEWPORT,
    _ES3_GL_SCISSOR_BOX = GL_SCISSOR_BOX,
    /*      GL_SCISSOR_TEST */
    _ES3_GL_COLOR_CLEAR_VALUE = GL_COLOR_CLEAR_VALUE,
    _ES3_GL_COLOR_WRITEMASK = GL_COLOR_WRITEMASK,
    _ES3_GL_UNPACK_ALIGNMENT = GL_UNPACK_ALIGNMENT,
    _ES3_GL_PACK_ALIGNMENT = GL_PACK_ALIGNMENT,
    _ES3_GL_MAX_TEXTURE_SIZE = GL_MAX_TEXTURE_SIZE,
    _ES3_GL_MAX_VIEWPORT_DIMS = GL_MAX_VIEWPORT_DIMS,
    _ES3_GL_SUBPIXEL_BITS = GL_SUBPIXEL_BITS,
    _ES3_GL_RED_BITS = GL_RED_BITS,
    _ES3_GL_GREEN_BITS = GL_GREEN_BITS,
    _ES3_GL_BLUE_BITS = GL_BLUE_BITS,
    _ES3_GL_ALPHA_BITS = GL_ALPHA_BITS,
    _ES3_GL_DEPTH_BITS = GL_DEPTH_BITS,
    _ES3_GL_STENCIL_BITS = GL_STENCIL_BITS,
    _ES3_GL_POLYGON_OFFSET_UNITS = GL_POLYGON_OFFSET_UNITS,
    /*      GL_POLYGON_OFFSET_FILL */
    _ES3_GL_POLYGON_OFFSET_FACTOR = GL_POLYGON_OFFSET_FACTOR,
    _ES3_GL_TEXTURE_BINDING_2D = GL_TEXTURE_BINDING_2D,
    _ES3_GL_SAMPLE_BUFFERS = GL_SAMPLE_BUFFERS,
    _ES3_GL_SAMPLES = GL_SAMPLES,
    _ES3_GL_SAMPLE_COVERAGE_VALUE = GL_SAMPLE_COVERAGE_VALUE,
    _ES3_GL_SAMPLE_COVERAGE_INVERT = GL_SAMPLE_COVERAGE_INVERT,
    
    /* GetTextureParameter */
    /*      GL_TEXTURE_MAG_FILTER */
    /*      GL_TEXTURE_MIN_FILTER */
    /*      GL_TEXTURE_WRAP_S */
    /*      GL_TEXTURE_WRAP_T */
    
    _ES3_GL_NUM_COMPRESSED_TEXTURE_FORMATS = GL_NUM_COMPRESSED_TEXTURE_FORMATS,
    _ES3_GL_COMPRESSED_TEXTURE_FORMATS = GL_COMPRESSED_TEXTURE_FORMATS,
    
    /* HintMode */
    _ES3_GL_DONT_CARE = GL_DONT_CARE,
    _ES3_GL_FASTEST = GL_FASTEST,
    _ES3_GL_NICEST = GL_NICEST,
    
    /* HintTarget */
    _ES3_GL_GENERATE_MIPMAP_HINT = GL_GENERATE_MIPMAP_HINT,
    
    /* DataType */
    _ES3_GL_BYTE = GL_BYTE,
    _ES3_GL_UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
    _ES3_GL_SHORT = GL_SHORT,
    _ES3_GL_UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
    _ES3_GL_INT = GL_INT,
    _ES3_GL_UNSIGNED_INT = GL_UNSIGNED_INT,
    _ES3_GL_FLOAT = GL_FLOAT,
    _ES3_GL_FIXED = GL_FIXED,
    
    /* PixelFormat */
    _ES3_GL_DEPTH_COMPONENT = GL_DEPTH_COMPONENT,
    _ES3_GL_ALPHA = GL_ALPHA,
    _ES3_GL_RGB = GL_RGB,
    _ES3_GL_RGBA = GL_RGBA,
    _ES3_GL_LUMINANCE = GL_LUMINANCE,
    _ES3_GL_LUMINANCE_ALPHA = GL_LUMINANCE_ALPHA,
    
    /* PixelType */
    /*      GL_UNSIGNED_BYTE */
    _ES3_GL_UNSIGNED_SHORT_4_4_4_4 = GL_UNSIGNED_SHORT_4_4_4_4,
    _ES3_GL_UNSIGNED_SHORT_5_5_5_1 = GL_UNSIGNED_SHORT_5_5_5_1,
    _ES3_GL_UNSIGNED_SHORT_5_6_5 = GL_UNSIGNED_SHORT_5_6_5,
    
    /* Shaders */
    _ES3_GL_FRAGMENT_SHADER = GL_FRAGMENT_SHADER,
    _ES3_GL_VERTEX_SHADER = GL_VERTEX_SHADER,
    _ES3_GL_MAX_VERTEX_ATTRIBS = GL_MAX_VERTEX_ATTRIBS,
    _ES3_GL_MAX_VERTEX_UNIFORM_VECTORS = GL_MAX_VERTEX_UNIFORM_VECTORS,
    _ES3_GL_MAX_VARYING_VECTORS = GL_MAX_VARYING_VECTORS,
    _ES3_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS,
    _ES3_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS,
    _ES3_GL_MAX_TEXTURE_IMAGE_UNITS = GL_MAX_TEXTURE_IMAGE_UNITS,
    _ES3_GL_MAX_FRAGMENT_UNIFORM_VECTORS = GL_MAX_FRAGMENT_UNIFORM_VECTORS,
    _ES3_GL_SHADER_TYPE = GL_SHADER_TYPE,
    _ES3_GL_DELETE_STATUS = GL_DELETE_STATUS,
    _ES3_GL_LINK_STATUS = GL_LINK_STATUS,
    _ES3_GL_VALIDATE_STATUS = GL_VALIDATE_STATUS,
    _ES3_GL_ATTACHED_SHADERS = GL_ATTACHED_SHADERS,
    _ES3_GL_ACTIVE_UNIFORMS = GL_ACTIVE_UNIFORMS,
    _ES3_GL_ACTIVE_UNIFORM_MAX_LENGTH = GL_ACTIVE_UNIFORM_MAX_LENGTH,
    _ES3_GL_ACTIVE_ATTRIBUTES = GL_ACTIVE_ATTRIBUTES,
    _ES3_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = GL_ACTIVE_ATTRIBUTE_MAX_LENGTH,
    _ES3_GL_SHADING_LANGUAGE_VERSION = GL_SHADING_LANGUAGE_VERSION,
    _ES3_GL_CURRENT_PROGRAM = GL_CURRENT_PROGRAM,
    
    /* StencilFunction */
    _ES3_GL_NEVER = GL_NEVER,
    _ES3_GL_LESS = GL_LESS,
    _ES3_GL_EQUAL = GL_EQUAL,
    _ES3_GL_LEQUAL = GL_LEQUAL,
    _ES3_GL_GREATER = GL_GREATER,
    _ES3_GL_NOTEQUAL = GL_NOTEQUAL,
    _ES3_GL_GEQUAL = GL_GEQUAL,
    _ES3_GL_ALWAYS = GL_ALWAYS,
    
    /* StencilOp */
    /*      GL_ZERO */
    _ES3_GL_KEEP = GL_KEEP,
    _ES3_GL_REPLACE = GL_REPLACE,
    _ES3_GL_INCR = GL_INCR,
    _ES3_GL_DECR = GL_DECR,
    _ES3_GL_INVERT = GL_INVERT,
    _ES3_GL_INCR_WRAP = GL_INCR_WRAP,
    _ES3_GL_DECR_WRAP = GL_DECR_WRAP,
    
    /* StringName */
    _ES3_GL_VENDOR = GL_VENDOR,
    _ES3_GL_RENDERER = GL_RENDERER,
    _ES3_GL_VERSION = GL_VERSION,
    _ES3_GL_EXTENSIONS = GL_EXTENSIONS,
    
    /* TextureMagFilter */
    _ES3_GL_NEAREST = GL_NEAREST,
    _ES3_GL_LINEAR = GL_LINEAR,
    
    /* TextureMinFilter */
    /*      GL_NEAREST */
    /*      GL_LINEAR */
    _ES3_GL_NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
    _ES3_GL_LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
    _ES3_GL_NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
    _ES3_GL_LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
    
    /* TextureParameterName */
    _ES3_GL_TEXTURE_MAG_FILTER = GL_TEXTURE_MAG_FILTER,
    _ES3_GL_TEXTURE_MIN_FILTER = GL_TEXTURE_MIN_FILTER,
    _ES3_GL_TEXTURE_WRAP_S = GL_TEXTURE_WRAP_S,
    _ES3_GL_TEXTURE_WRAP_T = GL_TEXTURE_WRAP_T,
    
    /* TextureTarget */
    /*      GL_TEXTURE_2D */
    _ES3_GL_TEXTURE = GL_TEXTURE,
    
    _ES3_GL_TEXTURE_CUBE_MAP = GL_TEXTURE_CUBE_MAP,
    _ES3_GL_TEXTURE_BINDING_CUBE_MAP = GL_TEXTURE_BINDING_CUBE_MAP,
    _ES3_GL_TEXTURE_CUBE_MAP_POSITIVE_X = GL_TEXTURE_CUBE_MAP_POSITIVE_X,
    _ES3_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
    _ES3_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
    _ES3_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y,
    _ES3_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
    _ES3_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z,
    _ES3_GL_MAX_CUBE_MAP_TEXTURE_SIZE = GL_MAX_CUBE_MAP_TEXTURE_SIZE,
    
    /* TextureUnit */
    _ES3_GL_TEXTURE0 = GL_TEXTURE0,
    _ES3_GL_TEXTURE1 = GL_TEXTURE1,
    _ES3_GL_TEXTURE2 = GL_TEXTURE2,
    _ES3_GL_TEXTURE3 = GL_TEXTURE3,
    _ES3_GL_TEXTURE4 = GL_TEXTURE4,
    _ES3_GL_TEXTURE5 = GL_TEXTURE5,
    _ES3_GL_TEXTURE6 = GL_TEXTURE6,
    _ES3_GL_TEXTURE7 = GL_TEXTURE7,
    _ES3_GL_TEXTURE8 = GL_TEXTURE8,
    _ES3_GL_TEXTURE9 = GL_TEXTURE9,
    _ES3_GL_TEXTURE10 = GL_TEXTURE10,
    _ES3_GL_TEXTURE11 = GL_TEXTURE11,
    _ES3_GL_TEXTURE12 = GL_TEXTURE12,
    _ES3_GL_TEXTURE13 = GL_TEXTURE13,
    _ES3_GL_TEXTURE14 = GL_TEXTURE14,
    _ES3_GL_TEXTURE15 = GL_TEXTURE15,
    _ES3_GL_TEXTURE16 = GL_TEXTURE16,
    _ES3_GL_TEXTURE17 = GL_TEXTURE17,
    _ES3_GL_TEXTURE18 = GL_TEXTURE18,
    _ES3_GL_TEXTURE19 = GL_TEXTURE19,
    _ES3_GL_TEXTURE20 = GL_TEXTURE20,
    _ES3_GL_TEXTURE21 = GL_TEXTURE21,
    _ES3_GL_TEXTURE22 = GL_TEXTURE22,
    _ES3_GL_TEXTURE23 = GL_TEXTURE23,
    _ES3_GL_TEXTURE24 = GL_TEXTURE24,
    _ES3_GL_TEXTURE25 = GL_TEXTURE25,
    _ES3_GL_TEXTURE26 = GL_TEXTURE26,
    _ES3_GL_TEXTURE27 = GL_TEXTURE27,
    _ES3_GL_TEXTURE28 = GL_TEXTURE28,
    _ES3_GL_TEXTURE29 = GL_TEXTURE29,
    _ES3_GL_TEXTURE30 = GL_TEXTURE30,
    _ES3_GL_TEXTURE31 = GL_TEXTURE31,
    _ES3_GL_ACTIVE_TEXTURE = GL_ACTIVE_TEXTURE,
    
    /* TextureWrapMode */
    _ES3_GL_REPEAT = GL_REPEAT,
    _ES3_GL_CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
    _ES3_GL_MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
    
    /* Uniform Types */
    _ES3_GL_FLOAT_VEC2 = GL_FLOAT_VEC2,
    _ES3_GL_FLOAT_VEC3 = GL_FLOAT_VEC3,
    _ES3_GL_FLOAT_VEC4 = GL_FLOAT_VEC4,
    _ES3_GL_INT_VEC2 = GL_INT_VEC2,
    _ES3_GL_INT_VEC3 = GL_INT_VEC3,
    _ES3_GL_INT_VEC4 = GL_INT_VEC4,
    _ES3_GL_BOOL = GL_BOOL,
    _ES3_GL_BOOL_VEC2 = GL_BOOL_VEC2,
    _ES3_GL_BOOL_VEC3 = GL_BOOL_VEC3,
    _ES3_GL_BOOL_VEC4 = GL_BOOL_VEC4,
    _ES3_GL_FLOAT_MAT2 = GL_FLOAT_MAT2,
    _ES3_GL_FLOAT_MAT3 = GL_FLOAT_MAT3,
    _ES3_GL_FLOAT_MAT4 = GL_FLOAT_MAT4,
    _ES3_GL_SAMPLER_2D = GL_SAMPLER_2D,
    _ES3_GL_SAMPLER_CUBE = GL_SAMPLER_CUBE,
    
    /* Vertex Arrays */
    _ES3_GL_VERTEX_ATTRIB_ARRAY_ENABLED = GL_VERTEX_ATTRIB_ARRAY_ENABLED,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_SIZE = GL_VERTEX_ATTRIB_ARRAY_SIZE,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_STRIDE = GL_VERTEX_ATTRIB_ARRAY_STRIDE,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_TYPE = GL_VERTEX_ATTRIB_ARRAY_TYPE,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = GL_VERTEX_ATTRIB_ARRAY_NORMALIZED,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_POINTER = GL_VERTEX_ATTRIB_ARRAY_POINTER,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING,
    
    /* Read Format */
    _ES3_GL_IMPLEMENTATION_COLOR_READ_TYPE = GL_IMPLEMENTATION_COLOR_READ_TYPE,
    _ES3_GL_IMPLEMENTATION_COLOR_READ_FORMAT = GL_IMPLEMENTATION_COLOR_READ_FORMAT,
    
    /* Shader Source */
    _ES3_GL_COMPILE_STATUS = GL_COMPILE_STATUS,
    _ES3_GL_INFO_LOG_LENGTH = GL_INFO_LOG_LENGTH,
    _ES3_GL_SHADER_SOURCE_LENGTH = GL_SHADER_SOURCE_LENGTH,
    _ES3_GL_SHADER_COMPILER = GL_SHADER_COMPILER,
    
    /* Shader Binary */
    _ES3_GL_SHADER_BINARY_FORMATS = GL_SHADER_BINARY_FORMATS,
    _ES3_GL_NUM_SHADER_BINARY_FORMATS = GL_NUM_SHADER_BINARY_FORMATS,
    
    /* Shader Precision-Specified Types */
    _ES3_GL_LOW_FLOAT = GL_LOW_FLOAT,
    _ES3_GL_MEDIUM_FLOAT = GL_MEDIUM_FLOAT,
    _ES3_GL_HIGH_FLOAT = GL_HIGH_FLOAT,
    _ES3_GL_LOW_INT = GL_LOW_INT,
    _ES3_GL_MEDIUM_INT = GL_MEDIUM_INT,
    _ES3_GL_HIGH_INT = GL_HIGH_INT,
    
    /* Framebuffer Object. */
    _ES3_GL_FRAMEBUFFER = GL_FRAMEBUFFER,
    _ES3_GL_RENDERBUFFER = GL_RENDERBUFFER,
    
    _ES3_GL_RGBA4 = GL_RGBA4,
    _ES3_GL_RGB5_A1 = GL_RGB5_A1,
    _ES3_GL_RGB565 = GL_RGB565,
    _ES3_GL_DEPTH_COMPONENT16 = GL_DEPTH_COMPONENT16,
    _ES3_GL_STENCIL_INDEX8 = GL_STENCIL_INDEX8,
    
    _ES3_GL_RENDERBUFFER_WIDTH = GL_RENDERBUFFER_WIDTH,
    _ES3_GL_RENDERBUFFER_HEIGHT = GL_RENDERBUFFER_HEIGHT,
    _ES3_GL_RENDERBUFFER_INTERNAL_FORMAT = GL_RENDERBUFFER_INTERNAL_FORMAT,
    _ES3_GL_RENDERBUFFER_RED_SIZE = GL_RENDERBUFFER_RED_SIZE,
    _ES3_GL_RENDERBUFFER_GREEN_SIZE = GL_RENDERBUFFER_GREEN_SIZE,
    _ES3_GL_RENDERBUFFER_BLUE_SIZE = GL_RENDERBUFFER_BLUE_SIZE,
    _ES3_GL_RENDERBUFFER_ALPHA_SIZE = GL_RENDERBUFFER_ALPHA_SIZE,
    _ES3_GL_RENDERBUFFER_DEPTH_SIZE = GL_RENDERBUFFER_DEPTH_SIZE,
    _ES3_GL_RENDERBUFFER_STENCIL_SIZE = GL_RENDERBUFFER_STENCIL_SIZE,
    
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE,
    
    _ES3_GL_COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
    _ES3_GL_DEPTH_ATTACHMENT = GL_DEPTH_ATTACHMENT,
    _ES3_GL_STENCIL_ATTACHMENT = GL_STENCIL_ATTACHMENT,
    
    _ES3_GL_NONE = GL_NONE,
    
    _ES3_GL_FRAMEBUFFER_COMPLETE = GL_FRAMEBUFFER_COMPLETE,
    _ES3_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT,
    _ES3_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT,
    _ES3_GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS = GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS,
    _ES3_GL_FRAMEBUFFER_UNSUPPORTED = GL_FRAMEBUFFER_UNSUPPORTED,
    
    _ES3_GL_FRAMEBUFFER_BINDING = GL_FRAMEBUFFER_BINDING,
    _ES3_GL_RENDERBUFFER_BINDING = GL_RENDERBUFFER_BINDING,
    _ES3_GL_MAX_RENDERBUFFER_SIZE = GL_MAX_RENDERBUFFER_SIZE,
    
    _ES3_GL_INVALID_FRAMEBUFFER_OPERATION = GL_INVALID_FRAMEBUFFER_OPERATION,
    
    /* OpenGL ES 3.0 */
    
    _ES3_GL_READ_BUFFER = GL_READ_BUFFER,
    _ES3_GL_UNPACK_ROW_LENGTH = GL_UNPACK_ROW_LENGTH,
    _ES3_GL_UNPACK_SKIP_ROWS = GL_UNPACK_SKIP_ROWS,
    _ES3_GL_UNPACK_SKIP_PIXELS = GL_UNPACK_SKIP_PIXELS,
    _ES3_GL_PACK_ROW_LENGTH = GL_PACK_ROW_LENGTH,
    _ES3_GL_PACK_SKIP_ROWS = GL_PACK_SKIP_ROWS,
    _ES3_GL_PACK_SKIP_PIXELS = GL_PACK_SKIP_PIXELS,
    _ES3_GL_COLOR = GL_COLOR,
    _ES3_GL_DEPTH = GL_DEPTH,
    _ES3_GL_STENCIL = GL_STENCIL,
    _ES3_GL_RED = GL_RED,
    _ES3_GL_RGB8 = GL_RGB8,
    _ES3_GL_RGBA8 = GL_RGBA8,
    _ES3_GL_RGB10_A2 = GL_RGB10_A2,
    _ES3_GL_TEXTURE_BINDING_3D = GL_TEXTURE_BINDING_3D,
    _ES3_GL_UNPACK_SKIP_IMAGES = GL_UNPACK_SKIP_IMAGES,
    _ES3_GL_UNPACK_IMAGE_HEIGHT = GL_UNPACK_IMAGE_HEIGHT,
    _ES3_GL_TEXTURE_3D = GL_TEXTURE_3D,
    _ES3_GL_TEXTURE_WRAP_R = GL_TEXTURE_WRAP_R,
    _ES3_GL_MAX_3D_TEXTURE_SIZE = GL_MAX_3D_TEXTURE_SIZE,
    _ES3_GL_UNSIGNED_INT_2_10_10_10_REV = GL_UNSIGNED_INT_2_10_10_10_REV,
    _ES3_GL_MAX_ELEMENTS_VERTICES = GL_MAX_ELEMENTS_VERTICES,
    _ES3_GL_MAX_ELEMENTS_INDICES = GL_MAX_ELEMENTS_INDICES,
    _ES3_GL_TEXTURE_MIN_LOD = GL_TEXTURE_MIN_LOD,
    _ES3_GL_TEXTURE_MAX_LOD = GL_TEXTURE_MAX_LOD,
    _ES3_GL_TEXTURE_BASE_LEVEL = GL_TEXTURE_BASE_LEVEL,
    _ES3_GL_TEXTURE_MAX_LEVEL = GL_TEXTURE_MAX_LEVEL,
    _ES3_GL_MIN = GL_MIN,
    _ES3_GL_MAX = GL_MAX,
    _ES3_GL_DEPTH_COMPONENT24 = GL_DEPTH_COMPONENT24,
    _ES3_GL_MAX_TEXTURE_LOD_BIAS = GL_MAX_TEXTURE_LOD_BIAS,
    _ES3_GL_TEXTURE_COMPARE_MODE = GL_TEXTURE_COMPARE_MODE,
    _ES3_GL_TEXTURE_COMPARE_FUNC = GL_TEXTURE_COMPARE_FUNC,
    _ES3_GL_CURRENT_QUERY = GL_CURRENT_QUERY,
    _ES3_GL_QUERY_RESULT = GL_QUERY_RESULT,
    _ES3_GL_QUERY_RESULT_AVAILABLE = GL_QUERY_RESULT_AVAILABLE,
    _ES3_GL_BUFFER_MAPPED = GL_BUFFER_MAPPED,
    _ES3_GL_BUFFER_MAP_POINTER = GL_BUFFER_MAP_POINTER,
    _ES3_GL_STREAM_READ = GL_STREAM_READ,
    _ES3_GL_STREAM_COPY = GL_STREAM_COPY,
    _ES3_GL_STATIC_READ = GL_STATIC_READ,
    _ES3_GL_STATIC_COPY = GL_STATIC_COPY,
    _ES3_GL_DYNAMIC_READ = GL_DYNAMIC_READ,
    _ES3_GL_DYNAMIC_COPY = GL_DYNAMIC_COPY,
    _ES3_GL_MAX_DRAW_BUFFERS = GL_MAX_DRAW_BUFFERS,
    _ES3_GL_DRAW_BUFFER0 = GL_DRAW_BUFFER0,
    _ES3_GL_DRAW_BUFFER1 = GL_DRAW_BUFFER1,
    _ES3_GL_DRAW_BUFFER2 = GL_DRAW_BUFFER2,
    _ES3_GL_DRAW_BUFFER3 = GL_DRAW_BUFFER3,
    _ES3_GL_DRAW_BUFFER4 = GL_DRAW_BUFFER4,
    _ES3_GL_DRAW_BUFFER5 = GL_DRAW_BUFFER5,
    _ES3_GL_DRAW_BUFFER6 = GL_DRAW_BUFFER6,
    _ES3_GL_DRAW_BUFFER7 = GL_DRAW_BUFFER7,
    _ES3_GL_DRAW_BUFFER8 = GL_DRAW_BUFFER8,
    _ES3_GL_DRAW_BUFFER9 = GL_DRAW_BUFFER9,
    _ES3_GL_DRAW_BUFFER10 = GL_DRAW_BUFFER10,
    _ES3_GL_DRAW_BUFFER11 = GL_DRAW_BUFFER11,
    _ES3_GL_DRAW_BUFFER12 = GL_DRAW_BUFFER12,
    _ES3_GL_DRAW_BUFFER13 = GL_DRAW_BUFFER13,
    _ES3_GL_DRAW_BUFFER14 = GL_DRAW_BUFFER14,
    _ES3_GL_DRAW_BUFFER15 = GL_DRAW_BUFFER15,
    _ES3_GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = GL_MAX_FRAGMENT_UNIFORM_COMPONENTS,
    _ES3_GL_MAX_VERTEX_UNIFORM_COMPONENTS = GL_MAX_VERTEX_UNIFORM_COMPONENTS,
    _ES3_GL_SAMPLER_3D = GL_SAMPLER_3D,
    _ES3_GL_SAMPLER_2D_SHADOW = GL_SAMPLER_2D_SHADOW,
    _ES3_GL_FRAGMENT_SHADER_DERIVATIVE_HINT = GL_FRAGMENT_SHADER_DERIVATIVE_HINT,
    _ES3_GL_PIXEL_PACK_BUFFER = GL_PIXEL_PACK_BUFFER,
    _ES3_GL_PIXEL_UNPACK_BUFFER = GL_PIXEL_UNPACK_BUFFER,
    _ES3_GL_PIXEL_PACK_BUFFER_BINDING = GL_PIXEL_PACK_BUFFER_BINDING,
    _ES3_GL_PIXEL_UNPACK_BUFFER_BINDING = GL_PIXEL_UNPACK_BUFFER_BINDING,
    _ES3_GL_FLOAT_MAT2x3 = GL_FLOAT_MAT2x3,
    _ES3_GL_FLOAT_MAT2x4 = GL_FLOAT_MAT2x4,
    _ES3_GL_FLOAT_MAT3x2 = GL_FLOAT_MAT3x2,
    _ES3_GL_FLOAT_MAT3x4 = GL_FLOAT_MAT3x4,
    _ES3_GL_FLOAT_MAT4x2 = GL_FLOAT_MAT4x2,
    _ES3_GL_FLOAT_MAT4x3 = GL_FLOAT_MAT4x3,
    _ES3_GL_SRGB = GL_SRGB,
    _ES3_GL_SRGB8 = GL_SRGB8,
    _ES3_GL_SRGB8_ALPHA8 = GL_SRGB8_ALPHA8,
    _ES3_GL_COMPARE_REF_TO_TEXTURE = GL_COMPARE_REF_TO_TEXTURE,
    _ES3_GL_MAJOR_VERSION = GL_MAJOR_VERSION,
    _ES3_GL_MINOR_VERSION = GL_MINOR_VERSION,
    _ES3_GL_NUM_EXTENSIONS = GL_NUM_EXTENSIONS,
    _ES3_GL_RGBA32F = GL_RGBA32F,
    _ES3_GL_RGB32F = GL_RGB32F,
    _ES3_GL_RGBA16F = GL_RGBA16F,
    _ES3_GL_RGB16F = GL_RGB16F,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_INTEGER = GL_VERTEX_ATTRIB_ARRAY_INTEGER,
    _ES3_GL_MAX_ARRAY_TEXTURE_LAYERS = GL_MAX_ARRAY_TEXTURE_LAYERS,
    _ES3_GL_MIN_PROGRAM_TEXEL_OFFSET = GL_MIN_PROGRAM_TEXEL_OFFSET,
    _ES3_GL_MAX_PROGRAM_TEXEL_OFFSET = GL_MAX_PROGRAM_TEXEL_OFFSET,
    _ES3_GL_MAX_VARYING_COMPONENTS = GL_MAX_VARYING_COMPONENTS,
    _ES3_GL_TEXTURE_2D_ARRAY = GL_TEXTURE_2D_ARRAY,
    _ES3_GL_TEXTURE_BINDING_2D_ARRAY = GL_TEXTURE_BINDING_2D_ARRAY,
    _ES3_GL_R11F_G11F_B10F = GL_R11F_G11F_B10F,
    _ES3_GL_UNSIGNED_INT_10F_11F_11F_REV = GL_UNSIGNED_INT_10F_11F_11F_REV,
    _ES3_GL_RGB9_E5 = GL_RGB9_E5,
    _ES3_GL_UNSIGNED_INT_5_9_9_9_REV = GL_UNSIGNED_INT_5_9_9_9_REV,
    _ES3_GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH,
    _ES3_GL_TRANSFORM_FEEDBACK_BUFFER_MODE = GL_TRANSFORM_FEEDBACK_BUFFER_MODE,
    _ES3_GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS,
    _ES3_GL_TRANSFORM_FEEDBACK_VARYINGS = GL_TRANSFORM_FEEDBACK_VARYINGS,
    _ES3_GL_TRANSFORM_FEEDBACK_BUFFER_START = GL_TRANSFORM_FEEDBACK_BUFFER_START,
    _ES3_GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = GL_TRANSFORM_FEEDBACK_BUFFER_SIZE,
    _ES3_GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN,
    _ES3_GL_RASTERIZER_DISCARD = GL_RASTERIZER_DISCARD,
    _ES3_GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS,
    _ES3_GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS,
    _ES3_GL_INTERLEAVED_ATTRIBS = GL_INTERLEAVED_ATTRIBS,
    _ES3_GL_SEPARATE_ATTRIBS = GL_SEPARATE_ATTRIBS,
    _ES3_GL_TRANSFORM_FEEDBACK_BUFFER = GL_TRANSFORM_FEEDBACK_BUFFER,
    _ES3_GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = GL_TRANSFORM_FEEDBACK_BUFFER_BINDING,
    _ES3_GL_RGBA32UI = GL_RGBA32UI,
    _ES3_GL_RGB32UI = GL_RGB32UI,
    _ES3_GL_RGBA16UI = GL_RGBA16UI,
    _ES3_GL_RGB16UI = GL_RGB16UI,
    _ES3_GL_RGBA8UI = GL_RGBA8UI,
    _ES3_GL_RGB8UI = GL_RGB8UI,
    _ES3_GL_RGBA32I = GL_RGBA32I,
    _ES3_GL_RGB32I = GL_RGB32I,
    _ES3_GL_RGBA16I = GL_RGBA16I,
    _ES3_GL_RGB16I = GL_RGB16I,
    _ES3_GL_RGBA8I = GL_RGBA8I,
    _ES3_GL_RGB8I = GL_RGB8I,
    _ES3_GL_RED_INTEGER = GL_RED_INTEGER,
    _ES3_GL_RGB_INTEGER = GL_RGB_INTEGER,
    _ES3_GL_RGBA_INTEGER = GL_RGBA_INTEGER,
    _ES3_GL_SAMPLER_2D_ARRAY = GL_SAMPLER_2D_ARRAY,
    _ES3_GL_SAMPLER_2D_ARRAY_SHADOW = GL_SAMPLER_2D_ARRAY_SHADOW,
    _ES3_GL_SAMPLER_CUBE_SHADOW = GL_SAMPLER_CUBE_SHADOW,
    _ES3_GL_UNSIGNED_INT_VEC2 = GL_UNSIGNED_INT_VEC2,
    _ES3_GL_UNSIGNED_INT_VEC3 = GL_UNSIGNED_INT_VEC3,
    _ES3_GL_UNSIGNED_INT_VEC4 = GL_UNSIGNED_INT_VEC4,
    _ES3_GL_INT_SAMPLER_2D = GL_INT_SAMPLER_2D,
    _ES3_GL_INT_SAMPLER_3D = GL_INT_SAMPLER_3D,
    _ES3_GL_INT_SAMPLER_CUBE = GL_INT_SAMPLER_CUBE,
    _ES3_GL_INT_SAMPLER_2D_ARRAY = GL_INT_SAMPLER_2D_ARRAY,
    _ES3_GL_UNSIGNED_INT_SAMPLER_2D = GL_UNSIGNED_INT_SAMPLER_2D,
    _ES3_GL_UNSIGNED_INT_SAMPLER_3D = GL_UNSIGNED_INT_SAMPLER_3D,
    _ES3_GL_UNSIGNED_INT_SAMPLER_CUBE = GL_UNSIGNED_INT_SAMPLER_CUBE,
    _ES3_GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = GL_UNSIGNED_INT_SAMPLER_2D_ARRAY,
    _ES3_GL_BUFFER_ACCESS_FLAGS = GL_BUFFER_ACCESS_FLAGS,
    _ES3_GL_BUFFER_MAP_LENGTH = GL_BUFFER_MAP_LENGTH,
    _ES3_GL_BUFFER_MAP_OFFSET = GL_BUFFER_MAP_OFFSET,
    _ES3_GL_DEPTH_COMPONENT32F = GL_DEPTH_COMPONENT32F,
    _ES3_GL_DEPTH32F_STENCIL8 = GL_DEPTH32F_STENCIL8,
    _ES3_GL_FLOAT_32_UNSIGNED_INT_24_8_REV = GL_FLOAT_32_UNSIGNED_INT_24_8_REV,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE,
    _ES3_GL_FRAMEBUFFER_DEFAULT = GL_FRAMEBUFFER_DEFAULT,
    _ES3_GL_FRAMEBUFFER_UNDEFINED = GL_FRAMEBUFFER_UNDEFINED,
    _ES3_GL_DEPTH_STENCIL_ATTACHMENT = GL_DEPTH_STENCIL_ATTACHMENT,
    _ES3_GL_DEPTH_STENCIL = GL_DEPTH_STENCIL,
    _ES3_GL_UNSIGNED_INT_24_8 = GL_UNSIGNED_INT_24_8,
    _ES3_GL_DEPTH24_STENCIL8 = GL_DEPTH24_STENCIL8,
    _ES3_GL_UNSIGNED_NORMALIZED = GL_UNSIGNED_NORMALIZED,
    _ES3_GL_DRAW_FRAMEBUFFER_BINDING = GL_DRAW_FRAMEBUFFER_BINDING,
    _ES3_GL_READ_FRAMEBUFFER = GL_READ_FRAMEBUFFER,
    _ES3_GL_DRAW_FRAMEBUFFER = GL_DRAW_FRAMEBUFFER,
    _ES3_GL_READ_FRAMEBUFFER_BINDING = GL_READ_FRAMEBUFFER_BINDING,
    _ES3_GL_RENDERBUFFER_SAMPLES = GL_RENDERBUFFER_SAMPLES,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER,
    _ES3_GL_MAX_COLOR_ATTACHMENTS = GL_MAX_COLOR_ATTACHMENTS,
    _ES3_GL_COLOR_ATTACHMENT1 = GL_COLOR_ATTACHMENT1,
    _ES3_GL_COLOR_ATTACHMENT2 = GL_COLOR_ATTACHMENT2,
    _ES3_GL_COLOR_ATTACHMENT3 = GL_COLOR_ATTACHMENT3,
    _ES3_GL_COLOR_ATTACHMENT4 = GL_COLOR_ATTACHMENT4,
    _ES3_GL_COLOR_ATTACHMENT5 = GL_COLOR_ATTACHMENT5,
    _ES3_GL_COLOR_ATTACHMENT6 = GL_COLOR_ATTACHMENT6,
    _ES3_GL_COLOR_ATTACHMENT7 = GL_COLOR_ATTACHMENT7,
    _ES3_GL_COLOR_ATTACHMENT8 = GL_COLOR_ATTACHMENT8,
    _ES3_GL_COLOR_ATTACHMENT9 = GL_COLOR_ATTACHMENT9,
    _ES3_GL_COLOR_ATTACHMENT10 = GL_COLOR_ATTACHMENT10,
    _ES3_GL_COLOR_ATTACHMENT11 = GL_COLOR_ATTACHMENT11,
    _ES3_GL_COLOR_ATTACHMENT12 = GL_COLOR_ATTACHMENT12,
    _ES3_GL_COLOR_ATTACHMENT13 = GL_COLOR_ATTACHMENT13,
    _ES3_GL_COLOR_ATTACHMENT14 = GL_COLOR_ATTACHMENT14,
    _ES3_GL_COLOR_ATTACHMENT15 = GL_COLOR_ATTACHMENT15,
    _ES3_GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE,
    _ES3_GL_MAX_SAMPLES = GL_MAX_SAMPLES,
    _ES3_GL_HALF_FLOAT = GL_HALF_FLOAT,
    _ES3_GL_MAP_READ_BIT = GL_MAP_READ_BIT,
    _ES3_GL_MAP_WRITE_BIT = GL_MAP_WRITE_BIT,
    _ES3_GL_MAP_INVALIDATE_RANGE_BIT = GL_MAP_INVALIDATE_RANGE_BIT,
    _ES3_GL_MAP_INVALIDATE_BUFFER_BIT = GL_MAP_INVALIDATE_BUFFER_BIT,
    _ES3_GL_MAP_FLUSH_EXPLICIT_BIT = GL_MAP_FLUSH_EXPLICIT_BIT,
    _ES3_GL_MAP_UNSYNCHRONIZED_BIT = GL_MAP_UNSYNCHRONIZED_BIT,
    _ES3_GL_RG = GL_RG,
    _ES3_GL_RG_INTEGER = GL_RG_INTEGER,
    _ES3_GL_R8 = GL_R8,
    _ES3_GL_RG8 = GL_RG8,
    _ES3_GL_R16F = GL_R16F,
    _ES3_GL_R32F = GL_R32F,
    _ES3_GL_RG16F = GL_RG16F,
    _ES3_GL_RG32F = GL_RG32F,
    _ES3_GL_R8I = GL_R8I,
    _ES3_GL_R8UI = GL_R8UI,
    _ES3_GL_R16I = GL_R16I,
    _ES3_GL_R16UI = GL_R16UI,
    _ES3_GL_R32I = GL_R32I,
    _ES3_GL_R32UI = GL_R32UI,
    _ES3_GL_RG8I = GL_RG8I,
    _ES3_GL_RG8UI = GL_RG8UI,
    _ES3_GL_RG16I = GL_RG16I,
    _ES3_GL_RG16UI = GL_RG16UI,
    _ES3_GL_RG32I = GL_RG32I,
    _ES3_GL_RG32UI = GL_RG32UI,
    _ES3_GL_VERTEX_ARRAY_BINDING = GL_VERTEX_ARRAY_BINDING,
    _ES3_GL_R8_SNORM = GL_R8_SNORM,
    _ES3_GL_RG8_SNORM = GL_RG8_SNORM,
    _ES3_GL_RGB8_SNORM = GL_RGB8_SNORM,
    _ES3_GL_RGBA8_SNORM = GL_RGBA8_SNORM,
    _ES3_GL_SIGNED_NORMALIZED = GL_SIGNED_NORMALIZED,
    _ES3_GL_PRIMITIVE_RESTART_FIXED_INDEX = GL_PRIMITIVE_RESTART_FIXED_INDEX,
    _ES3_GL_COPY_READ_BUFFER = GL_COPY_READ_BUFFER,
    _ES3_GL_COPY_WRITE_BUFFER = GL_COPY_WRITE_BUFFER,
    _ES3_GL_COPY_READ_BUFFER_BINDING = GL_COPY_READ_BUFFER_BINDING,
    _ES3_GL_COPY_WRITE_BUFFER_BINDING = GL_COPY_WRITE_BUFFER_BINDING,
    _ES3_GL_UNIFORM_BUFFER = GL_UNIFORM_BUFFER,
    _ES3_GL_UNIFORM_BUFFER_BINDING = GL_UNIFORM_BUFFER_BINDING,
    _ES3_GL_UNIFORM_BUFFER_START = GL_UNIFORM_BUFFER_START,
    _ES3_GL_UNIFORM_BUFFER_SIZE = GL_UNIFORM_BUFFER_SIZE,
    _ES3_GL_MAX_VERTEX_UNIFORM_BLOCKS = GL_MAX_VERTEX_UNIFORM_BLOCKS,
    _ES3_GL_MAX_FRAGMENT_UNIFORM_BLOCKS = GL_MAX_FRAGMENT_UNIFORM_BLOCKS,
    _ES3_GL_MAX_COMBINED_UNIFORM_BLOCKS = GL_MAX_COMBINED_UNIFORM_BLOCKS,
    _ES3_GL_MAX_UNIFORM_BUFFER_BINDINGS = GL_MAX_UNIFORM_BUFFER_BINDINGS,
    _ES3_GL_MAX_UNIFORM_BLOCK_SIZE = GL_MAX_UNIFORM_BLOCK_SIZE,
    _ES3_GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
    _ES3_GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,
    _ES3_GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT,
    _ES3_GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH,
    _ES3_GL_ACTIVE_UNIFORM_BLOCKS = GL_ACTIVE_UNIFORM_BLOCKS,
    _ES3_GL_UNIFORM_TYPE = GL_UNIFORM_TYPE,
    _ES3_GL_UNIFORM_SIZE = GL_UNIFORM_SIZE,
    _ES3_GL_UNIFORM_NAME_LENGTH = GL_UNIFORM_NAME_LENGTH,
    _ES3_GL_UNIFORM_BLOCK_INDEX = GL_UNIFORM_BLOCK_INDEX,
    _ES3_GL_UNIFORM_OFFSET = GL_UNIFORM_OFFSET,
    _ES3_GL_UNIFORM_ARRAY_STRIDE = GL_UNIFORM_ARRAY_STRIDE,
    _ES3_GL_UNIFORM_MATRIX_STRIDE = GL_UNIFORM_MATRIX_STRIDE,
    _ES3_GL_UNIFORM_IS_ROW_MAJOR = GL_UNIFORM_IS_ROW_MAJOR,
    _ES3_GL_UNIFORM_BLOCK_BINDING = GL_UNIFORM_BLOCK_BINDING,
    _ES3_GL_UNIFORM_BLOCK_DATA_SIZE = GL_UNIFORM_BLOCK_DATA_SIZE,
    _ES3_GL_UNIFORM_BLOCK_NAME_LENGTH = GL_UNIFORM_BLOCK_NAME_LENGTH,
    _ES3_GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS,
    _ES3_GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES,
    _ES3_GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER,
    _ES3_GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER,
    _ES3_GL_INVALID_INDEX = GL_INVALID_INDEX,
    _ES3_GL_MAX_VERTEX_OUTPUT_COMPONENTS = GL_MAX_VERTEX_OUTPUT_COMPONENTS,
    _ES3_GL_MAX_FRAGMENT_INPUT_COMPONENTS = GL_MAX_FRAGMENT_INPUT_COMPONENTS,
    _ES3_GL_MAX_SERVER_WAIT_TIMEOUT = GL_MAX_SERVER_WAIT_TIMEOUT,
    _ES3_GL_OBJECT_TYPE = GL_OBJECT_TYPE,
    _ES3_GL_SYNC_CONDITION = GL_SYNC_CONDITION,
    _ES3_GL_SYNC_STATUS = GL_SYNC_STATUS,
    _ES3_GL_SYNC_FLAGS = GL_SYNC_FLAGS,
    _ES3_GL_SYNC_FENCE = GL_SYNC_FENCE,
    _ES3_GL_SYNC_GPU_COMMANDS_COMPLETE = GL_SYNC_GPU_COMMANDS_COMPLETE,
    _ES3_GL_UNSIGNALED = GL_UNSIGNALED,
    _ES3_GL_SIGNALED = GL_SIGNALED,
    _ES3_GL_ALREADY_SIGNALED = GL_ALREADY_SIGNALED,
    _ES3_GL_TIMEOUT_EXPIRED = GL_TIMEOUT_EXPIRED,
    _ES3_GL_CONDITION_SATISFIED = GL_CONDITION_SATISFIED,
    _ES3_GL_WAIT_FAILED = GL_WAIT_FAILED,
    _ES3_GL_SYNC_FLUSH_COMMANDS_BIT = GL_SYNC_FLUSH_COMMANDS_BIT,
    //_ES3_GL_TIMEOUT_IGNORED = GL_TIMEOUT_IGNORED,
    _ES3_GL_VERTEX_ATTRIB_ARRAY_DIVISOR = GL_VERTEX_ATTRIB_ARRAY_DIVISOR,
    _ES3_GL_ANY_SAMPLES_PASSED = GL_ANY_SAMPLES_PASSED,
    _ES3_GL_ANY_SAMPLES_PASSED_CONSERVATIVE = GL_ANY_SAMPLES_PASSED_CONSERVATIVE,
    _ES3_GL_SAMPLER_BINDING = GL_SAMPLER_BINDING,
    _ES3_GL_RGB10_A2UI = GL_RGB10_A2UI,
    _ES3_GL_TEXTURE_SWIZZLE_R = GL_TEXTURE_SWIZZLE_R,
    _ES3_GL_TEXTURE_SWIZZLE_G = GL_TEXTURE_SWIZZLE_G,
    _ES3_GL_TEXTURE_SWIZZLE_B = GL_TEXTURE_SWIZZLE_B,
    _ES3_GL_TEXTURE_SWIZZLE_A = GL_TEXTURE_SWIZZLE_A,
    _ES3_GL_GREEN = GL_GREEN,
    _ES3_GL_BLUE = GL_BLUE,
    _ES3_GL_INT_2_10_10_10_REV = GL_INT_2_10_10_10_REV,
    _ES3_GL_TRANSFORM_FEEDBACK = GL_TRANSFORM_FEEDBACK,
    _ES3_GL_TRANSFORM_FEEDBACK_PAUSED = GL_TRANSFORM_FEEDBACK_PAUSED,
    _ES3_GL_TRANSFORM_FEEDBACK_ACTIVE = GL_TRANSFORM_FEEDBACK_ACTIVE,
    _ES3_GL_TRANSFORM_FEEDBACK_BINDING = GL_TRANSFORM_FEEDBACK_BINDING,
    _ES3_GL_PROGRAM_BINARY_RETRIEVABLE_HINT = GL_PROGRAM_BINARY_RETRIEVABLE_HINT,
    _ES3_GL_PROGRAM_BINARY_LENGTH = GL_PROGRAM_BINARY_LENGTH,
    _ES3_GL_NUM_PROGRAM_BINARY_FORMATS = GL_NUM_PROGRAM_BINARY_FORMATS,
    _ES3_GL_PROGRAM_BINARY_FORMATS = GL_PROGRAM_BINARY_FORMATS,
    _ES3_GL_COMPRESSED_R11_EAC = GL_COMPRESSED_R11_EAC,
    _ES3_GL_COMPRESSED_SIGNED_R11_EAC = GL_COMPRESSED_SIGNED_R11_EAC,
    _ES3_GL_COMPRESSED_RG11_EAC = GL_COMPRESSED_RG11_EAC,
    _ES3_GL_COMPRESSED_SIGNED_RG11_EAC = GL_COMPRESSED_SIGNED_RG11_EAC,
    _ES3_GL_COMPRESSED_RGB8_ETC2 = GL_COMPRESSED_RGB8_ETC2,
    _ES3_GL_COMPRESSED_SRGB8_ETC2 = GL_COMPRESSED_SRGB8_ETC2,
    _ES3_GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
    _ES3_GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
    _ES3_GL_COMPRESSED_RGBA8_ETC2_EAC = GL_COMPRESSED_RGBA8_ETC2_EAC,
    _ES3_GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC,
    _ES3_GL_TEXTURE_IMMUTABLE_FORMAT = GL_TEXTURE_IMMUTABLE_FORMAT,
    _ES3_GL_MAX_ELEMENT_INDEX = GL_MAX_ELEMENT_INDEX,
    _ES3_GL_NUM_SAMPLE_COUNTS = GL_NUM_SAMPLE_COUNTS,
    _ES3_GL_TEXTURE_IMMUTABLE_LEVELS = GL_TEXTURE_IMMUTABLE_LEVELS,
    
    /*************************************************************/
    /*                          glext.h                          */
    /*************************************************************/
    
    _ES3_GL_APPLE_copy_texture_levels = GL_APPLE_copy_texture_levels,
    _ES3_GL_APPLE_rgb_422 = GL_APPLE_rgb_422,
    _ES3_GL_APPLE_texture_format_BGRA8888 = GL_APPLE_texture_format_BGRA8888,
    _ES3_GL_EXT_color_buffer_half_float = GL_EXT_color_buffer_half_float,
    _ES3_GL_EXT_debug_label = GL_EXT_debug_label,
    _ES3_GL_EXT_debug_marker = GL_EXT_debug_marker,
    _ES3_GL_EXT_pvrtc_sRGB = GL_EXT_pvrtc_sRGB,
    _ES3_GL_EXT_read_format_bgra = GL_EXT_read_format_bgra,
    _ES3_GL_EXT_separate_shader_objects = GL_EXT_separate_shader_objects,
    _ES3_GL_EXT_shader_framebuffer_fetch = GL_EXT_shader_framebuffer_fetch,
    _ES3_GL_EXT_shader_texture_lod = GL_EXT_shader_texture_lod,
    _ES3_GL_EXT_shadow_samplers = GL_EXT_shadow_samplers,
    //_ES3_GL_EXT_shader_framebuffer_fetch = GL_EXT_shader_framebuffer_fetch,
    _ES3_GL_EXT_texture_filter_anisotropic = GL_EXT_texture_filter_anisotropic,
    _ES3_GL_IMG_read_format = GL_IMG_read_format,
    _ES3_GL_IMG_texture_compression_pvrtc = GL_IMG_texture_compression_pvrtc,
    _ES3_GL_OES_standard_derivatives = GL_OES_standard_derivatives,
    
    /*------------------------------------------------------------------------*
     * APPLE extension tokens
     *------------------------------------------------------------------------*/
#if GL_APPLE_rgb_422
    _ES3_GL_RGB_422_APPLE = GL_RGB_422_APPLE,
    _ES3_GL_UNSIGNED_SHORT_8_8_APPLE = GL_UNSIGNED_SHORT_8_8_APPLE,
    _ES3_GL_UNSIGNED_SHORT_8_8_REV_APPLE = GL_UNSIGNED_SHORT_8_8_REV_APPLE,
    _ES3_GL_RGB_RAW_422_APPLE = GL_RGB_RAW_422_APPLE,
#endif
    
#if GL_APPLE_texture_format_BGRA8888
    _ES3_GL_BGRA_EXT = GL_BGRA_EXT,
    _ES3_GL_BGRA8_EXT = GL_BGRA8_EXT,
#endif
    
#if GL_APPLE_texture_format_BGRA8888 || GL_IMG_read_format
    _ES3_GL_BGRA = GL_BGRA,
#endif
    
    /*------------------------------------------------------------------------*
     * EXT extension tokens
     *------------------------------------------------------------------------*/
#if GL_EXT_color_buffer_half_float
    _ES3_GL_RGBA16F_EXT = GL_RGBA16F_EXT,
    _ES3_GL_RGB16F_EXT = GL_RGB16F_EXT,
    _ES3_GL_RG16F_EXT = GL_RG16F_EXT,
    _ES3_GL_R16F_EXT = GL_R16F_EXT,
    _ES3_GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT = GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT,
    _ES3_GL_UNSIGNED_NORMALIZED_EXT = GL_UNSIGNED_NORMALIZED_EXT,
#endif
    
#if GL_EXT_debug_label
    _ES3_GL_BUFFER_OBJECT_EXT = GL_BUFFER_OBJECT_EXT,
    _ES3_GL_SHADER_OBJECT_EXT = GL_SHADER_OBJECT_EXT,
    _ES3_GL_PROGRAM_OBJECT_EXT = GL_PROGRAM_OBJECT_EXT,
    _ES3_GL_QUERY_OBJECT_EXT = GL_QUERY_OBJECT_EXT,
    _ES3_GL_VERTEX_ARRAY_OBJECT_EXT = GL_VERTEX_ARRAY_OBJECT_EXT,
    _ES3_GL_PROGRAM_PIPELINE_OBJECT_EXT = GL_PROGRAM_PIPELINE_OBJECT_EXT,
    _ES3_GL_SYNC_OBJECT_APPLE = GL_SYNC_OBJECT_APPLE,
    _ES3_GL_SAMPLER = GL_SAMPLER,
#endif
    
#if GL_EXT_pvrtc_sRGB
    _ES3_GL_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT = GL_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT,
    _ES3_GL_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT = GL_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT,
    _ES3_GL_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT = GL_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT,
    _ES3_GL_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT = GL_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT,
#endif
    
#if GL_EXT_read_format_bgra
    _ES3_GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT = GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT,
    _ES3_GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT = GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT,
    _ES3_GL_UNSIGNED_SHORT_1_5_5_5_REV = GL_UNSIGNED_SHORT_1_5_5_5_REV,
#endif
    
#if GL_EXT_read_format_bgra || GL_IMG_read_format
    _ES3_GL_UNSIGNED_SHORT_4_4_4_4_REV = GL_UNSIGNED_SHORT_4_4_4_4_REV,
#endif
    
#if GL_EXT_separate_shader_objects
    _ES3_GL_VERTEX_SHADER_BIT_EXT = GL_VERTEX_SHADER_BIT_EXT,
    _ES3_GL_FRAGMENT_SHADER_BIT_EXT = GL_FRAGMENT_SHADER_BIT_EXT,
    _ES3_GL_ALL_SHADER_BITS_EXT = GL_ALL_SHADER_BITS_EXT,
    _ES3_GL_PROGRAM_SEPARABLE_EXT = GL_PROGRAM_SEPARABLE_EXT,
    _ES3_GL_ACTIVE_PROGRAM_EXT = GL_ACTIVE_PROGRAM_EXT,
    _ES3_GL_PROGRAM_PIPELINE_BINDING_EXT = GL_PROGRAM_PIPELINE_BINDING_EXT,
#endif
    
#if GL_EXT_shader_framebuffer_fetch
    _ES3_GL_FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT = GL_FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT,
#endif
    
#if GL_EXT_shadow_samplers
    _ES3_GL_TEXTURE_COMPARE_MODE_EXT = GL_TEXTURE_COMPARE_MODE_EXT,
    _ES3_GL_TEXTURE_COMPARE_FUNC_EXT = GL_TEXTURE_COMPARE_FUNC_EXT,
    _ES3_GL_COMPARE_REF_TO_TEXTURE_EXT = GL_COMPARE_REF_TO_TEXTURE_EXT,
    _ES3_GL_SAMPLER_2D_SHADOW_EXT = GL_SAMPLER_2D_SHADOW_EXT,
#endif
    
#if GL_EXT_texture_filter_anisotropic
    _ES3_GL_TEXTURE_MAX_ANISOTROPY_EXT = GL_TEXTURE_MAX_ANISOTROPY_EXT,
    _ES3_GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT,
#endif
    
    
    /*------------------------------------------------------------------------*
     * IMG extension tokens
     *------------------------------------------------------------------------*/
#if GL_IMG_read_format
    _ES3_GL_BGRA_IMG = GL_BGRA_IMG,
    _ES3_GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG = GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG,
#endif
    
#if GL_IMG_texture_compression_pvrtc
    _ES3_GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG = GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
    _ES3_GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG = GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
    _ES3_GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG = GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
    _ES3_GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG = GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
#endif
    
    /*------------------------------------------------------------------------*
     * OES extension tokens
     *------------------------------------------------------------------------*/
#if GL_OES_standard_derivatives
    _ES3_GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES = GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES,
#endif
    
    /**************************************************************************/
    
};

typedef enum _ES3_ ES3;

#endif /* __OpenGLES_ES3_Defines_H */
