package apple.accessorysetupkit;

import apple.NSObject;
import apple.foundation.NSArray;
import apple.foundation.NSError;
import apple.foundation.NSMethodSignature;
import apple.foundation.NSSet;
import apple.opaque.dispatch_queue_t;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.moe.natj.c.ann.FunctionPtr;
import org.moe.natj.general.NatJ;
import org.moe.natj.general.Pointer;
import org.moe.natj.general.ann.Generated;
import org.moe.natj.general.ann.Library;
import org.moe.natj.general.ann.Mapped;
import org.moe.natj.general.ann.NInt;
import org.moe.natj.general.ann.NUInt;
import org.moe.natj.general.ann.Owned;
import org.moe.natj.general.ann.Runtime;
import org.moe.natj.general.ptr.VoidPtr;
import org.moe.natj.objc.Class;
import org.moe.natj.objc.ObjCRuntime;
import org.moe.natj.objc.SEL;
import org.moe.natj.objc.ann.ObjCBlock;
import org.moe.natj.objc.ann.ObjCClassBinding;
import org.moe.natj.objc.ann.Selector;
import org.moe.natj.objc.map.ObjCObjectMapper;

/**
 * ===========================================================================================================================
 * Manages accessories.
 * 
 * API-Since: 18.0
 */
@Generated
@Library("AccessorySetupKit")
@Runtime(ObjCRuntime.class)
@ObjCClassBinding
public class ASAccessorySession extends NSObject {
    static {
        NatJ.register();
    }

    @Generated
    protected ASAccessorySession(Pointer peer) {
        super(peer);
    }

    @Generated
    @Selector("accessInstanceVariablesDirectly")
    public static native boolean accessInstanceVariablesDirectly();

    /**
     * An array of previously-selected accessories for this application.
     * 
     * To monitor for changes in this list, use your event handler to watch for the events
     * ``ASAccessoryEventType/accessoryAdded``, ``ASAccessoryEventType/accessoryChanged``, and
     * ``ASAccessoryEventType/accessoryRemoved``.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("accessories")
    @NotNull
    public native NSArray<? extends ASAccessory> accessories();

    /**
     * Activate the session and start delivering events to an event handler.
     * - Parameters:
     * - queue: The dispatch the session uses to deliver events to `eventHandler`.
     * - eventHandler: A closure or block that receives events generated by the session. Each callback to the event
     * handler provides an ``ASAccessoryEvent`` as a parameter, and expects no return value.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("activateWithQueue:eventHandler:")
    public native void activateWithQueueEventHandler(@NotNull dispatch_queue_t queue,
            @ObjCBlock(name = "call_activateWithQueueEventHandler") @NotNull Block_activateWithQueueEventHandler eventHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_activateWithQueueEventHandler {
        @Generated
        void call_activateWithQueueEventHandler(@NotNull ASAccessoryEvent event);
    }

    @Generated
    @Owned
    @Selector("alloc")
    public static native ASAccessorySession alloc();

    @Generated
    @Owned
    @Selector("allocWithZone:")
    public static native ASAccessorySession allocWithZone(VoidPtr zone);

    @Generated
    @Selector("automaticallyNotifiesObserversForKey:")
    public static native boolean automaticallyNotifiesObserversForKey(@NotNull String key);

    @Generated
    @Selector("cancelPreviousPerformRequestsWithTarget:")
    public static native void cancelPreviousPerformRequestsWithTarget(
            @Mapped(ObjCObjectMapper.class) @NotNull Object aTarget);

    @Generated
    @Selector("cancelPreviousPerformRequestsWithTarget:selector:object:")
    public static native void cancelPreviousPerformRequestsWithTargetSelectorObject(
            @Mapped(ObjCObjectMapper.class) @NotNull Object aTarget, @NotNull SEL aSelector,
            @Mapped(ObjCObjectMapper.class) @Nullable Object anArgument);

    @Generated
    @Selector("classFallbacksForKeyedArchiver")
    @NotNull
    public static native NSArray<String> classFallbacksForKeyedArchiver();

    @Generated
    @Selector("classForKeyedUnarchiver")
    @NotNull
    public static native Class classForKeyedUnarchiver();

    @Generated
    @Selector("debugDescription")
    public static native String debugDescription_static();

    @Generated
    @Selector("description")
    public static native String description_static();

    /**
     * End authorization of a partially-configured accessory as a failure.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("failAuthorization:completionHandler:")
    public native void failAuthorizationCompletionHandler(@NotNull ASAccessory accessory,
            @ObjCBlock(name = "call_failAuthorizationCompletionHandler") @NotNull Block_failAuthorizationCompletionHandler completionHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_failAuthorizationCompletionHandler {
        @Generated
        void call_failAuthorizationCompletionHandler(@Nullable NSError error);
    }

    /**
     * Finish authorization of a partially-setup accessory.
     * 
     * Use this method in scenarios where an accessory has multiple wireless interfaces. For example, when an accessory
     * has both Bluetooth and Wi-Fi, and your descriptor may only provides an SSID prefix. In this case, the Bluetooth
     * interface onboards first and your app needs to then finish authorization with the full SSID.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("finishAuthorization:settings:completionHandler:")
    public native void finishAuthorizationSettingsCompletionHandler(@NotNull ASAccessory accessory,
            @NotNull ASAccessorySettings settings,
            @ObjCBlock(name = "call_finishAuthorizationSettingsCompletionHandler") @NotNull Block_finishAuthorizationSettingsCompletionHandler completionHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_finishAuthorizationSettingsCompletionHandler {
        @Generated
        void call_finishAuthorizationSettingsCompletionHandler(@Nullable NSError error);
    }

    @Generated
    @Selector("hash")
    @NUInt
    public static native long hash_static();

    @Generated
    @Selector("init")
    public native ASAccessorySession init();

    @Generated
    @Selector("instanceMethodForSelector:")
    @FunctionPtr(name = "call_instanceMethodForSelector_ret")
    public static native NSObject.Function_instanceMethodForSelector_ret instanceMethodForSelector(SEL aSelector);

    @Generated
    @Selector("instanceMethodSignatureForSelector:")
    public static native NSMethodSignature instanceMethodSignatureForSelector(SEL aSelector);

    @Generated
    @Selector("instancesRespondToSelector:")
    public static native boolean instancesRespondToSelector(SEL aSelector);

    /**
     * Invalidate the session by stopping any operations.
     * 
     * This call breaks any retain cycles. The session is unusable after calling `invalidate`.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("invalidate")
    public native void invalidate();

    @Generated
    @Selector("isSubclassOfClass:")
    public static native boolean isSubclassOfClass(Class aClass);

    @Generated
    @Selector("keyPathsForValuesAffectingValueForKey:")
    @NotNull
    public static native NSSet<String> keyPathsForValuesAffectingValueForKey(@NotNull String key);

    @Generated
    @Owned
    @Selector("new")
    public static native ASAccessorySession new_objc();

    /**
     * Removes an accessory.
     * 
     * - Parameters:
     * - accessory: The accessory to remove.
     * - completionHandler: A block or closure that executes after the remove operation completes. The completion
     * handler receives an <doc://com.apple.documentation/documentation/Foundation/NSError> instance if the remove
     * operation encounters an error.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("removeAccessory:completionHandler:")
    public native void removeAccessoryCompletionHandler(@NotNull ASAccessory accessory,
            @ObjCBlock(name = "call_removeAccessoryCompletionHandler") @NotNull Block_removeAccessoryCompletionHandler completionHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_removeAccessoryCompletionHandler {
        @Generated
        void call_removeAccessoryCompletionHandler(@Nullable NSError error);
    }

    /**
     * Displays a view to rename an accessory.
     * 
     * To rename a Wi-Fi SSID with this method, use the option ``ASAccessory/RenameOptions/ssid``.
     * 
     * - Parameters:
     * - accessory: The accessory to rename.
     * - renameOptions: Options that affect the behavior of the rename operation.
     * - completionHandler: A block or closure that executes after the rename operation completes. The completion
     * handler receives an <doc://com.apple.documentation/documentation/Foundation/NSError> instance if the rename
     * operation encounters an error.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("renameAccessory:options:completionHandler:")
    public native void renameAccessoryOptionsCompletionHandler(@NotNull ASAccessory accessory,
            @NUInt long renameOptions,
            @ObjCBlock(name = "call_renameAccessoryOptionsCompletionHandler") @NotNull Block_renameAccessoryOptionsCompletionHandler completionHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_renameAccessoryOptionsCompletionHandler {
        @Generated
        void call_renameAccessoryOptionsCompletionHandler(@Nullable NSError error);
    }

    @Generated
    @Selector("resolveClassMethod:")
    public static native boolean resolveClassMethod(SEL sel);

    @Generated
    @Selector("resolveInstanceMethod:")
    public static native boolean resolveInstanceMethod(SEL sel);

    @Generated
    @Selector("setVersion:")
    public static native void setVersion_static(@NInt long aVersion);

    /**
     * Present a picker that shows discovered accessories matching an array of display items.
     * 
     * The session's event handler receives events when this picker displays and dismisses, as well as when the person
     * using the app picks an accessory.
     * 
     * To migrate previously-configured accessories to AccessorySetupKit, add instances of ``ASMigrationDisplayItem`` to
     * the `displayItems` array.
     * - Parameters:
     * - displayItems: An array of ``ASPickerDisplayItem`` instances describing accessories your app can set up. The
     * picker displays only discovered accessories that match the properties of items in this array.
     * - completionHandler: A block or closure that the picker calls when it completes the operation. The completion
     * handler receives an <doc://com.apple.documentation/documentation/Foundation/NSError> instance if the picker
     * encounters an error.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("showPickerForDisplayItems:completionHandler:")
    public native void showPickerForDisplayItemsCompletionHandler(
            @NotNull NSArray<? extends ASPickerDisplayItem> displayItems,
            @ObjCBlock(name = "call_showPickerForDisplayItemsCompletionHandler") @NotNull Block_showPickerForDisplayItemsCompletionHandler completionHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_showPickerForDisplayItemsCompletionHandler {
        @Generated
        void call_showPickerForDisplayItemsCompletionHandler(@Nullable NSError error);
    }

    /**
     * Present a picker that shows accessories managed by a Device Discovery Extension in your app.
     * 
     * Use this method when your app includes a <doc://com.apple.documentation/documentation/devicediscoveryextension>
     * for its supported accessories. If your app doesn't use DDE, call ``showPickerForDisplayItems:completionHandler:``
     * with an array of ``ASPickerDisplayItem-c.class`` instances instead.
     * 
     * The session's event handler receives events when this picker displays and dismisses, as well as when the person
     * using the app picks an accessory.
     * 
     * - Parameters:
     * - completionHandler: A block or closure that the picker calls when it completes the operation. The completion
     * handler receives an <doc://com.apple.documentation/documentation/Foundation/NSError> instance if the picker
     * encounters an error.
     * 
     * API-Since: 18.0
     */
    @Generated
    @Selector("showPickerWithCompletionHandler:")
    public native void showPickerWithCompletionHandler(
            @ObjCBlock(name = "call_showPickerWithCompletionHandler") @NotNull Block_showPickerWithCompletionHandler completionHandler);

    @Runtime(ObjCRuntime.class)
    @Generated
    public interface Block_showPickerWithCompletionHandler {
        @Generated
        void call_showPickerWithCompletionHandler(@Nullable NSError error);
    }

    @Generated
    @Selector("superclass")
    public static native Class superclass_static();

    @Generated
    @Deprecated
    @Selector("useStoredAccessor")
    public static native boolean useStoredAccessor();

    @Generated
    @Selector("version")
    @NInt
    public static native long version_static();
}