package apple.corelocation.enums;

import org.moe.natj.general.ann.Generated;
import org.moe.natj.general.ann.NInt;

/**
 * CLLiveUpdateConfiguration
 * 
 * Discussion:
 * Specifies the types of locations being generated by
 * -[CLLocationUpdater liveUpdaterWithConfiguration:queue:handler:] or
 * -[CLLocationUpdater liveUpdaterWithQueue:handler:]
 */
@Generated
public final class CLLiveUpdateConfiguration {
    @Generated
    private CLLiveUpdateConfiguration() {
    }

    /**
     * Default configuration
     */
    @Generated @NInt public static final long Default = 0x0000000000000000L;
    /**
     * Configuration tuned for automotive navigation use cases
     */
    @Generated @NInt public static final long AutomotiveNavigation = 0x0000000000000001L;
    /**
     * Configuration tuned for other navigation use cases
     */
    @Generated @NInt public static final long OtherNavigation = 0x0000000000000002L;
    /**
     * Configuration tuned for fitness use cases
     */
    @Generated @NInt public static final long Fitness = 0x0000000000000003L;
    /**
     * Configuration tuned for airborne use cases
     */
    @Generated @NInt public static final long Airborne = 0x0000000000000004L;
}