package apple.avfaudio.enums;

import org.moe.natj.general.ann.Generated;
import org.moe.natj.general.ann.NUInt;

/**
 * API-Since: 17.0
 */
@Generated
public final class AVSpeechSynthesisVoiceTraits {
    @Generated
    private AVSpeechSynthesisVoiceTraits() {
    }

    /**
     * API-Since: 17.0
     */
    @Generated @NUInt public static final long None = 0x0000000000000000L;
    /**
     * The voice is generally for novelty purposes, for example a character's voice in a game.
     * 
     * API-Since: 17.0
     */
    @Generated @NUInt public static final long IsNoveltyVoice = 0x0000000000000001L;
    /**
     * The voice is was generated by, and belongs to the user. Voices with this trait will only be avilable when
     * AVSpeechSynthesizer.personalVoiceAuthorizationStatus is
     * AVSpeechSynthesisPersonalVoiceAuthorizationStatusAuthorized
     * 
     * API-Since: 17.0
     */
    @Generated @NUInt public static final long IsPersonalVoice = 0x0000000000000002L;
}