#!/bin/bash

#
# Copyright (C) 2014 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

realpath () {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

cd "$(dirname "$(realpath "$0")")";

PRIVATE_SDK=$PWD/build/private/moe-sdk
PUBLIC_SDK=$PWD/build/private/moe-sdk-public

cd build/private

if [ -d "$PUBLIC_SDK" ]; then
	rm -R "$PUBLIC_SDK"
fi
mkdir "$PUBLIC_SDK"

cd "$PUBLIC_SDK"
cp "$PRIVATE_SDK/EULA.TXT" ./

mkdir -p main
cp -R "$PRIVATE_SDK/main/java" ./main
if [ -f "main/java/moe-ios-sources.jar" ]; then
	rm "main/java/moe-ios-sources.jar"
fi

mkdir -p main/native/Release-iphoneos
cp -R "$PRIVATE_SDK/main/native/Release-iphoneos/moeSDK.framework" ./main/native/Release-iphoneos
mkdir -p main/native/Release-iphonesimulator
cp -R "$PRIVATE_SDK/main/native/Release-iphonesimulator/moeSDK.framework" ./main/native/Release-iphonesimulator

mkdir -p platform-tools
cp "$PRIVATE_SDK/platform-tools/dex2oat" ./platform-tools/dex2oat
cp "$PRIVATE_SDK/platform-tools/dx" ./platform-tools/dx
cp -R "$PRIVATE_SDK/platform-tools/lib" ./platform-tools/lib

cp "$PRIVATE_SDK/preloaded-classes" ./
cp -R "$PRIVATE_SDK/script" ./
cp -R "$PRIVATE_SDK/test" ./
if [ -f "test/java/moe-ios-test-sources.jar" ]; then
	rm "test/java/moe-ios-test-sources.jar"
fi
