/* Fallback implementations autogenerated by mx_substratevm.py */

#include <stdlib.h>
#include <jni.h>

JNIEXPORT jobject JNICALL JVM_AddModuleExports(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_AddModuleExports called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_AddModuleExportsToAll(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_AddModuleExportsToAll called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_AddModuleExportsToAllUnnamed(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_AddModuleExportsToAllUnnamed called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_AddReadsModule(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_AddReadsModule called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_AreNestMates(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_AreNestMates called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ArrayCopy(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ArrayCopy called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_AssertionStatusDirectives(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_AssertionStatusDirectives called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_CallStackWalk(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_CallStackWalk called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_Clone(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_Clone called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetClassAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetClassAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetClassAtIfLoaded(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetClassAtIfLoaded called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetClassRefIndexAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetClassRefIndexAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetDoubleAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetDoubleAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetFieldAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetFieldAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetFieldAtIfLoaded(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetFieldAtIfLoaded called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetFloatAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetFloatAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetIntAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetIntAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetLongAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetLongAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetMemberRefInfoAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetMemberRefInfoAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetMethodAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetMethodAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetMethodAtIfLoaded(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetMethodAtIfLoaded called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetNameAndTypeRefIndexAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetNameAndTypeRefIndexAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetNameAndTypeRefInfoAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetNameAndTypeRefInfoAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetSize(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetSize called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetStringAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetStringAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetTagAt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetTagAt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_ConstantPoolGetUTF8At(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ConstantPoolGetUTF8At called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_CountStackFrames(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_CountStackFrames called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_CurrentThread(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_CurrentThread called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_DefineClassWithSource(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_DefineClassWithSource called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_DefineModule(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_DefineModule called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_DesiredAssertionStatus(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_DesiredAssertionStatus called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_DumpThreads(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_DumpThreads called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_FillInStackTrace(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_FillInStackTrace called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_FindClassFromBootLoader(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_FindClassFromBootLoader called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_FindClassFromCaller(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_FindClassFromCaller called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_FindClassFromClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_FindClassFromClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_FindLoadedClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_FindLoadedClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_FindPrimitiveClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_FindPrimitiveClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_FindSignal() {
    fprintf(stderr, "JVM_FindSignal called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_FreeMemory() {
    fprintf(stderr, "JVM_FreeMemory called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_GC() {
    fprintf(stderr, "JVM_GC called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_GetAllThreads(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetAllThreads called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetAndClearReferencePendingList(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetAndClearReferencePendingList called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetArrayElement(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetArrayElement called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetArrayLength(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetArrayLength called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPClassNameUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPClassNameUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPFieldClassNameUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPFieldClassNameUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPFieldModifiers(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPFieldModifiers called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPFieldSignatureUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPFieldSignatureUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPMethodClassNameUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPMethodClassNameUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPMethodModifiers(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPMethodModifiers called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPMethodNameUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPMethodNameUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCPMethodSignatureUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCPMethodSignatureUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetCallerClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetCallerClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassAccessFlags(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassAccessFlags called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassAnnotations(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassAnnotations called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassCPEntriesCount(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassCPEntriesCount called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassCPTypes(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassCPTypes called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassConstantPool(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassConstantPool called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassContext(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassContext called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassDeclaredConstructors(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassDeclaredConstructors called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassDeclaredFields(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassDeclaredFields called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassDeclaredMethods(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassDeclaredMethods called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassFieldsCount(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassFieldsCount called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassInterfaces(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassInterfaces called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassMethodsCount(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassMethodsCount called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassModifiers(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassModifiers called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassNameUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassNameUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassSignature(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassSignature called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassSigners(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassSigners called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetClassTypeAnnotations(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetClassTypeAnnotations called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetDeclaredClasses(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetDeclaredClasses called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetDeclaringClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetDeclaringClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetEnclosingMethodInfo(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetEnclosingMethodInfo called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetFieldIxModifiers(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetFieldIxModifiers called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetFieldTypeAnnotations(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetFieldTypeAnnotations called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetInheritedAccessControlContext(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetInheritedAccessControlContext called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_GetManagement() {
    fprintf(stderr, "JVM_GetManagement called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxArgsSize(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxArgsSize called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxByteCode(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxByteCode called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxByteCodeLength(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxByteCodeLength called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxExceptionIndexes(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxExceptionIndexes called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxExceptionTableEntry(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxExceptionTableEntry called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxExceptionTableLength(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxExceptionTableLength called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxExceptionsCount(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxExceptionsCount called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxLocalsCount(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxLocalsCount called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxMaxStack(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxMaxStack called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxModifiers(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxModifiers called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxNameUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxNameUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodIxSignatureUTF(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodIxSignatureUTF called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodParameters(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodParameters called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetMethodTypeAnnotations(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetMethodTypeAnnotations called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetNestHost(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetNestHost called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetNestMembers(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetNestMembers called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetPrimitiveArrayElement(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetPrimitiveArrayElement called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetProtectionDomain(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetProtectionDomain called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetSimpleBinaryName(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetSimpleBinaryName called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetStackAccessControlContext(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetStackAccessControlContext called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetSystemPackage(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetSystemPackage called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetSystemPackages(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetSystemPackages called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_GetVmArguments(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetVmArguments called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_HasReferencePendingList(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_HasReferencePendingList called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_HoldsLock(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_HoldsLock called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IHashCode(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IHashCode called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InitAgentProperties(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InitAgentProperties called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InitClassName(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InitClassName called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InitProperties(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InitProperties called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InitStackTraceElement(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InitStackTraceElement called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InitStackTraceElementArray(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InitStackTraceElementArray called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InitializeFromArchive(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InitializeFromArchive called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InternString(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InternString called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_Interrupt(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_Interrupt called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_InvokeMethod(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_InvokeMethod called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsArrayClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsArrayClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsConstructorIx(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsConstructorIx called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsInterface(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsInterface called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsInterrupted(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsInterrupted called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsPrimitiveClass(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsPrimitiveClass called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsSameClassPackage(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsSameClassPackage called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_IsSupportedJNIVersion() {
    fprintf(stderr, "JVM_IsSupportedJNIVersion called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_IsThreadAlive(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsThreadAlive called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_IsVMGeneratedMethodIx(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsVMGeneratedMethodIx called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_LatestUserDefinedLoader(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_LatestUserDefinedLoader called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_LoadLibrary() {
    fprintf(stderr, "JVM_LoadLibrary called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_MaxMemory() {
    fprintf(stderr, "JVM_MaxMemory called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_MaxObjectInspectionAge() {
    fprintf(stderr, "JVM_MaxObjectInspectionAge called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_MonitorNotify(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_MonitorNotify called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_MonitorNotifyAll(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_MonitorNotifyAll called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_MonitorWait(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_MonitorWait called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_MoreStackWalk(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_MoreStackWalk called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_NativePath() {
    fprintf(stderr, "JVM_NativePath called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_NewArray(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_NewArray called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_NewInstanceFromConstructor(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_NewInstanceFromConstructor called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_NewMultiArray(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_NewMultiArray called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_RaiseSignal() {
    fprintf(stderr, "JVM_RaiseSignal called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_RawMonitorCreate() {
    fprintf(stderr, "JVM_RawMonitorCreate called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_RawMonitorDestroy() {
    fprintf(stderr, "JVM_RawMonitorDestroy called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_RawMonitorEnter() {
    fprintf(stderr, "JVM_RawMonitorEnter called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_RawMonitorExit() {
    fprintf(stderr, "JVM_RawMonitorExit called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_RegisterSignal() {
    fprintf(stderr, "JVM_RegisterSignal called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_ReleaseUTF() {
    fprintf(stderr, "JVM_ReleaseUTF called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_ResumeThread(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_ResumeThread called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_SetArrayElement(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SetArrayElement called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_SetBootLoaderUnnamedModule(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SetBootLoaderUnnamedModule called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_SetClassSigners(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SetClassSigners called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_SetNativeThreadName(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SetNativeThreadName called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_SetPrimitiveArrayElement(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SetPrimitiveArrayElement called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_SetThreadPriority(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SetThreadPriority called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_Sleep(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_Sleep called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_StartThread(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_StartThread called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_StopThread(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_StopThread called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_SupportsCX8() {
    fprintf(stderr, "JVM_SupportsCX8 called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_SuspendThread(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_SuspendThread called:  Unimplemented");
    return NULL;
}

JNIEXPORT void JNICALL JVM_TotalMemory() {
    fprintf(stderr, "JVM_TotalMemory called:  Unimplemented\n");
    abort();
}

JNIEXPORT void JNICALL JVM_UnloadLibrary() {
    fprintf(stderr, "JVM_UnloadLibrary called:  Unimplemented\n");
    abort();
}

JNIEXPORT jobject JNICALL JVM_WaitForReferencePendingList(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_WaitForReferencePendingList called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_Yield(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_Yield called:  Unimplemented");
    return NULL;
}

JNIEXPORT jobject JNICALL JVM_DefineArchivedModules(JNIEnv *env, jobject platform_loader, jobject system_loader) {
    (*env)->FatalError(env, "JVM_DefineArchivedModules called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_DumpClassListToFile(JNIEnv *env, jstring listFileName) {
    (*env)->FatalError(env, "JVM_DumpClassListToFile called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_DumpDynamicArchive(JNIEnv *env, jstring archiveName) {
    (*env)->FatalError(env, "JVM_DumpDynamicArchive called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_GetExtendedNPEMessage(JNIEnv *env, jthrowable throwable) {
    (*env)->FatalError(env, "JVM_GetExtendedNPEMessage called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_GetPermittedSubclasses(JNIEnv *env, jclass current) {
    (*env)->FatalError(env, "JVM_GetPermittedSubclasses called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_GetProperties(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_GetProperties called:  Unimplemented");
    return NULL;
}
JNIEXPORT void JNICALL JVM_GetRandomSeedForDumping() {
    fprintf(stderr, "JVM_GetRandomSeedForDumping called:  Unimplemented\n");
    abort();
}
JNIEXPORT jobject JNICALL JVM_GetRecordComponents(JNIEnv *env, jclass ofClass) {
    (*env)->FatalError(env, "JVM_GetRecordComponents called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_IsCDSDumpingEnabled(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsCDSDumpingEnabled called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_IsDumpingClassList(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsDumpingClassList called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_IsHiddenClass(JNIEnv *env, jclass cls) {
    (*env)->FatalError(env, "JVM_IsHiddenClass called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_IsRecord(JNIEnv *env, jclass cls) {
    (*env)->FatalError(env, "JVM_IsRecord called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_IsSharingEnabled(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_IsSharingEnabled called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_LogLambdaFormInvoker(JNIEnv *env, jstring line) {
    (*env)->FatalError(env, "JVM_LogLambdaFormInvoker called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_LookupDefineClass(JNIEnv *env, jclass lookup, const char *name, const jbyte *buf,
                                                jsize len, jobject pd, jboolean initialize, int flags, jobject classData) {
    (*env)->FatalError(env, "JVM_LookupDefineClass called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_LookupLambdaProxyClassFromArchive(JNIEnv *env) {
    (*env)->FatalError(env, "JVM_LookupLambdaProxyClassFromArchive called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_PhantomReferenceRefersTo(JNIEnv *env,
                                                       jclass caller,
                                                       jstring interfaceMethodName,
                                                       jobject factoryType,
                                                       jobject interfaceMethodType,
                                                       jobject implementationMember,
                                                       jobject dynamicMethodType) {
    (*env)->FatalError(env, "JVM_PhantomReferenceRefersTo called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_ReferenceClear(JNIEnv *env, jobject ref) {
    (*env)->FatalError(env, "JVM_ReferenceClear called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_ReferenceRefersTo(JNIEnv *env, jobject ref, jobject o) {
    (*env)->FatalError(env, "JVM_ReferenceRefersTo called:  Unimplemented");
    return NULL;
}
JNIEXPORT jobject JNICALL JVM_RegisterLambdaProxyClassForArchiving(JNIEnv *env,
                                                                   jclass caller,
                                                                   jstring interfaceMethodName,
                                                                   jobject factoryType,
                                                                   jobject interfaceMethodType,
                                                                   jobject implementationMember,
                                                                   jobject dynamicMethodType,
                                                                   jclass lambdaProxyClass) {
    (*env)->FatalError(env, "JVM_RegisterLambdaProxyClassForArchiving called:  Unimplemented");
    return NULL;
}

