import org.moe.prebuilts.XcodeBuild
import org.moe.prebuilts.Script

apply plugin: 'base'

def graalDeps = [
        projects: [
                ':moe.apple:moe.core.native:svm.graal@libjvm',
                ':moe.apple:moe.core.native:svm.openjdk@libjava',
        ]
]

def createJDWPJarBuild(String arch) {
    return tasks.register("build_jdwp_${arch}_jar", Script) {
        def baseCapPath = rootProject.file("../tools/moe.tools.substrate/src/main/resources/")
        def platform = arch == "arm64" ? "IOS_AARCH64" : "IOS_AMD64"
        def cAbi = arch == "arm64" ? "MAC_OS_AARCH_64" : "SYS_V"
        def buildPath = file("build/jdwpBuild$arch")

        dependsOn(graalDistTask)
        inputs.dir(graalDist)
        inputs.dir(baseCapPath)

        rawWorkDir "$buildPath"
        exec "rm", "-rf", file(workDir).absolutePath

        mkdir file(workDir).absolutePath

        exec file("$graalDist/bin/native-image").absolutePath,
                "-H:+SharedLibrary",
                "-H:-SpawnIsolates",
                "-H:PageSize=16384",
                "-H:+ExitAfterRelocatableImageWrite",
                "-H:TempDirectory=${workDir}",
                "-H:+UseCAPCache",
                "-H:CAPCacheDir=${file("$baseCapPath/cap_$arch/")}",
                "--no-server",
                "-Dsvm.targetName=iOS",
                "-Dsvm.targetArch=${arch}",
                "-Dsvm.platform=org.graalvm.nativeimage.Platform\$$platform",
                "-Djdk.internal.foreign.CABI=$cAbi",

                "--no-fallback",
                "-H:+UnlockExperimentalVMOptions",
                "-H:+AssertInitializationSpecifiedForAllClasses",
                "-H:+EnforceMaxRuntimeCompileMethods",
                "-H:+VerifyRuntimeCompilationFrameStates",
                "-H:+GuaranteeSubstrateTypesLinked",
                "-H:-UnlockExperimentalVMOptions",
                "--link-at-build-time",
                "--shared",
                "-H:+UnlockExperimentalVMOptions",
                "-H:+IncludeDebugHelperMethods",
                "-H:-DeleteLocalSymbols",
                "-H:+PreserveFramePointer",
                "--features=com.oracle.svm.jdwp.server.ServerJDWPFeature",

                "--add-exports", "java.base/jdk.internal.misc=com.oracle.svm.jdwp.server",
                "--add-exports", "jdk.internal.vm.ci/jdk.vm.ci.meta=com.oracle.svm.jdwp.server",

                "-o", "svmjdwp",
                "--module-path", file("$graalDist/lib/graalvm/svm-jdwp-server.jar").absolutePath

        doLast {
            def resultDir = buildPath.listFiles().find { it.name.startsWith("SVM-") }
            copy {
                from(resultDir) {
                    include "svmjdwp.o"
                    rename "svmjdwp.o", "svmjdwp_${arch}.o"
                }

                into "build/jdwpBuild"
            }
        }
    }
}

def arm64Task = createJDWPJarBuild("arm64")
def x86_64Task = createJDWPJarBuild("x86_64")


tasks.register("build_jdwp_jar") {
    dependsOn arm64Task
    dependsOn x86_64Task
}


XcodeBuild.createTask(project, "svmjdwp", "ios", "iphoneos", "Debug", graalDeps)
        .cond_buildopt(buildfilter.ios.archs, "ARCHS")
        .cond_buildopt(buildfilter.ios.archs != null, "ONLY_ACTIVE_ARCH", "YES")
        .dependsOn(build_jdwp_jar)
XcodeBuild.createTask(project, "svmjdwp", "ios", "iphoneos", "Release", graalDeps)
        .cond_buildopt(buildfilter.ios.archs, "ARCHS")
        .cond_buildopt(buildfilter.ios.archs != null, "ONLY_ACTIVE_ARCH", "YES")
        .dependsOn(build_jdwp_jar)
XcodeBuild.createTask(project, "svmjdwp", "ios", "iphonesimulator", "Debug", graalDeps)
        .cond_buildopt(buildfilter.ios.archs, "ARCHS")
        .cond_buildopt(buildfilter.ios.archs != null, "ONLY_ACTIVE_ARCH", "YES")
        .dependsOn(build_jdwp_jar)
XcodeBuild.createTask(project, "svmjdwp", "ios", "iphonesimulator", "Release", graalDeps)
        .cond_buildopt(buildfilter.ios.archs, "ARCHS")
        .cond_buildopt(buildfilter.ios.archs != null, "ONLY_ACTIVE_ARCH", "YES")
        .dependsOn(build_jdwp_jar)

tasks.build {
    def configs = ['Release']
    if (buildfilter.ios.config)
        configs = [buildfilter.ios.config]

    def sdks = ['iphoneos', 'iphonesimulator']
    if (buildfilter.ios.sdk)
        sdks = [buildfilter.ios.sdk]

    for (config in configs)
        for (sdk in sdks)
            dependsOn "build_svmjdwp_ios_${sdk}_${config.toLowerCase()}"
}
