/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import org.moe.prebuilts.XcodeBuild

plugins {
    id 'org.moe.buildtools'
}

apply plugin: 'maven-publish'

ext {
    nativeOutputs = []
}

def useAsan = providers.gradleProperty("moe.use.addresssanitizer").isPresent()
def xcodeProjectDir = file("natj.xcodeproj")

def registerNativeTarget = { String cfg, String sdkArg, String tgt ->
    def productDest = "$buildDir/xcode/${cfg}"
    if (tgt == 'natj') {
        project.nativeOutputs.add("${productDest}/libnatj.dylib")
    }
    return tasks.register("build_${tgt}_${cfg}_${sdkArg}", XcodeBuild) { XcodeBuild t ->
        t.xcodeProject.set(xcodeProjectDir)
        t.configuration = cfg
        t.target = tgt
        t.sdk = sdkArg
        if (useAsan) {
            t.extraArgs('-enableAddressSanitizer', 'YES')
        }
        t.dependsOn ":prebuild_libffi_macos"
        t.inputs.dir rootProject.file('src')
        t.inputs.dir xcodeProjectDir
        t.outputs.upToDateWhen { false }
        if (tgt == 'natj') {
            t.outputs.file "${productDest}/libnatj.dylib"
        } else {
            t.dependsOn "build_natj_${cfg}_${sdkArg}"
        }
    }
}

// Create build task
task build {
    dependsOn registerNativeTarget("Release", "macosx", "natj")
    dependsOn registerNativeTarget("Debug", "macosx", "natj")
}

// Create test tasks
task build_TestClasses_macosx {
    dependsOn registerNativeTarget("Release", "macosx", "TestClasses")
    dependsOn registerNativeTarget("Debug", "macosx", "TestClasses")
}

task build_TestClassesC_macosx {
    dependsOn registerNativeTarget("Release", "macosx", "TestClassesC")
    dependsOn registerNativeTarget("Debug", "macosx", "TestClassesC")
}

task build_TestClassesCxx_macosx {
    dependsOn registerNativeTarget("Release", "macosx", "TestClassesCxx")
    dependsOn registerNativeTarget("Debug", "macosx", "TestClassesCxx")
}

task build_TestClassesObjC_macosx {
    dependsOn registerNativeTarget("Release", "macosx", "TestClassesObjC")
    dependsOn registerNativeTarget("Debug", "macosx", "TestClassesObjC")
}

task buildAll {
    dependsOn build, build_TestClasses_macosx, build_TestClassesC_macosx, build_TestClassesCxx_macosx, build_TestClassesObjC_macosx
}

// Create clean task
task clean {
    doLast {
        delete buildDir
    }
}

// Setup publishing
tasks.publish.dependsOn build
publishing {
    publications {
        mavenNative(MavenPublication) {
            artifactId 'natj-mac'

            for (o in nativeOutputs) {
                artifact source: o, extension: 'dylib', classifier: new File(o).getParentFile().getName()
            }
        }
    }
}
