/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
plugins {
    id "com.diffplug.spotless" version "7.0.2"
}

apply plugin: 'java'

def JvmVersionMeets(version) {
    def currentJvm = org.gradle.internal.jvm.Jvm.current()
    return version <= Integer.parseInt(currentJvm.javaVersion.majorVersion)
}

java {
    sourceCompatibility = "1.8"
    targetCompatibility = "1.8"
}

tasks.withType(JavaCompile).configureEach {
    options.fork = true
    options.forkOptions.memoryMaximumSize = '6g'
}

tasks.classes.dependsOn ':ext_natj_ios'

configurations {
    natJGen
}

dependencies {
    implementation "org.moe:natj"
    compileOnly project(':moe.apple:moe.core.java')
    compileOnly 'org.jetbrains:annotations:23.0.0'
    natJGen "org.multi-os-engine:moe.generator.natjgen"
}

tasks.register('updateNatJGenConfig', Exec) {
    commandLine = ["python3", "platform_natjgen_updater.py"]
}

tasks.register('generateBindings', JavaExec) {
    finalizedBy spotlessApply

    def tempFile = file("build/generate_bindings.log")
    tempFile.parentFile.mkdirs()

    classpath configurations.natJGen
    mainClass = "org.moe.natjgen.Main"
    args = [file("../").absolutePath, "moe.platform.ios", file("platform.natjgen").absolutePath]
    systemProperty "java.library.path", rootProject.external.llvm.jnipath.absolutePath +
            File.pathSeparator + rootProject.external.natj.jnipath.absolutePath

    doFirst {
        standardOutput = new FileOutputStream(tempFile)
    }
}

tasks.register('removeOutdatedBindings', Exec) {
    commandLine = ["python3", "remove_deprecated_files.py", file("build/generate_bindings.log").absolutePath]
}

tasks.register('applyManualBindingFixes', Exec) {
    commandLine = ["git", "apply", "fix_manual_binding_changes.patch"]
}

tasks.javadoc {
    if (JvmVersionMeets(8)) {
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addBooleanOption("-allow-script-in-comments", true)
    }
}

tasks.register('javadocJar', Jar) {
    dependsOn javadoc
    archiveBaseName = 'moe-ios'
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

tasks.register('sourceJar', Jar) {
    archiveBaseName = 'moe-ios'
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
    from(rootProject.external.natj.sources) {
        include '**/*.java'
    }
}

jar {
    archiveBaseName = 'moe-ios'
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
}

spotless {
    java {
        target("src/main/java/apple/**")
        removeUnusedImports()
        eclipse().configFile('Eclipse_Adjusted_NatJGen.xml')
    }
}
