//
//  OpenGLES_ES2_Defines.h
//

#ifndef __OpenGLES_ES2_Defines_H
#define __OpenGLES_ES2_Defines_H

#include <OpenGLES/ES2/gl.h>
#include <OpenGLES/ES2/glext.h>

enum _ES2_ {
    
    /*************************************************************/
    /*                            gl.h                           */
    /*************************************************************/
    
    /* OpenGL ES core versions */
    _ES2_GL_ES_VERSION_2_0 = GL_ES_VERSION_2_0,
    
    /* ClearBufferMask */
    _ES2_GL_DEPTH_BUFFER_BIT = GL_DEPTH_BUFFER_BIT,
    _ES2_GL_STENCIL_BUFFER_BIT = GL_STENCIL_BUFFER_BIT,
    _ES2_GL_COLOR_BUFFER_BIT = GL_COLOR_BUFFER_BIT,
    
    /* Boolean */
    _ES2_GL_FALSE = GL_FALSE,
    _ES2_GL_TRUE = GL_TRUE,
    
    /* BeginMode */
    _ES2_GL_POINTS = GL_POINTS,
    _ES2_GL_LINES = GL_LINES,
    _ES2_GL_LINE_LOOP = GL_LINE_LOOP,
    _ES2_GL_LINE_STRIP = GL_LINE_STRIP,
    _ES2_GL_TRIANGLES = GL_TRIANGLES,
    _ES2_GL_TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
    _ES2_GL_TRIANGLE_FAN = GL_TRIANGLE_FAN,
    
    /* BlendingFactorDest */
    _ES2_GL_ZERO = GL_ZERO,
    _ES2_GL_ONE = GL_ONE,
    _ES2_GL_SRC_COLOR = GL_SRC_COLOR,
    _ES2_GL_ONE_MINUS_SRC_COLOR = GL_ONE_MINUS_SRC_COLOR,
    _ES2_GL_SRC_ALPHA = GL_SRC_ALPHA,
    _ES2_GL_ONE_MINUS_SRC_ALPHA = GL_ONE_MINUS_SRC_ALPHA,
    _ES2_GL_DST_ALPHA = GL_DST_ALPHA,
    _ES2_GL_ONE_MINUS_DST_ALPHA = GL_ONE_MINUS_DST_ALPHA,
    
    /* BlendingFactorSrc */
    /*      GL_ZERO */
    /*      GL_ONE */
    _ES2_GL_DST_COLOR = GL_DST_COLOR,
    _ES2_GL_ONE_MINUS_DST_COLOR = GL_ONE_MINUS_DST_COLOR,
    _ES2_GL_SRC_ALPHA_SATURATE = GL_SRC_ALPHA_SATURATE,
    /*      GL_SRC_ALPHA */
    /*      GL_ONE_MINUS_SRC_ALPHA */
    /*      GL_DST_ALPHA */
    /*      GL_ONE_MINUS_DST_ALPHA */
    
    /* BlendEquationSeparate */
    _ES2_GL_FUNC_ADD = GL_FUNC_ADD,
    _ES2_GL_BLEND_EQUATION = GL_BLEND_EQUATION,
    _ES2_GL_BLEND_EQUATION_RGB = GL_BLEND_EQUATION_RGB,    /* same as BLEND_EQUATION */
    _ES2_GL_BLEND_EQUATION_ALPHA = GL_BLEND_EQUATION_ALPHA,
    
    /* BlendSubtract */
    _ES2_GL_FUNC_SUBTRACT = GL_FUNC_SUBTRACT,
    _ES2_GL_FUNC_REVERSE_SUBTRACT = GL_FUNC_REVERSE_SUBTRACT,
    
    /* Separate Blend Functions */
    _ES2_GL_BLEND_DST_RGB = GL_BLEND_DST_RGB,
    _ES2_GL_BLEND_SRC_RGB = GL_BLEND_SRC_RGB,
    _ES2_GL_BLEND_DST_ALPHA = GL_BLEND_DST_ALPHA,
    _ES2_GL_BLEND_SRC_ALPHA = GL_BLEND_SRC_ALPHA,
    _ES2_GL_CONSTANT_COLOR = GL_CONSTANT_COLOR,
    _ES2_GL_ONE_MINUS_CONSTANT_COLOR = GL_ONE_MINUS_CONSTANT_COLOR,
    _ES2_GL_CONSTANT_ALPHA = GL_CONSTANT_ALPHA,
    _ES2_GL_ONE_MINUS_CONSTANT_ALPHA = GL_ONE_MINUS_CONSTANT_ALPHA,
    _ES2_GL_BLEND_COLOR = GL_BLEND_COLOR,
    
    /* Buffer Objects */
    _ES2_GL_ARRAY_BUFFER = GL_ARRAY_BUFFER,
    _ES2_GL_ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER,
    _ES2_GL_ARRAY_BUFFER_BINDING = GL_ARRAY_BUFFER_BINDING,
    _ES2_GL_ELEMENT_ARRAY_BUFFER_BINDING = GL_ELEMENT_ARRAY_BUFFER_BINDING,
    
    _ES2_GL_STREAM_DRAW = GL_STREAM_DRAW,
    _ES2_GL_STATIC_DRAW = GL_STATIC_DRAW,
    _ES2_GL_DYNAMIC_DRAW = GL_DYNAMIC_DRAW,
    
    _ES2_GL_BUFFER_SIZE = GL_BUFFER_SIZE,
    _ES2_GL_BUFFER_USAGE = GL_BUFFER_USAGE,
    
    _ES2_GL_CURRENT_VERTEX_ATTRIB = GL_CURRENT_VERTEX_ATTRIB,
    
    /* CullFaceMode */
    _ES2_GL_FRONT = GL_FRONT,
    _ES2_GL_BACK = GL_BACK,
    _ES2_GL_FRONT_AND_BACK = GL_FRONT_AND_BACK,
    
    /* DepthFunction */
    /*      GL_NEVER */
    /*      GL_LESS */
    /*      GL_EQUAL */
    /*      GL_LEQUAL */
    /*      GL_GREATER */
    /*      GL_NOTEQUAL */
    /*      GL_GEQUAL */
    /*      GL_ALWAYS */
    
    /* EnableCap */
    _ES2_GL_TEXTURE_2D = GL_TEXTURE_2D,
    _ES2_GL_CULL_FACE = GL_CULL_FACE,
    _ES2_GL_BLEND = GL_BLEND,
    _ES2_GL_DITHER = GL_DITHER,
    _ES2_GL_STENCIL_TEST = GL_STENCIL_TEST,
    _ES2_GL_DEPTH_TEST = GL_DEPTH_TEST,
    _ES2_GL_SCISSOR_TEST = GL_SCISSOR_TEST,
    _ES2_GL_POLYGON_OFFSET_FILL = GL_POLYGON_OFFSET_FILL,
    _ES2_GL_SAMPLE_ALPHA_TO_COVERAGE = GL_SAMPLE_ALPHA_TO_COVERAGE,
    _ES2_GL_SAMPLE_COVERAGE = GL_SAMPLE_COVERAGE,
    
    /* ErrorCode */
    _ES2_GL_NO_ERROR = GL_NO_ERROR,
    _ES2_GL_INVALID_ENUM = GL_INVALID_ENUM,
    _ES2_GL_INVALID_VALUE = GL_INVALID_VALUE,
    _ES2_GL_INVALID_OPERATION = GL_INVALID_OPERATION,
    _ES2_GL_OUT_OF_MEMORY = GL_OUT_OF_MEMORY,
    
    /* FrontFaceDirection */
    _ES2_GL_CW = GL_CW,
    _ES2_GL_CCW = GL_CCW,
    
    /* GetPName */
    _ES2_GL_LINE_WIDTH = GL_LINE_WIDTH,
    _ES2_GL_ALIASED_POINT_SIZE_RANGE = GL_ALIASED_POINT_SIZE_RANGE,
    _ES2_GL_ALIASED_LINE_WIDTH_RANGE = GL_ALIASED_LINE_WIDTH_RANGE,
    _ES2_GL_CULL_FACE_MODE = GL_CULL_FACE_MODE,
    _ES2_GL_FRONT_FACE = GL_FRONT_FACE,
    _ES2_GL_DEPTH_RANGE = GL_DEPTH_RANGE,
    _ES2_GL_DEPTH_WRITEMASK = GL_DEPTH_WRITEMASK,
    _ES2_GL_DEPTH_CLEAR_VALUE = GL_DEPTH_CLEAR_VALUE,
    _ES2_GL_DEPTH_FUNC = GL_DEPTH_FUNC,
    _ES2_GL_STENCIL_CLEAR_VALUE = GL_STENCIL_CLEAR_VALUE,
    _ES2_GL_STENCIL_FUNC = GL_STENCIL_FUNC,
    _ES2_GL_STENCIL_FAIL = GL_STENCIL_FAIL,
    _ES2_GL_STENCIL_PASS_DEPTH_FAIL = GL_STENCIL_PASS_DEPTH_FAIL,
    _ES2_GL_STENCIL_PASS_DEPTH_PASS = GL_STENCIL_PASS_DEPTH_PASS,
    _ES2_GL_STENCIL_REF = GL_STENCIL_REF,
    _ES2_GL_STENCIL_VALUE_MASK = GL_STENCIL_VALUE_MASK,
    _ES2_GL_STENCIL_WRITEMASK = GL_STENCIL_WRITEMASK,
    _ES2_GL_STENCIL_BACK_FUNC = GL_STENCIL_BACK_FUNC,
    _ES2_GL_STENCIL_BACK_FAIL = GL_STENCIL_BACK_FAIL,
    _ES2_GL_STENCIL_BACK_PASS_DEPTH_FAIL = GL_STENCIL_BACK_PASS_DEPTH_FAIL,
    _ES2_GL_STENCIL_BACK_PASS_DEPTH_PASS = GL_STENCIL_BACK_PASS_DEPTH_PASS,
    _ES2_GL_STENCIL_BACK_REF = GL_STENCIL_BACK_REF,
    _ES2_GL_STENCIL_BACK_VALUE_MASK = GL_STENCIL_BACK_VALUE_MASK,
    _ES2_GL_STENCIL_BACK_WRITEMASK = GL_STENCIL_BACK_WRITEMASK,
    _ES2_GL_VIEWPORT = GL_VIEWPORT,
    _ES2_GL_SCISSOR_BOX = GL_SCISSOR_BOX,
    /*      GL_SCISSOR_TEST */
    _ES2_GL_COLOR_CLEAR_VALUE = GL_COLOR_CLEAR_VALUE,
    _ES2_GL_COLOR_WRITEMASK = GL_COLOR_WRITEMASK,
    _ES2_GL_UNPACK_ALIGNMENT = GL_UNPACK_ALIGNMENT,
    _ES2_GL_PACK_ALIGNMENT = GL_PACK_ALIGNMENT,
    _ES2_GL_MAX_TEXTURE_SIZE = GL_MAX_TEXTURE_SIZE,
    _ES2_GL_MAX_VIEWPORT_DIMS = GL_MAX_VIEWPORT_DIMS,
    _ES2_GL_SUBPIXEL_BITS = GL_SUBPIXEL_BITS,
    _ES2_GL_RED_BITS = GL_RED_BITS,
    _ES2_GL_GREEN_BITS = GL_GREEN_BITS,
    _ES2_GL_BLUE_BITS = GL_BLUE_BITS,
    _ES2_GL_ALPHA_BITS = GL_ALPHA_BITS,
    _ES2_GL_DEPTH_BITS = GL_DEPTH_BITS,
    _ES2_GL_STENCIL_BITS = GL_STENCIL_BITS,
    _ES2_GL_POLYGON_OFFSET_UNITS = GL_POLYGON_OFFSET_UNITS,
    /*      GL_POLYGON_OFFSET_FILL */
    _ES2_GL_POLYGON_OFFSET_FACTOR = GL_POLYGON_OFFSET_FACTOR,
    _ES2_GL_TEXTURE_BINDING_2D = GL_TEXTURE_BINDING_2D,
    _ES2_GL_SAMPLE_BUFFERS = GL_SAMPLE_BUFFERS,
    _ES2_GL_SAMPLES = GL_SAMPLES,
    _ES2_GL_SAMPLE_COVERAGE_VALUE = GL_SAMPLE_COVERAGE_VALUE,
    _ES2_GL_SAMPLE_COVERAGE_INVERT = GL_SAMPLE_COVERAGE_INVERT,
    
    /* GetTextureParameter */
    /*      GL_TEXTURE_MAG_FILTER */
    /*      GL_TEXTURE_MIN_FILTER */
    /*      GL_TEXTURE_WRAP_S */
    /*      GL_TEXTURE_WRAP_T */
    
    _ES2_GL_NUM_COMPRESSED_TEXTURE_FORMATS = GL_NUM_COMPRESSED_TEXTURE_FORMATS,
    _ES2_GL_COMPRESSED_TEXTURE_FORMATS = GL_COMPRESSED_TEXTURE_FORMATS,
    
    /* HintMode */
    _ES2_GL_DONT_CARE = GL_DONT_CARE,
    _ES2_GL_FASTEST = GL_FASTEST,
    _ES2_GL_NICEST = GL_NICEST,
    
    /* HintTarget */
    _ES2_GL_GENERATE_MIPMAP_HINT = GL_GENERATE_MIPMAP_HINT,
    
    /* DataType */
    _ES2_GL_BYTE = GL_BYTE,
    _ES2_GL_UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
    _ES2_GL_SHORT = GL_SHORT,
    _ES2_GL_UNSIGNED_SHORT = GL_UNSIGNED_SHORT,
    _ES2_GL_INT = GL_INT,
    _ES2_GL_UNSIGNED_INT = GL_UNSIGNED_INT,
    _ES2_GL_FLOAT = GL_FLOAT,
    _ES2_GL_FIXED = GL_FIXED,
    
    /* PixelFormat */
    _ES2_GL_DEPTH_COMPONENT = GL_DEPTH_COMPONENT,
    _ES2_GL_ALPHA = GL_ALPHA,
    _ES2_GL_RGB = GL_RGB,
    _ES2_GL_RGBA = GL_RGBA,
    _ES2_GL_LUMINANCE = GL_LUMINANCE,
    _ES2_GL_LUMINANCE_ALPHA = GL_LUMINANCE_ALPHA,
    
    /* PixelType */
    /*      GL_UNSIGNED_BYTE */
    _ES2_GL_UNSIGNED_SHORT_4_4_4_4 = GL_UNSIGNED_SHORT_4_4_4_4,
    _ES2_GL_UNSIGNED_SHORT_5_5_5_1 = GL_UNSIGNED_SHORT_5_5_5_1,
    _ES2_GL_UNSIGNED_SHORT_5_6_5 = GL_UNSIGNED_SHORT_5_6_5,
    
    /* Shaders */
    _ES2_GL_FRAGMENT_SHADER = GL_FRAGMENT_SHADER,
    _ES2_GL_VERTEX_SHADER = GL_VERTEX_SHADER,
    _ES2_GL_MAX_VERTEX_ATTRIBS = GL_MAX_VERTEX_ATTRIBS,
    _ES2_GL_MAX_VERTEX_UNIFORM_VECTORS = GL_MAX_VERTEX_UNIFORM_VECTORS,
    _ES2_GL_MAX_VARYING_VECTORS = GL_MAX_VARYING_VECTORS,
    _ES2_GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS,
    _ES2_GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS,
    _ES2_GL_MAX_TEXTURE_IMAGE_UNITS = GL_MAX_TEXTURE_IMAGE_UNITS,
    _ES2_GL_MAX_FRAGMENT_UNIFORM_VECTORS = GL_MAX_FRAGMENT_UNIFORM_VECTORS,
    _ES2_GL_SHADER_TYPE = GL_SHADER_TYPE,
    _ES2_GL_DELETE_STATUS = GL_DELETE_STATUS,
    _ES2_GL_LINK_STATUS = GL_LINK_STATUS,
    _ES2_GL_VALIDATE_STATUS = GL_VALIDATE_STATUS,
    _ES2_GL_ATTACHED_SHADERS = GL_ATTACHED_SHADERS,
    _ES2_GL_ACTIVE_UNIFORMS = GL_ACTIVE_UNIFORMS,
    _ES2_GL_ACTIVE_UNIFORM_MAX_LENGTH = GL_ACTIVE_UNIFORM_MAX_LENGTH,
    _ES2_GL_ACTIVE_ATTRIBUTES = GL_ACTIVE_ATTRIBUTES,
    _ES2_GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = GL_ACTIVE_ATTRIBUTE_MAX_LENGTH,
    _ES2_GL_SHADING_LANGUAGE_VERSION = GL_SHADING_LANGUAGE_VERSION,
    _ES2_GL_CURRENT_PROGRAM = GL_CURRENT_PROGRAM,
    
    /* StencilFunction */
    _ES2_GL_NEVER = GL_NEVER,
    _ES2_GL_LESS = GL_LESS,
    _ES2_GL_EQUAL = GL_EQUAL,
    _ES2_GL_LEQUAL = GL_LEQUAL,
    _ES2_GL_GREATER = GL_GREATER,
    _ES2_GL_NOTEQUAL = GL_NOTEQUAL,
    _ES2_GL_GEQUAL = GL_GEQUAL,
    _ES2_GL_ALWAYS = GL_ALWAYS,
    
    /* StencilOp */
    /*      GL_ZERO */
    _ES2_GL_KEEP = GL_KEEP,
    _ES2_GL_REPLACE = GL_REPLACE,
    _ES2_GL_INCR = GL_INCR,
    _ES2_GL_DECR = GL_DECR,
    _ES2_GL_INVERT = GL_INVERT,
    _ES2_GL_INCR_WRAP = GL_INCR_WRAP,
    _ES2_GL_DECR_WRAP = GL_DECR_WRAP,
    
    /* StringName */
    _ES2_GL_VENDOR = GL_VENDOR,
    _ES2_GL_RENDERER = GL_RENDERER,
    _ES2_GL_VERSION = GL_VERSION,
    _ES2_GL_EXTENSIONS = GL_EXTENSIONS,
    
    /* TextureMagFilter */
    _ES2_GL_NEAREST = GL_NEAREST,
    _ES2_GL_LINEAR = GL_LINEAR,
    
    /* TextureMinFilter */
    /*      GL_NEAREST */
    /*      GL_LINEAR */
    _ES2_GL_NEAREST_MIPMAP_NEAREST = GL_NEAREST_MIPMAP_NEAREST,
    _ES2_GL_LINEAR_MIPMAP_NEAREST = GL_LINEAR_MIPMAP_NEAREST,
    _ES2_GL_NEAREST_MIPMAP_LINEAR = GL_NEAREST_MIPMAP_LINEAR,
    _ES2_GL_LINEAR_MIPMAP_LINEAR = GL_LINEAR_MIPMAP_LINEAR,
    
    /* TextureParameterName */
    _ES2_GL_TEXTURE_MAG_FILTER = GL_TEXTURE_MAG_FILTER,
    _ES2_GL_TEXTURE_MIN_FILTER = GL_TEXTURE_MIN_FILTER,
    _ES2_GL_TEXTURE_WRAP_S = GL_TEXTURE_WRAP_S,
    _ES2_GL_TEXTURE_WRAP_T = GL_TEXTURE_WRAP_T,
    
    /* TextureTarget */
    /*      GL_TEXTURE_2D */
    _ES2_GL_TEXTURE = GL_TEXTURE,
    
    _ES2_GL_TEXTURE_CUBE_MAP = GL_TEXTURE_CUBE_MAP,
    _ES2_GL_TEXTURE_BINDING_CUBE_MAP = GL_TEXTURE_BINDING_CUBE_MAP,
    _ES2_GL_TEXTURE_CUBE_MAP_POSITIVE_X = GL_TEXTURE_CUBE_MAP_POSITIVE_X,
    _ES2_GL_TEXTURE_CUBE_MAP_NEGATIVE_X = GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
    _ES2_GL_TEXTURE_CUBE_MAP_POSITIVE_Y = GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
    _ES2_GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y,
    _ES2_GL_TEXTURE_CUBE_MAP_POSITIVE_Z = GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
    _ES2_GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z,
    _ES2_GL_MAX_CUBE_MAP_TEXTURE_SIZE = GL_MAX_CUBE_MAP_TEXTURE_SIZE,
    
    /* TextureUnit */
    _ES2_GL_TEXTURE0 = GL_TEXTURE0,
    _ES2_GL_TEXTURE1 = GL_TEXTURE1,
    _ES2_GL_TEXTURE2 = GL_TEXTURE2,
    _ES2_GL_TEXTURE3 = GL_TEXTURE3,
    _ES2_GL_TEXTURE4 = GL_TEXTURE4,
    _ES2_GL_TEXTURE5 = GL_TEXTURE5,
    _ES2_GL_TEXTURE6 = GL_TEXTURE6,
    _ES2_GL_TEXTURE7 = GL_TEXTURE7,
    _ES2_GL_TEXTURE8 = GL_TEXTURE8,
    _ES2_GL_TEXTURE9 = GL_TEXTURE9,
    _ES2_GL_TEXTURE10 = GL_TEXTURE10,
    _ES2_GL_TEXTURE11 = GL_TEXTURE11,
    _ES2_GL_TEXTURE12 = GL_TEXTURE12,
    _ES2_GL_TEXTURE13 = GL_TEXTURE13,
    _ES2_GL_TEXTURE14 = GL_TEXTURE14,
    _ES2_GL_TEXTURE15 = GL_TEXTURE15,
    _ES2_GL_TEXTURE16 = GL_TEXTURE16,
    _ES2_GL_TEXTURE17 = GL_TEXTURE17,
    _ES2_GL_TEXTURE18 = GL_TEXTURE18,
    _ES2_GL_TEXTURE19 = GL_TEXTURE19,
    _ES2_GL_TEXTURE20 = GL_TEXTURE20,
    _ES2_GL_TEXTURE21 = GL_TEXTURE21,
    _ES2_GL_TEXTURE22 = GL_TEXTURE22,
    _ES2_GL_TEXTURE23 = GL_TEXTURE23,
    _ES2_GL_TEXTURE24 = GL_TEXTURE24,
    _ES2_GL_TEXTURE25 = GL_TEXTURE25,
    _ES2_GL_TEXTURE26 = GL_TEXTURE26,
    _ES2_GL_TEXTURE27 = GL_TEXTURE27,
    _ES2_GL_TEXTURE28 = GL_TEXTURE28,
    _ES2_GL_TEXTURE29 = GL_TEXTURE29,
    _ES2_GL_TEXTURE30 = GL_TEXTURE30,
    _ES2_GL_TEXTURE31 = GL_TEXTURE31,
    _ES2_GL_ACTIVE_TEXTURE = GL_ACTIVE_TEXTURE,
    
    /* TextureWrapMode */
    _ES2_GL_REPEAT = GL_REPEAT,
    _ES2_GL_CLAMP_TO_EDGE = GL_CLAMP_TO_EDGE,
    _ES2_GL_MIRRORED_REPEAT = GL_MIRRORED_REPEAT,
    
    /* Uniform Types */
    _ES2_GL_FLOAT_VEC2 = GL_FLOAT_VEC2,
    _ES2_GL_FLOAT_VEC3 = GL_FLOAT_VEC3,
    _ES2_GL_FLOAT_VEC4 = GL_FLOAT_VEC4,
    _ES2_GL_INT_VEC2 = GL_INT_VEC2,
    _ES2_GL_INT_VEC3 = GL_INT_VEC3,
    _ES2_GL_INT_VEC4 = GL_INT_VEC4,
    _ES2_GL_BOOL = GL_BOOL,
    _ES2_GL_BOOL_VEC2 = GL_BOOL_VEC2,
    _ES2_GL_BOOL_VEC3 = GL_BOOL_VEC3,
    _ES2_GL_BOOL_VEC4 = GL_BOOL_VEC4,
    _ES2_GL_FLOAT_MAT2 = GL_FLOAT_MAT2,
    _ES2_GL_FLOAT_MAT3 = GL_FLOAT_MAT3,
    _ES2_GL_FLOAT_MAT4 = GL_FLOAT_MAT4,
    _ES2_GL_SAMPLER_2D = GL_SAMPLER_2D,
    _ES2_GL_SAMPLER_CUBE = GL_SAMPLER_CUBE,
    
    /* Vertex Arrays */
    _ES2_GL_VERTEX_ATTRIB_ARRAY_ENABLED = GL_VERTEX_ATTRIB_ARRAY_ENABLED,
    _ES2_GL_VERTEX_ATTRIB_ARRAY_SIZE = GL_VERTEX_ATTRIB_ARRAY_SIZE,
    _ES2_GL_VERTEX_ATTRIB_ARRAY_STRIDE = GL_VERTEX_ATTRIB_ARRAY_STRIDE,
    _ES2_GL_VERTEX_ATTRIB_ARRAY_TYPE = GL_VERTEX_ATTRIB_ARRAY_TYPE,
    _ES2_GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = GL_VERTEX_ATTRIB_ARRAY_NORMALIZED,
    _ES2_GL_VERTEX_ATTRIB_ARRAY_POINTER = GL_VERTEX_ATTRIB_ARRAY_POINTER,
    _ES2_GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING,
    
    /* Read Format */
    _ES2_GL_IMPLEMENTATION_COLOR_READ_TYPE = GL_IMPLEMENTATION_COLOR_READ_TYPE,
    _ES2_GL_IMPLEMENTATION_COLOR_READ_FORMAT = GL_IMPLEMENTATION_COLOR_READ_FORMAT,
    
    /* Shader Source */
    _ES2_GL_COMPILE_STATUS = GL_COMPILE_STATUS,
    _ES2_GL_INFO_LOG_LENGTH = GL_INFO_LOG_LENGTH,
    _ES2_GL_SHADER_SOURCE_LENGTH = GL_SHADER_SOURCE_LENGTH,
    _ES2_GL_SHADER_COMPILER = GL_SHADER_COMPILER,
    
    /* Shader Binary */
    _ES2_GL_SHADER_BINARY_FORMATS = GL_SHADER_BINARY_FORMATS,
    _ES2_GL_NUM_SHADER_BINARY_FORMATS = GL_NUM_SHADER_BINARY_FORMATS,
    
    /* Shader Precision-Specified Types */
    _ES2_GL_LOW_FLOAT = GL_LOW_FLOAT,
    _ES2_GL_MEDIUM_FLOAT = GL_MEDIUM_FLOAT,
    _ES2_GL_HIGH_FLOAT = GL_HIGH_FLOAT,
    _ES2_GL_LOW_INT = GL_LOW_INT,
    _ES2_GL_MEDIUM_INT = GL_MEDIUM_INT,
    _ES2_GL_HIGH_INT = GL_HIGH_INT,
    
    /* Framebuffer Object. */
    _ES2_GL_FRAMEBUFFER = GL_FRAMEBUFFER,
    _ES2_GL_RENDERBUFFER = GL_RENDERBUFFER,
    
    _ES2_GL_RGBA4 = GL_RGBA4,
    _ES2_GL_RGB5_A1 = GL_RGB5_A1,
    _ES2_GL_RGB565 = GL_RGB565,
    _ES2_GL_DEPTH_COMPONENT16 = GL_DEPTH_COMPONENT16,
    _ES2_GL_STENCIL_INDEX8 = GL_STENCIL_INDEX8,
    
    _ES2_GL_RENDERBUFFER_WIDTH = GL_RENDERBUFFER_WIDTH,
    _ES2_GL_RENDERBUFFER_HEIGHT = GL_RENDERBUFFER_HEIGHT,
    _ES2_GL_RENDERBUFFER_INTERNAL_FORMAT = GL_RENDERBUFFER_INTERNAL_FORMAT,
    _ES2_GL_RENDERBUFFER_RED_SIZE = GL_RENDERBUFFER_RED_SIZE,
    _ES2_GL_RENDERBUFFER_GREEN_SIZE = GL_RENDERBUFFER_GREEN_SIZE,
    _ES2_GL_RENDERBUFFER_BLUE_SIZE = GL_RENDERBUFFER_BLUE_SIZE,
    _ES2_GL_RENDERBUFFER_ALPHA_SIZE = GL_RENDERBUFFER_ALPHA_SIZE,
    _ES2_GL_RENDERBUFFER_DEPTH_SIZE = GL_RENDERBUFFER_DEPTH_SIZE,
    _ES2_GL_RENDERBUFFER_STENCIL_SIZE = GL_RENDERBUFFER_STENCIL_SIZE,
    
    _ES2_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE,
    _ES2_GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME,
    _ES2_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL,
    _ES2_GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE,
    
    _ES2_GL_COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
    _ES2_GL_DEPTH_ATTACHMENT = GL_DEPTH_ATTACHMENT,
    _ES2_GL_STENCIL_ATTACHMENT = GL_STENCIL_ATTACHMENT,
    
    _ES2_GL_NONE = GL_NONE,
    
    _ES2_GL_FRAMEBUFFER_COMPLETE = GL_FRAMEBUFFER_COMPLETE,
    _ES2_GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT,
    _ES2_GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT,
    _ES2_GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS = GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS,
    _ES2_GL_FRAMEBUFFER_UNSUPPORTED = GL_FRAMEBUFFER_UNSUPPORTED,
    
    _ES2_GL_FRAMEBUFFER_BINDING = GL_FRAMEBUFFER_BINDING,
    _ES2_GL_RENDERBUFFER_BINDING = GL_RENDERBUFFER_BINDING,
    _ES2_GL_MAX_RENDERBUFFER_SIZE = GL_MAX_RENDERBUFFER_SIZE,
    
    _ES2_GL_INVALID_FRAMEBUFFER_OPERATION = GL_INVALID_FRAMEBUFFER_OPERATION,
    
    /*************************************************************/
    /*                          glext.h                          */
    /*************************************************************/
    
    _ES2_GL_APPLE_copy_texture_levels = GL_APPLE_copy_texture_levels,
    _ES2_GL_APPLE_framebuffer_multisample = GL_APPLE_framebuffer_multisample,
    _ES2_GL_APPLE_rgb_422 = GL_APPLE_rgb_422,
    _ES2_GL_APPLE_sync = GL_APPLE_sync,
    _ES2_GL_APPLE_texture_format_BGRA8888 = GL_APPLE_texture_format_BGRA8888,
    _ES2_GL_APPLE_texture_max_level = GL_APPLE_texture_max_level,
    _ES2_GL_EXT_blend_minmax = GL_EXT_blend_minmax,
    _ES2_GL_EXT_color_buffer_half_float = GL_EXT_color_buffer_half_float,
    _ES2_GL_EXT_debug_label = GL_EXT_debug_label,
    _ES2_GL_EXT_debug_marker = GL_EXT_debug_marker,
    _ES2_GL_EXT_discard_framebuffer = GL_EXT_discard_framebuffer,
    _ES2_GL_EXT_draw_instanced = GL_EXT_draw_instanced,
    _ES2_GL_EXT_instanced_arrays = GL_EXT_instanced_arrays,
    _ES2_GL_EXT_map_buffer_range = GL_EXT_map_buffer_range,
    _ES2_GL_EXT_occlusion_query_boolean = GL_EXT_occlusion_query_boolean,
    _ES2_GL_EXT_pvrtc_sRGB = GL_EXT_pvrtc_sRGB,
    _ES2_GL_EXT_read_format_bgra = GL_EXT_read_format_bgra,
    _ES2_GL_EXT_separate_shader_objects = GL_EXT_separate_shader_objects,
    _ES2_GL_EXT_shader_framebuffer_fetch = GL_EXT_shader_framebuffer_fetch,
    _ES2_GL_EXT_shader_texture_lod = GL_EXT_shader_texture_lod,
    _ES2_GL_EXT_shadow_samplers = GL_EXT_shadow_samplers,
    _ES2_GL_EXT_sRGB = GL_EXT_sRGB,
    _ES2_GL_EXT_texture_filter_anisotropic = GL_EXT_texture_filter_anisotropic,
    _ES2_GL_EXT_texture_rg = GL_EXT_texture_rg,
    _ES2_GL_EXT_texture_storage = GL_EXT_texture_storage,
    _ES2_GL_IMG_read_format = GL_IMG_read_format,
    _ES2_GL_IMG_texture_compression_pvrtc = GL_IMG_texture_compression_pvrtc,
    _ES2_GL_OES_depth_texture = GL_OES_depth_texture,
    _ES2_GL_OES_depth24 = GL_OES_depth24,
    _ES2_GL_OES_element_index_uint = GL_OES_element_index_uint,
    _ES2_GL_OES_fbo_render_mipmap = GL_OES_fbo_render_mipmap,
    _ES2_GL_OES_mapbuffer = GL_OES_mapbuffer,
    _ES2_GL_OES_packed_depth_stencil = GL_OES_packed_depth_stencil,
    _ES2_GL_OES_rgb8_rgba8 = GL_OES_rgb8_rgba8,
    _ES2_GL_OES_standard_derivatives = GL_OES_standard_derivatives,
    _ES2_GL_OES_texture_float = GL_OES_texture_float,
    _ES2_GL_OES_texture_half_float = GL_OES_texture_half_float,
    _ES2_GL_OES_texture_half_float_linear = GL_OES_texture_half_float_linear,
    _ES2_GL_OES_vertex_array_object = GL_OES_vertex_array_object,
    
    /*------------------------------------------------------------------------*
     * APPLE extension tokens
     *------------------------------------------------------------------------*/
#if GL_APPLE_framebuffer_multisample
    _ES2_GL_RENDERBUFFER_SAMPLES_APPLE = GL_RENDERBUFFER_SAMPLES_APPLE,
    _ES2_GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE = GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE,
    _ES2_GL_MAX_SAMPLES_APPLE = GL_MAX_SAMPLES_APPLE,
    _ES2_GL_READ_FRAMEBUFFER_APPLE = GL_READ_FRAMEBUFFER_APPLE,
    _ES2_GL_DRAW_FRAMEBUFFER_APPLE = GL_DRAW_FRAMEBUFFER_APPLE,
    _ES2_GL_DRAW_FRAMEBUFFER_BINDING_APPLE = GL_DRAW_FRAMEBUFFER_BINDING_APPLE,
    _ES2_GL_READ_FRAMEBUFFER_BINDING_APPLE = GL_READ_FRAMEBUFFER_BINDING_APPLE,
#endif
    
#if GL_APPLE_rgb_422
    _ES2_GL_RGB_422_APPLE = GL_RGB_422_APPLE,
    _ES2_GL_UNSIGNED_SHORT_8_8_APPLE = GL_UNSIGNED_SHORT_8_8_APPLE,
    _ES2_GL_UNSIGNED_SHORT_8_8_REV_APPLE = GL_UNSIGNED_SHORT_8_8_REV_APPLE,
#endif
    
#if GL_APPLE_sync
    _ES2_GL_MAX_SERVER_WAIT_TIMEOUT_APPLE = GL_MAX_SERVER_WAIT_TIMEOUT_APPLE,
    _ES2_GL_OBJECT_TYPE_APPLE = GL_OBJECT_TYPE_APPLE,
    _ES2_GL_SYNC_CONDITION_APPLE = GL_SYNC_CONDITION_APPLE,
    _ES2_GL_SYNC_STATUS_APPLE = GL_SYNC_STATUS_APPLE,
    _ES2_GL_SYNC_FLAGS_APPLE = GL_SYNC_FLAGS_APPLE,
    _ES2_GL_SYNC_FENCE_APPLE = GL_SYNC_FENCE_APPLE,
    _ES2_GL_SYNC_GPU_COMMANDS_COMPLETE_APPLE = GL_SYNC_GPU_COMMANDS_COMPLETE_APPLE,
    _ES2_GL_UNSIGNALED_APPLE = GL_UNSIGNALED_APPLE,
    _ES2_GL_SIGNALED_APPLE = GL_SIGNALED_APPLE,
    _ES2_GL_ALREADY_SIGNALED_APPLE = GL_ALREADY_SIGNALED_APPLE,
    _ES2_GL_TIMEOUT_EXPIRED_APPLE = GL_TIMEOUT_EXPIRED_APPLE,
    _ES2_GL_CONDITION_SATISFIED_APPLE = GL_CONDITION_SATISFIED_APPLE,
    _ES2_GL_WAIT_FAILED_APPLE = GL_WAIT_FAILED_APPLE,
    _ES2_GL_SYNC_FLUSH_COMMANDS_BIT_APPLE = GL_SYNC_FLUSH_COMMANDS_BIT_APPLE,
    //_ES2_GL_TIMEOUT_IGNORED_APPLE = GL_TIMEOUT_IGNORED_APPLE,
    _ES2_GL_SYNC_OBJECT_APPLE = GL_SYNC_OBJECT_APPLE,
#endif
    
#if GL_APPLE_texture_format_BGRA8888
    _ES2_GL_BGRA_EXT = GL_BGRA_EXT,
#endif
    
#if GL_APPLE_texture_format_BGRA8888 || GL_IMG_read_format
    _ES2_GL_BGRA = GL_BGRA,
#endif
    
#if GL_APPLE_texture_max_level
    _ES2_GL_TEXTURE_MAX_LEVEL_APPLE = GL_TEXTURE_MAX_LEVEL_APPLE,
#endif
    
    /*------------------------------------------------------------------------*
     * EXT extension tokens
     *------------------------------------------------------------------------*/
    
#if GL_EXT_blend_minmax
    _ES2_GL_MIN_EXT = GL_MIN_EXT,
    _ES2_GL_MAX_EXT = GL_MAX_EXT,
#endif
    
#if GL_EXT_color_buffer_half_float
    _ES2_GL_RGBA16F_EXT = GL_RGBA16F_EXT,
    _ES2_GL_RGB16F_EXT = GL_RGB16F_EXT,
    _ES2_GL_RG16F_EXT = GL_RG16F_EXT,
    _ES2_GL_R16F_EXT = GL_R16F_EXT,
    _ES2_GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT = GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT,
    _ES2_GL_UNSIGNED_NORMALIZED_EXT = GL_UNSIGNED_NORMALIZED_EXT,
#endif
    
#if GL_EXT_debug_label
    _ES2_GL_BUFFER_OBJECT_EXT = GL_BUFFER_OBJECT_EXT,
    _ES2_GL_SHADER_OBJECT_EXT = GL_SHADER_OBJECT_EXT,
    _ES2_GL_PROGRAM_OBJECT_EXT = GL_PROGRAM_OBJECT_EXT,
    _ES2_GL_QUERY_OBJECT_EXT = GL_QUERY_OBJECT_EXT,
    _ES2_GL_VERTEX_ARRAY_OBJECT_EXT = GL_VERTEX_ARRAY_OBJECT_EXT,
    _ES2_GL_PROGRAM_PIPELINE_OBJECT_EXT = GL_PROGRAM_PIPELINE_OBJECT_EXT,
    /*      GL_SYNC_OBJECT_APPLE */
#endif
    
#if GL_EXT_discard_framebuffer
    _ES2_GL_COLOR_EXT = GL_COLOR_EXT,
    _ES2_GL_DEPTH_EXT = GL_DEPTH_EXT,
    _ES2_GL_STENCIL_EXT = GL_STENCIL_EXT,
#endif
    
#if GL_EXT_instanced_arrays
    _ES2_GL_VERTEX_ATTRIB_ARRAY_DIVISOR_EXT = GL_VERTEX_ATTRIB_ARRAY_DIVISOR_EXT,
#endif
    
#if GL_EXT_map_buffer_range
    _ES2_GL_MAP_READ_BIT_EXT = GL_MAP_READ_BIT_EXT,
    _ES2_GL_MAP_WRITE_BIT_EXT = GL_MAP_WRITE_BIT_EXT,
    _ES2_GL_MAP_INVALIDATE_RANGE_BIT_EXT = GL_MAP_INVALIDATE_RANGE_BIT_EXT,
    _ES2_GL_MAP_INVALIDATE_BUFFER_BIT_EXT = GL_MAP_INVALIDATE_BUFFER_BIT_EXT,
    _ES2_GL_MAP_FLUSH_EXPLICIT_BIT_EXT = GL_MAP_FLUSH_EXPLICIT_BIT_EXT,
    _ES2_GL_MAP_UNSYNCHRONIZED_BIT_EXT = GL_MAP_UNSYNCHRONIZED_BIT_EXT,
#endif
    
#if GL_EXT_occlusion_query_boolean
    _ES2_GL_ANY_SAMPLES_PASSED_EXT = GL_ANY_SAMPLES_PASSED_EXT,
    _ES2_GL_ANY_SAMPLES_PASSED_CONSERVATIVE_EXT = GL_ANY_SAMPLES_PASSED_CONSERVATIVE_EXT,
    _ES2_GL_CURRENT_QUERY_EXT = GL_CURRENT_QUERY_EXT,
    _ES2_GL_QUERY_RESULT_EXT = GL_QUERY_RESULT_EXT,
    _ES2_GL_QUERY_RESULT_AVAILABLE_EXT = GL_QUERY_RESULT_AVAILABLE_EXT,
#endif
    
#if GL_EXT_pvrtc_sRGB
    _ES2_GL_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT = GL_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT,
    _ES2_GL_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT = GL_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT,
    _ES2_GL_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT = GL_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT,
    _ES2_GL_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT = GL_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT,
#endif
    
#if GL_EXT_read_format_bgra
    _ES2_GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT = GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT,
    _ES2_GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT = GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT,
    _ES2_GL_UNSIGNED_SHORT_1_5_5_5_REV = GL_UNSIGNED_SHORT_1_5_5_5_REV,
#endif
    
#if GL_EXT_read_format_bgra || GL_IMG_read_format
    _ES2_GL_UNSIGNED_SHORT_4_4_4_4_REV = GL_UNSIGNED_SHORT_4_4_4_4_REV,
#endif
    
#if GL_EXT_separate_shader_objects
    _ES2_GL_VERTEX_SHADER_BIT_EXT = GL_VERTEX_SHADER_BIT_EXT,
    _ES2_GL_FRAGMENT_SHADER_BIT_EXT = GL_FRAGMENT_SHADER_BIT_EXT,
    _ES2_GL_ALL_SHADER_BITS_EXT = GL_ALL_SHADER_BITS_EXT,
    _ES2_GL_PROGRAM_SEPARABLE_EXT = GL_PROGRAM_SEPARABLE_EXT,
    _ES2_GL_ACTIVE_PROGRAM_EXT = GL_ACTIVE_PROGRAM_EXT,
    _ES2_GL_PROGRAM_PIPELINE_BINDING_EXT = GL_PROGRAM_PIPELINE_BINDING_EXT,
#endif
    
#if GL_EXT_shader_framebuffer_fetch
    _ES2_GL_FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT = GL_FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT,
#endif
    
#if GL_EXT_shadow_samplers
    _ES2_GL_TEXTURE_COMPARE_MODE_EXT = GL_TEXTURE_COMPARE_MODE_EXT,
    _ES2_GL_TEXTURE_COMPARE_FUNC_EXT = GL_TEXTURE_COMPARE_FUNC_EXT,
    _ES2_GL_COMPARE_REF_TO_TEXTURE_EXT = GL_COMPARE_REF_TO_TEXTURE_EXT,
    _ES2_GL_SAMPLER_2D_SHADOW_EXT = GL_SAMPLER_2D_SHADOW_EXT,
#endif
    
#if GL_EXT_sRGB
    _ES2_GL_SRGB_EXT = GL_SRGB_EXT,
    _ES2_GL_SRGB_ALPHA_EXT = GL_SRGB_ALPHA_EXT,
    _ES2_GL_SRGB8_ALPHA8_EXT = GL_SRGB8_ALPHA8_EXT,
    _ES2_GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT = GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT,
#endif
    
#if GL_EXT_texture_filter_anisotropic
    _ES2_GL_TEXTURE_MAX_ANISOTROPY_EXT = GL_TEXTURE_MAX_ANISOTROPY_EXT,
    _ES2_GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT = GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT,
#endif
    
#if GL_EXT_texture_rg
    _ES2_GL_RED_EXT = GL_RED_EXT,
    _ES2_GL_RG_EXT = GL_RG_EXT,
    _ES2_GL_R8_EXT = GL_R8_EXT,
    _ES2_GL_RG8_EXT = GL_RG8_EXT,
#endif
    
#if GL_EXT_texture_storage
    _ES2_GL_TEXTURE_IMMUTABLE_FORMAT_EXT = GL_TEXTURE_IMMUTABLE_FORMAT_EXT,
    _ES2_GL_ALPHA8_EXT = GL_ALPHA8_EXT,
    _ES2_GL_LUMINANCE8_EXT = GL_LUMINANCE8_EXT,
    _ES2_GL_LUMINANCE8_ALPHA8_EXT = GL_LUMINANCE8_ALPHA8_EXT,
    _ES2_GL_BGRA8_EXT = GL_BGRA8_EXT,
    _ES2_GL_RGBA32F_EXT = GL_RGBA32F_EXT,
    _ES2_GL_RGB32F_EXT = GL_RGB32F_EXT,
    _ES2_GL_RG32F_EXT = GL_RG32F_EXT,
    _ES2_GL_R32F_EXT = GL_R32F_EXT,
    _ES2_GL_ALPHA32F_EXT = GL_ALPHA32F_EXT,
    _ES2_GL_LUMINANCE32F_EXT = GL_LUMINANCE32F_EXT,
    _ES2_GL_LUMINANCE_ALPHA32F_EXT = GL_LUMINANCE_ALPHA32F_EXT,
    _ES2_GL_ALPHA16F_EXT = GL_ALPHA16F_EXT,
    _ES2_GL_LUMINANCE16F_EXT = GL_LUMINANCE16F_EXT,
    _ES2_GL_LUMINANCE_ALPHA16F_EXT = GL_LUMINANCE_ALPHA16F_EXT,
    _ES2_GL_DEPTH_COMPONENT32_OES = GL_DEPTH_COMPONENT32_OES,
    _ES2_GL_RGB_RAW_422_APPLE = GL_RGB_RAW_422_APPLE,
#endif
    
    /*------------------------------------------------------------------------*
     * IMG extension tokens
     *------------------------------------------------------------------------*/
#if GL_IMG_read_format
    _ES2_GL_BGRA_IMG = GL_BGRA_IMG,
    _ES2_GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG = GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG,
#endif
    
#if GL_IMG_texture_compression_pvrtc
    _ES2_GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG = GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
    _ES2_GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG = GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
    _ES2_GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG = GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
    _ES2_GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG = GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
#endif
    
    /*------------------------------------------------------------------------*
     * OES extension tokens
     *------------------------------------------------------------------------*/
#if GL_OES_depth24
    _ES2_GL_DEPTH_COMPONENT24_OES = GL_DEPTH_COMPONENT24_OES,
#endif
    
#if GL_OES_mapbuffer
    _ES2_GL_WRITE_ONLY_OES = GL_WRITE_ONLY_OES,
    _ES2_GL_BUFFER_ACCESS_OES = GL_BUFFER_ACCESS_OES,
    _ES2_GL_BUFFER_MAPPED_OES = GL_BUFFER_MAPPED_OES,
    _ES2_GL_BUFFER_MAP_POINTER_OES = GL_BUFFER_MAP_POINTER_OES,
#endif
    
#if GL_OES_packed_depth_stencil
    _ES2_GL_DEPTH_STENCIL_OES = GL_DEPTH_STENCIL_OES,
    _ES2_GL_UNSIGNED_INT_24_8_OES = GL_UNSIGNED_INT_24_8_OES,
    _ES2_GL_DEPTH24_STENCIL8_OES = GL_DEPTH24_STENCIL8_OES,
#endif
    
#if GL_OES_rgb8_rgba8
    _ES2_GL_RGB8_OES = GL_RGB8_OES,
    _ES2_GL_RGBA8_OES = GL_RGBA8_OES,
#endif
    
#if GL_OES_standard_derivatives
    _ES2_GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES = GL_FRAGMENT_SHADER_DERIVATIVE_HINT_OES,
#endif
    
#if GL_OES_texture_half_float
    _ES2_GL_HALF_FLOAT_OES = GL_HALF_FLOAT_OES,
#endif
    
#if GL_OES_vertex_array_object
    _ES2_GL_VERTEX_ARRAY_BINDING_OES = GL_VERTEX_ARRAY_BINDING_OES,
#endif
    
    /**************************************************************************/
    
};

typedef enum _ES2_ ES2;

#endif /* __OpenGLES_ES2_Defines_H */
