#!/bin/bash

set -e

GIT_REPO_URL="$1"
GIT_REPO_BRANCH="$2"

if [ -d libffi ]; then
    echo "Removing libffi"
    rm -rf libffi
fi
if [ -d libffi ]; then
    echo "Failed to remove libffi"
    exit 1
fi

if [ "$GIT_REPO_URL" != "" ]
then
    echo "Cloning $GIT_REPO_URL libffi branch $GIT_REPO_BRANCH"
    git clone -b $GIT_REPO_BRANCH $GIT_REPO_URL
    if [ $? -ne 0 ]; then
        echo "Failed to clone libffi branch named $GIT_REPO_BRANCH"
        exit 1
    fi
elif [ "1" == "$NATJ_IGNORE_PREBUILT_FFI" ]
then
    echo "Linking local libffi checkout"
    ln -s ../libffi libffi

    cd libffi
    chmod a+x build_moe.sh
    if [ $? -ne 0 ]; then
        echo "Failed to add build_moe.sh executable permission"
        exit 1
    fi
    ./build_moe_all.sh
else
    echo "Linking prebuilt libffi"
    ln -s ../prebuilt/libffi libffi
fi
