import org.jetbrains.kotlin.gradle.dsl.JvmTarget

/*
Copyright (C) 2016 Migeran

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

plugins {
    id 'org.moe.java-conventions'
    id "org.jetbrains.kotlin.jvm"
    alias(libs.plugins.shadow)
    id "maven-publish"
    id "signing"
}

if (name != 'moe-gradle') {
    throw new GradleException('Incorrect name')
}
group = 'org.multi-os-engine'

version = MOE_VERSION + (project.hasProperty('RELEASE') ? '' : '-SNAPSHOT')

processResources {
    def moeVer = version
    inputs.property('version', moeVer)
    filesMatching('**/moe.properties') {
        expand('MOE_VERSION': moeVer)
    }
}

configurations {
    shade {
        canBeResolved = true
        canBeConsumed = false
        exclude group: 'org.jetbrains.kotlin'
        exclude group: 'org.jetbrains', module: 'annotations'
    }
    compileOnly.extendsFrom shade
    testImplementation.extendsFrom shade
}

dependencies {
    compileOnly gradleApi()

    shade project(':moe.tools.common')
    shade project(':moe.document.pbxproj')
    shade project(':moe.generator.project')
    shade project(':moe.tools.substrate')
    shade project(':moe.tools.classvalidator')

    shade libs.commons.lang3
    shade libs.commons.io
    shade libs.jsch
    shade libs.asm
    shade libs.asm.tree
    shade libs.asm.commons
    shade libs.gson
    shade libs.slf4j.api
    shade libs.dd.plist
    shade libs.commons.codec

    testImplementation libs.junit
    testImplementation gradleTestKit()
}

tasks.test.dependsOn ':moe-sdk:devsdk'

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    configurations = [project.configurations.shade]
    archiveClassifier = ''
    mergeServiceFiles()
    enableAutoRelocation = true
    relocationPrefix = 'org.moe.gradle.shadow'
    relocate('org.moe', 'org.moe')
}

jar {
    archiveClassifier = 'plain'
}

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.shadow
            artifact tasks.named('sourcesJar')
            artifact tasks.named('javadocJar')
            artifactId = 'moe-gradle'

            pom {
                name = 'moe-gradle'
                packaging = 'jar'
                description = 'MOE Gradle Plugin'
                url = POM_URL

                scm {
                    url = POM_SCM_URL
                }

                licenses {
                    license {
                        name = POM_LICENCE_NAME
                        url = POM_LICENCE_URL
                    }
                }

                developers {
                    developer {
                        id = POM_DEVELOPER_ID
                        name = POM_DEVELOPER_NAME
                        organization = POM_DEVELOPER_ORGANISATION
                        organizationUrl = POM_DEVELOPER_ORGANISATION_URL
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = 'MavenCentral'
            url = version.endsWith('SNAPSHOT') ? SONATYPE_SNAPSHOT_URL : SONATYPE_RELEASE_URL

            credentials {
                if (project.hasProperty('ossrhUsername')) {
                    username = ossrhUsername
                }
                if (project.hasProperty('ossrhPassword')) {
                    password = ossrhPassword
                }
            }
        }
    }
}

if (project.hasProperty("signing.gnupg.keyId")) {
    signing {
        useGpgCmd()
        sign publishing.publications.mavenJava
    }
}

// Write the plugin's classpath to a file to share with the tests
def createClasspathManifest = tasks.register('createClasspathManifest') {
    def outputDir = layout.buildDirectory.dir(name).get().asFile
    def runtimeClasspath = sourceSets.main.runtimeClasspath
    def shadeClasspath = configurations.shade
    def sdkLocalBuildPath = project(':moe-sdk').file('build/dev-sdk')
    def pluginVersion = project.version

    inputs.files runtimeClasspath
    outputs.dir outputDir

    doLast {
        outputDir.mkdirs()
        new File(outputDir, 'plugin-classpath.txt').text = (runtimeClasspath + shadeClasspath).join("\n")
        new File(outputDir, 'plugin-sdk-localbuild.txt').text = sdkLocalBuildPath.toString()
        new File(outputDir, 'plugin-version.txt').text = pluginVersion.toString()
    }
}

// Add the classpath file to the test runtime classpath
dependencies {
    testRuntimeOnly files(createClasspathManifest)
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_1_8
    }
}
