package apple.network.enums;

import org.moe.natj.general.ann.Generated;

/**
 * @typedef nw_service_class_t
 * @abstract
 * 	The network service class represents the network queuing priority to use
 * 	for traffic generated by a connection.
 */
@Generated
public final class nw_service_class_t {
    @Generated
    private nw_service_class_t() {
    }

    /**
     * @const nw_service_class_best_effort Default priority traffic
     */
    @Generated public static final int nw_service_class_best_effort = 0x00000000;
    /**
     * @const nw_service_class_background Bulk traffic, or traffic that can be de-prioritized behind foreground traffic
     */
    @Generated public static final int nw_service_class_background = 0x00000001;
    /**
     * @const nw_service_class_interactive_video Interactive video traffic
     */
    @Generated public static final int nw_service_class_interactive_video = 0x00000002;
    /**
     * @const nw_service_class_interactive_voice Interactive voice traffic
     */
    @Generated public static final int nw_service_class_interactive_voice = 0x00000003;
    /**
     * @const nw_service_class_responsive_data Interactive user data
     */
    @Generated public static final int nw_service_class_responsive_data = 0x00000004;
    /**
     * @const nw_service_class_signaling Bursty but short. Intolerant of delay and loss. For example, SIP.
     */
    @Generated public static final int nw_service_class_signaling = 0x00000005;
}