MOE_VERSION=2.0.0

POM_URL=https://discuss.multi-os-engine.org
POM_SCM_URL=https://github.com/multi-os-engine/multi-os-engine
POM_LICENCE_NAME=The Apache License, Version 2.0
POM_LICENCE_URL=http://www.apache.org/licenses/LICENSE-2.0.txt
POM_DEVELOPER_ID=MOE
POM_DEVELOPER_NAME=Multi-OS Engine Dev
POM_DEVELOPER_ORGANISATION=Multi-OS Engine
POM_DEVELOPER_ORGANISATION_URL=https://www.multi-os-engine.org/

SONATYPE_RELEASE_URL=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/
SONATYPE_SNAPSHOT_URL=https://central.sonatype.com/repository/maven-snapshots/
