/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import org.moe.prebuilts.XcodeBuild

plugins {
    id 'org.moe.buildtools'
}

apply plugin: 'maven-publish'

ext {
    nativeOutputs = []
}

def useAsan = providers.gradleProperty("moe.use.addresssanitizer").isPresent()

def buildNativeTarget = { xcodeproject, configuration, sdk, target ->
    def productDest = layout.buildDirectory.dir("xcode/${configuration}-${sdk}").get().asFile.path
    def outputFile = "${productDest}/libnatj.a"
    project.nativeOutputs.add(outputFile)
    return tasks.register("build_${target}_${configuration}_${sdk}", XcodeBuild) {
        xcodeProject.set(file(xcodeproject))
        setConfiguration(configuration)
        setTarget(target)
        setSdk(sdk)
        if (useAsan) {
            extraArgs('-enableAddressSanitizer', 'YES')
        }
        dependsOn ":prebuild_libffi_ios"
        inputs.dir rootProject.file('src')
        inputs.dir file(xcodeproject)
        outputs.file outputFile
        outputs.upToDateWhen { false }
    }
}

// Create build task
def nativeTasks = [
    buildNativeTarget("natj.xcodeproj", "Release", "iphoneos", "natj"),
    buildNativeTarget("natj.xcodeproj", "Release", "iphonesimulator", "natj"),
    buildNativeTarget("natj.xcodeproj", "Debug", "iphoneos", "natj"),
    buildNativeTarget("natj.xcodeproj", "Debug", "iphonesimulator", "natj"),
]

tasks.register('build') {
    dependsOn nativeTasks
}

tasks.register('buildAll') {
    dependsOn 'build'
}

// Create clean task
tasks.register('clean', Delete) {
    delete layout.buildDirectory
}

// Setup publishing
tasks.publish.dependsOn build
publishing {
    publications {
        mavenNative(MavenPublication) {
            artifactId 'natj-ios'

            for (o in nativeOutputs) {
                artifact source: o, extension: 'a', classifier: new File(o).getParentFile().getName()
            }
        }
    }
}
