/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


#include <iostream>

#include "dex/quick/resource_mask.h"

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
std::ostream& operator<<(std::ostream& os, const ResourceMask::ResourceBit& rhs) {
  switch (rhs) {
    case ResourceMask::kMustNotAlias: os << "MustNotAlias"; break;
    case ResourceMask::kHeapRef: os << "HeapRef"; break;
    case ResourceMask::kLiteral: os << "Literal"; break;
    case ResourceMask::kDalvikReg: os << "DalvikReg"; break;
    case ResourceMask::kFPStatus: os << "FPStatus"; break;
    case ResourceMask::kCCode: os << "CCode"; break;
    default: os << "ResourceMask::ResourceBit[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace art

