/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


#include <iostream>

#include "dex_instruction_utils.h"

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
std::ostream& operator<<(std::ostream& os, const DexMemAccessType& rhs) {
  switch (rhs) {
    case kDexMemAccessWord: os << "DexMemAccessWord"; break;
    case kDexMemAccessWide: os << "DexMemAccessWide"; break;
    case kDexMemAccessObject: os << "DexMemAccessObject"; break;
    case kDexMemAccessBoolean: os << "DexMemAccessBoolean"; break;
    case kDexMemAccessByte: os << "DexMemAccessByte"; break;
    case kDexMemAccessChar: os << "DexMemAccessChar"; break;
    case kDexMemAccessShort: os << "DexMemAccessShort"; break;
    case kDexMemAccessTypeCount: os << "DexMemAccessTypeCount"; break;
    default: os << "DexMemAccessType[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace art

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
std::ostream& operator<<(std::ostream& os, const DexInvokeType& rhs) {
  switch (rhs) {
    case kDexInvokeVirtual: os << "DexInvokeVirtual"; break;
    case kDexInvokeSuper: os << "DexInvokeSuper"; break;
    case kDexInvokeDirect: os << "DexInvokeDirect"; break;
    case kDexInvokeStatic: os << "DexInvokeStatic"; break;
    case kDexInvokeInterface: os << "DexInvokeInterface"; break;
    case kDexInvokeTypeCount: os << "DexInvokeTypeCount"; break;
    default: os << "DexInvokeType[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace art

