/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


#include <iostream>

#include "gc/heap.h"

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace gc {
std::ostream& operator<<(std::ostream& os, const HomogeneousSpaceCompactResult& rhs) {
  switch (rhs) {
    case kSuccess: os << "Success"; break;
    case kErrorReject: os << "ErrorReject"; break;
    case kErrorUnsupported: os << "ErrorUnsupported"; break;
    case kErrorVMShuttingDown: os << "ErrorVMShuttingDown"; break;
    default: os << "HomogeneousSpaceCompactResult[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace gc
}  // namespace art

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace gc {
std::ostream& operator<<(std::ostream& os, const ProcessState& rhs) {
  switch (rhs) {
    case kProcessStateJankPerceptible: os << "ProcessStateJankPerceptible"; break;
    case kProcessStateJankImperceptible: os << "ProcessStateJankImperceptible"; break;
    default: os << "ProcessState[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace gc
}  // namespace art

