/*
Copyright 2014-2016 Intel Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


#include <iostream>

#include "instrumentation.h"

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace instrumentation {
std::ostream& operator<<(std::ostream& os, const InterpreterHandlerTable& rhs) {
  switch (rhs) {
    case kMainHandlerTable: os << "MainHandlerTable"; break;
    case kAlternativeHandlerTable: os << "AlternativeHandlerTable"; break;
    case kNumHandlerTables: os << "NumHandlerTables"; break;
    default: os << "InterpreterHandlerTable[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace instrumentation
}  // namespace art

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace instrumentation {
std::ostream& operator<<(std::ostream& os, const Instrumentation::InstrumentationLevel& rhs) {
  switch (rhs) {
    case Instrumentation::InstrumentationLevel::kInstrumentNothing: os << "InstrumentNothing"; break;
    case Instrumentation::InstrumentationLevel::kInstrumentWithInstrumentationStubs: os << "InstrumentWithInstrumentationStubs"; break;
    case Instrumentation::InstrumentationLevel::kInstrumentWithInterpreter: os << "InstrumentWithInterpreter"; break;
  }
  return os;
}
}  // namespace instrumentation
}  // namespace art

// This was automatically generated by /Volumes/Android/inde-dev//art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace instrumentation {
std::ostream& operator<<(std::ostream& os, const Instrumentation::InstrumentationEvent& rhs) {
  switch (rhs) {
    case Instrumentation::kMethodEntered: os << "MethodEntered"; break;
    case Instrumentation::kMethodExited: os << "MethodExited"; break;
    case Instrumentation::kMethodUnwind: os << "MethodUnwind"; break;
    case Instrumentation::kDexPcMoved: os << "DexPcMoved"; break;
    case Instrumentation::kFieldRead: os << "FieldRead"; break;
    case Instrumentation::kFieldWritten: os << "FieldWritten"; break;
    case Instrumentation::kExceptionCaught: os << "ExceptionCaught"; break;
    case Instrumentation::kBackwardBranch: os << "BackwardBranch"; break;
    case Instrumentation::kInvokeVirtualOrInterface: os << "InvokeVirtualOrInterface"; break;
    default: os << "Instrumentation::InstrumentationEvent[" << static_cast<int>(rhs) << "]"; break;
  }
  return os;
}
}  // namespace instrumentation
}  // namespace art

