# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish MOE

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        description: Whether to make a release
        default: false
        required: true

  release:
    types: [ published ]

jobs:
  verify-release-config:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Test for release
        if: ${{ inputs.release }}
        run: echo "Building release version"

      - name: Test for snapshot
        if: ${{ inputs.release == false }}
        run: echo "Building snapshot version"

  build-and-publish:
    needs: verify-release-config
    runs-on: macos-26
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'graalvm'

      - name: Setup macOS toolchain
        run: |
          sudo mv /Library/Developer/CommandLineTools/SDKs/* /tmp
          sudo mv /Applications/Xcode.app /Applications/Xcode.app.bak
          sudo mv /Applications/Xcode_26.1.app /Applications/Xcode.app
          sudo xcode-select -switch /Applications/Xcode.app
          xcodebuild -version
          brew install autogen autoconf automake libtool pkg-config wget isl cloog cmake gpg ant maven mpfr libmpc premake texinfo

      - name: Cache libclang prebuild
        uses: actions/cache@v4
        id: llvm-cache
        with:
          path: prebuilts/llvm/macos/lib/libclang.dylib
          key: llvm-${{ hashFiles('.gitmodules') }}-xcode26.1

      - name: Build libclang
        if: steps.llvm-cache.outputs.cache-hit != 'true'
        run: ./gradlew :prebuilts:llvm

      - name: Build MOE SDK
        run: ./gradlew :tools:moe-sdk:sdk

      - name: Import GPG key
        if: ${{ inputs.release }}
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@1c6a9e9d3594f2d743f1b1dd7669ab0dfdffa922
        with:
          gpg-private-key: ${{ secrets.MOE_RELEASE_PRIVATE_KEY }}
          passphrase: ${{ secrets.MOE_RELEASE_PRIVATE_KEY_PASSPHRASE }}

      - name: Publish to Maven Central (Portal API)
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ossrhPassword }}
        run: |
          if [ "${{ inputs.release }}" = "true" ]; then
            ./gradlew :tools:moe-sdk:publishAndReleaseToMavenCentral \
                      :tools:moe-gradle:publishAndReleaseToMavenCentral \
                      -PRELEASE -Psigning.gnupg.keyId=${{ secrets.MOE_RELEASE_PRIVATE_KEY_ID }} \
                      --no-configuration-cache
          else
            ./gradlew :tools:moe-sdk:publishAllPublicationsToMavenCentralRepository \
                      :tools:moe-gradle:publishAllPublicationsToMavenCentralRepository \
                      --no-configuration-cache
          fi
